"""Phase 5 of the dream pass — regenerate the ``MEMORY.md`` index (#1933 § 6).

``MEMORY.md`` is the index of the memory set: one line per memory file, each a
clickable link plus a one-line summary (≤~200 chars), so a reader scans the
index and opens the topic file for detail. This phase REGENERATES that index
from the current ``*.md`` set under a ``memory_dir`` — it never moves content
INTO the index (the body stays in the topic file), only re-derives the one-line
pointers.

The regeneration is PURE and idempotent: the summary of each memory is derived
deterministically (its frontmatter ``summary``/``description``, else its first
non-heading prose line, clipped), lines are deduped by target filename and
stably ordered (filename sort), and a header preamble is preserved. A re-run on
an unchanged memory set produces a BYTE-IDENTICAL file — the property the test
pins. It NEVER touches the real ``~/.claude``: the caller passes an explicit
``memory_dir``; a missing dir is a clean no-op.
"""

import re
from dataclasses import dataclass
from pathlib import Path

_INDEX_NAME = "MEMORY.md"
_SUMMARY_MAX_CHARS = 200

_HEADER = (
    "# Auto Memory — Index\n\n"
    "> Generated by the dream re-index phase. One line per memory; detail lives in "
    "the topic file. Do not move content into this index.\n\n"
)

_FRONTMATTER_SUMMARY_RE = re.compile(r"^(?:summary|description):\s*(.+?)\s*$", re.MULTILINE | re.IGNORECASE)
_HEADING_RE = re.compile(r"^#{1,6}\s")


@dataclass(frozen=True, slots=True)
class ReindexResult:
    """What one phase-5 pass did: lines indexed, whether changed, whether dry."""

    lines_indexed: int
    changed: bool
    dry_run: bool


def _strip_frontmatter(text: str) -> tuple[str, str]:
    """Return (frontmatter_block, body). No frontmatter → ("", text)."""
    if not text.startswith("---"):
        return "", text
    end = text.find("---", 3)
    if end == -1:
        return "", text
    return text[3:end], text[end + 3 :]


def _first_prose_line(body: str) -> str:
    for raw in body.splitlines():
        line = raw.strip().lstrip("-*").strip()
        if line and not _HEADING_RE.match(raw.strip()):
            return line
    return ""


def _summary_for(text: str) -> str:
    front, body = _strip_frontmatter(text)
    match = _FRONTMATTER_SUMMARY_RE.search(front)
    summary = match.group(1).strip() if match else _first_prose_line(body)
    summary = " ".join(summary.split())  # collapse whitespace
    if len(summary) > _SUMMARY_MAX_CHARS:
        summary = summary[: _SUMMARY_MAX_CHARS - 1].rstrip() + "…"
    return summary


def _index_line(md: Path, summary: str) -> str:
    link = f"[{md.name}]({md.name})"
    return f"- {link} — {summary}" if summary else f"- {link}"


def render_index(memory_dir: Path) -> str:
    """Render the full ``MEMORY.md`` text for the current memory set (deterministic).

    Lines are deduped by filename and stably ordered (filename sort), so the
    output is a pure function of the memory set's content — a re-run with no
    changes renders the identical string.
    """
    seen: set[str] = set()
    lines: list[str] = []
    for md in sorted(memory_dir.glob("*.md")):
        if md.name == _INDEX_NAME or md.name in seen:
            continue
        seen.add(md.name)
        try:
            text = md.read_text(encoding="utf-8")
        except OSError:
            continue
        lines.append(_index_line(md, _summary_for(text)))
    body = "\n".join(lines)
    return f"{_HEADER}{body}\n" if body else _HEADER


def reindex_memory(memory_dir: Path, *, dry_run: bool = False) -> ReindexResult:
    """Regenerate ``MEMORY.md`` from the current memory set under *memory_dir*.

    Idempotent: the rendered index is a pure function of the set, so a re-run on
    an unchanged set writes a byte-identical file (``changed=False``). A missing
    dir is a clean no-op. Under *dry_run* the index is rendered (and ``changed``
    computed against the on-disk file) but nothing is written.
    """
    if not memory_dir.is_dir():
        return ReindexResult(lines_indexed=0, changed=False, dry_run=dry_run)
    rendered = render_index(memory_dir)
    index_path = memory_dir / _INDEX_NAME
    current = index_path.read_text(encoding="utf-8") if index_path.is_file() else ""
    changed = rendered != current
    if changed and not dry_run:
        index_path.write_text(rendered, encoding="utf-8")
    return ReindexResult(lines_indexed=_count_lines(rendered), changed=changed, dry_run=dry_run)


def _count_lines(rendered: str) -> int:
    return sum(1 for line in rendered.splitlines() if line.startswith("- "))


__all__ = ["ReindexResult", "reindex_memory", "render_index"]
