"""Phase 5 of the dream pass — regenerate the ``MEMORY.md`` index (#1933 § 6).

``MEMORY.md`` is the index of the memory set: one line per memory file, a bare
filename pointer plus a tight one-line summary, so a reader scans the index and
opens the topic file for detail. This phase REGENERATES that index from the
current ``*.md`` set under a ``memory_dir`` — it never moves content INTO the
index (the body stays in the topic file), only re-derives the one-line pointers.

Each line is ``- name.md — summary`` — a SINGLE bare filename pointer, not the
former ``[name.md](name.md)`` markdown link that listed the filename twice and
inflated the index. The summary is clipped to ``_SUMMARY_MAX_CHARS`` and the
WHOLE line is capped at ``_LINE_MAX_CHARS`` (filename intact, summary absorbing
the cap), so the index stays under the session-load budget gate (d) enforces
(#2723).

The regeneration is PURE and idempotent: the summary of each memory is derived
deterministically (its frontmatter ``summary``/``description``, else its first
non-heading prose line, clipped), lines are deduped by target filename and
stably ordered (filename sort), and a header preamble is preserved. A re-run on
an unchanged memory set produces a BYTE-IDENTICAL file — the property the test
pins. It NEVER touches the real ``~/.claude``: the caller passes an explicit
``memory_dir``; a missing dir is a clean no-op.
"""

import re
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path

_INDEX_NAME = "MEMORY.md"

#: The COLD archive index (#2723), written by the decay phase in the MAIN memory dir.
#: It is NEVER re-indexed into the hot ``MEMORY.md`` — excluded here exactly like the
#: hot index — so its one-line-per-archived-entry signatures do not re-bloat the index.
_ARCHIVE_INDEX_NAME = "MEMORY_ARCHIVE.md"

#: Per-summary clip and per-line cap (#2723). The summary is clipped first; the
#: whole line is then capped so a long filename plus a long summary can never blow
#: the per-line budget. Sized so even a long-filename line fits 140 chars and ~150
#: such lines stay under the ~24 KB session-load budget gate (d) enforces.
_SUMMARY_MAX_CHARS = 110
_LINE_MAX_CHARS = 140

_HEADER = (
    "# Auto Memory — Index\n\n"
    "> Generated by the dream re-index phase. One line per memory; detail lives in "
    "the topic file. Do not move content into this index.\n\n"
)

_FRONTMATTER_SUMMARY_RE = re.compile(r"^(?:summary|description):\s*(.+?)\s*$", re.MULTILINE | re.IGNORECASE)
_HEADING_RE = re.compile(r"^#{1,6}\s")

#: Body lines whose leading ``key:`` is metadata, not a lesson. A node-typed
#: memory whose body leads with ``node_type: memory`` must NOT have that line
#: lifted as its signature (#2746 nit-4) — skip these and take the next real
#: line. ``node_type:`` is included precisely because the bare ``type:`` prefix
#: does not match it (``node_type`` starts with ``node_``).
_METADATA_LINE_PREFIXES = ("name:", "summary:", "description:", "type:", "node_type:", "metadata:", "---")
_BINDING_MARKERS = ("binding", "non-negotiable")


@dataclass(frozen=True, slots=True)
class ReindexResult:
    """What one phase-5 pass did: lines indexed, whether changed, whether dry."""

    lines_indexed: int
    changed: bool
    dry_run: bool


def _strip_frontmatter(text: str) -> tuple[str, str]:
    """Return (frontmatter_block, body). No frontmatter → ("", text)."""
    if not text.startswith("---"):
        return "", text
    end = text.find("---", 3)
    if end == -1:
        return "", text
    return text[3:end], text[end + 3 :]


def _first_substantive_line(body: str) -> str:
    """First non-empty, non-heading, non-metadata body line (whitespace-collapsed).

    Metadata-ish ``key:`` lines (:data:`_METADATA_LINE_PREFIXES`) are skipped so a
    node-typed memory whose body leads with ``node_type: memory`` yields the real
    lesson that follows, not the type marker (#2746 nit-4). A genuine lesson never
    leads with one of those reserved metadata keys.
    """
    for raw in body.splitlines():
        line = raw.strip().lstrip("-*").strip()
        if not line or _HEADING_RE.match(raw.strip()):
            continue
        if line.lower().startswith(_METADATA_LINE_PREFIXES):
            continue
        return " ".join(line.split())
    return ""


def _first_binding_line(body: str) -> str:
    """First BINDING / Non-Negotiable body line (headings allowed), else ``""``.

    The last-resort signature when a memory carries no frontmatter summary and no
    substantive prose — a body of headings where one declares a BINDING rule still
    has a recoverable lesson.
    """
    for raw in body.splitlines():
        line = raw.strip().lstrip("#-*").strip()
        if line and any(marker in line.lower() for marker in _BINDING_MARKERS):
            return " ".join(line.split())
    return ""


def signature_text(text: str) -> str:
    """The memory's UNCLIPPED signature — the canonical lesson line (#2746 nit-4).

    The single frontmatter-aware extractor shared by the hot index
    (:func:`_summary_for`), the cold ``MEMORY_ARCHIVE.md`` index, and the
    retention probe (both via :func:`gates._signature_line`). Resolution order:
    the frontmatter ``description:``/``summary:`` value, else the first
    substantive body prose line (metadata ``key:`` lines skipped), else the first
    BINDING line, else ``""``. NEVER clipped — the verbatim line is what retention
    needs to stay findable, and the returned text is always a (whitespace-collapsed)
    substring of *text* so ``snapshot.contains(signature)`` stays True.
    """
    front, body = _strip_frontmatter(text)
    match = _FRONTMATTER_SUMMARY_RE.search(front)
    if match:
        return " ".join(match.group(1).split())
    prose = _first_substantive_line(body)
    if prose:
        return prose
    return _first_binding_line(body)


def _summary_for(text: str) -> str:
    summary = signature_text(text)
    if len(summary) > _SUMMARY_MAX_CHARS:
        summary = summary[: _SUMMARY_MAX_CHARS - 1].rstrip() + "…"
    return summary


def _index_line(md: Path, summary: str) -> str:
    if not summary:
        return f"- {md.name}"
    line = f"- {md.name} — {summary}"
    if len(line) <= _LINE_MAX_CHARS:
        return line
    # Whole-line cap: keep the pointer filename intact, clip the summary so the
    # line fits the per-line budget regardless of how long the filename is.
    keep = _LINE_MAX_CHARS - len(f"- {md.name} — ") - 1
    if keep <= 0:
        return f"- {md.name}"
    return f"- {md.name} — {summary[:keep].rstrip()}…"


def index_line_for(name: str, text: str) -> str:
    """The single ``MEMORY.md`` index line for one memory — the pure per-file renderer.

    Exposed so the decay phase can PROJECT the post-archival index byte-for-byte the
    way the re-index will render it (#2723), keeping the budget-tier stop condition
    exact w.r.t. the gate-(d) line / byte budget.
    """
    return _index_line(Path(name), _summary_for(text))


def render_index_lines(lines: Iterable[str]) -> str:
    """Wrap already-rendered per-memory index *lines* with the standard preamble.

    The pure tail of :func:`render_index`, exposed so the decay phase can render the
    projected (post-archival) index exactly as it will be written.
    """
    body = "\n".join(lines)
    return f"{_HEADER}{body}\n" if body else _HEADER


def render_index(memory_dir: Path) -> str:
    """Render the full ``MEMORY.md`` text for the current memory set (deterministic).

    Lines are deduped by filename and stably ordered (filename sort), so the
    output is a pure function of the memory set's content — a re-run with no
    changes renders the identical string. Both the hot ``MEMORY.md`` and the cold
    ``MEMORY_ARCHIVE.md`` are excluded so neither index re-bloats the hot index.
    """
    seen: set[str] = set()
    lines: list[str] = []
    for md in sorted(memory_dir.glob("*.md")):
        if md.name in {_INDEX_NAME, _ARCHIVE_INDEX_NAME} or md.name in seen:
            continue
        seen.add(md.name)
        try:
            text = md.read_text(encoding="utf-8")
        except OSError:
            continue
        lines.append(index_line_for(md.name, text))
    return render_index_lines(lines)


def reindex_memory(memory_dir: Path, *, dry_run: bool = False) -> ReindexResult:
    """Regenerate ``MEMORY.md`` from the current memory set under *memory_dir*.

    Idempotent: the rendered index is a pure function of the set, so a re-run on
    an unchanged set writes a byte-identical file (``changed=False``). A missing
    dir is a clean no-op. Under *dry_run* the index is rendered (and ``changed``
    computed against the on-disk file) but nothing is written.
    """
    if not memory_dir.is_dir():
        return ReindexResult(lines_indexed=0, changed=False, dry_run=dry_run)
    rendered = render_index(memory_dir)
    index_path = memory_dir / _INDEX_NAME
    current = index_path.read_text(encoding="utf-8") if index_path.is_file() else ""
    changed = rendered != current
    if changed and not dry_run:
        index_path.write_text(rendered, encoding="utf-8")
    return ReindexResult(lines_indexed=_count_lines(rendered), changed=changed, dry_run=dry_run)


def _count_lines(rendered: str) -> int:
    return sum(1 for line in rendered.splitlines() if line.startswith("- "))


__all__ = [
    "ReindexResult",
    "index_line_for",
    "reindex_memory",
    "render_index",
    "render_index_lines",
    "signature_text",
]
