"""Park a hook ``prek install -f`` is about to destroy, BEFORE it runs.

Round 1 of this fix destroyed the operator's bytes and said nothing. Round 2 carried the
loss out on a return value, and that channel was itself lossy: any raise discarded it and
the second consumer never read it. A third carried channel would repeat the class, so
nothing is carried here at all.

Durability precedes destruction. :meth:`Quarantine.capture` reads the bytes and
:meth:`Quarantine.park` writes them into ``<git-common-dir>/t3-hook-quarantine/``; either
raising :class:`HookCaptureError` REFUSES the destructive call rather than proceeding
without a copy. After the park there is no exception, no early return and no killed
process that can lose them, because no frame is holding them.

The report is read back from the world by :func:`pending`, never handed along: the
installer line, the doctor and provisioning all list the same directory, so the repair and
the verification cannot disagree.
"""

import logging
import stat
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path

logger = logging.getLogger(__name__)

QUARANTINE_DIRNAME = "t3-hook-quarantine"

#: The byte form of ``prek_hook._PREK_MARKER``; pinned equal to it by a conformance test.
#: Classifying on BYTES is what lets an undecodable prek-marked hook be recognised as
#: prek's own rather than mistaken for the operator's.
_PREK_MARKER = b"File generated by prek"


class HookCaptureError(RuntimeError):
    """The operator's hook could not be read or parked, so nothing destructive may run."""


def quarantine_dir(git_common_dir: Path) -> Path:
    return git_common_dir / QUARANTINE_DIRNAME


def pending(git_common_dir: Path) -> tuple[Path, ...] | None:
    """Every parked hook, ``()`` for none — and ``None`` when the directory could not be READ.

    Three-valued on purpose: a read failure degrading to ``()`` is the silent-empty this
    whole mechanism exists to forbid, since every consumer reads ``()`` as "nothing lost".
    """
    try:
        return tuple(sorted(entry for entry in quarantine_dir(git_common_dir).iterdir() if entry.is_file()))
    except FileNotFoundError:
        return ()
    except OSError:
        return None


def parked_finding(parked: tuple[Path, ...] | None, git_common_dir: Path | None) -> str | None:
    """The ONE sentence describing what the quarantine holds — ``None`` when it holds nothing.

    Whether to speak and how to say it are decided together, so the installer line, the doctor
    and provisioning cannot disagree about either. The restore dir is always ``<common>/hooks``,
    which is where a parked hook came from even when ``core.hooksPath`` points elsewhere — so a
    listing needs the clone, while an unread quarantine names itself with or without one.
    """
    if parked is None:
        where = QUARANTINE_DIRNAME if git_common_dir is None else quarantine_dir(git_common_dir)
        return (
            f"The parked-hook directory {where} could not be read — a pre-existing hook may be "
            f"parked there and NOT gating this clone."
        )
    if not parked or git_common_dir is None:
        return None
    return (
        f"The pre-existing {', '.join(str(path) for path in parked)} is parked and is NOT gating this "
        f"clone — move it back into {git_common_dir / 'hooks'} or delete it to clear this."
    )


def _is_foreign(path: Path) -> bool:
    return path.is_file() and _PREK_MARKER not in path.read_bytes()


def _still_holds(path: Path, blob: bytes) -> bool:
    """True only when *path* reads back as exactly *blob* — unlinked or unreadable is not."""
    try:
        return path.read_bytes() == blob
    except OSError:
        return False


def _gating_slot(live: Path, legacy: Path) -> Path | None:
    """Which of the two slots is the gate git or a prek shim actually runs, if either.

    A foreign ``<name>`` is run by git itself, leaving any ``.legacy`` beside it dark. A prek
    shim at ``<name>`` discovers and runs ``<name>.legacy`` at hook time instead, so THAT file
    is the gate. With ``<name>`` absent, the ``.legacy`` is an orphan nothing dispatches: the
    filesystem cannot say whether a shim was removed or the operator broke the chain
    deliberately, and resurrecting it would make dormant code run on every push.
    """
    if _is_foreign(live):
        return live
    return legacy if _is_foreign(legacy) and live.is_file() else None


@dataclass(frozen=True, slots=True)
class _Captured:
    """One foreign hook's bytes, where they are parked, and the slot they may return to."""

    source: Path
    parked: Path
    destination: Path | None
    blob: bytes
    mode: int


class Quarantine:
    """The operator's hooks, made durable before ``prek install -f`` and put back after it."""

    def __init__(self, hooks_dir: Path, git_common_dir: Path) -> None:
        self._hooks_dir = hooks_dir
        self._dir = quarantine_dir(git_common_dir)
        self._captured: list[_Captured] = []

    def capture(self, names: Iterable[str]) -> None:
        for name in sorted(names):
            self._captured.extend(self._capture_one(name))

    def _capture_one(self, name: str) -> list[_Captured]:
        live, legacy = self._hooks_dir / name, self._hooks_dir / f"{name}.legacy"
        try:
            gate = _gating_slot(live, legacy)
            return [
                _Captured(
                    source=source,
                    parked=self._dir / source.name,
                    destination=legacy if source == gate else None,
                    blob=source.read_bytes(),
                    mode=stat.S_IMODE(source.stat().st_mode),
                )
                for source in (live, legacy)
                if _is_foreign(source)
            ]
        except OSError as exc:
            msg = f"Could not read the pre-existing hook {name} in {self._hooks_dir}: {exc}"
            raise HookCaptureError(msg) from exc

    def park(self) -> None:
        if not self._captured:
            return
        try:
            self._dir.mkdir(parents=True, exist_ok=True)
        except OSError as exc:
            msg = f"Could not create the hook quarantine {self._dir}: {exc}"
            raise HookCaptureError(msg) from exc
        for item in self._captured:
            self._park_one(item)

    def _park_one(self, item: _Captured) -> None:
        try:
            existing: bytes | None = item.parked.read_bytes()
        except FileNotFoundError:
            existing = None
        except OSError as exc:
            msg = f"Could not read the already-parked hook {item.parked}: {exc}"
            raise HookCaptureError(msg) from exc
        if existing == item.blob:
            return
        if existing is not None:
            msg = (
                f"{item.parked} already holds a DIFFERENT pre-existing hook from an earlier run. "
                f"Move it back into {self._hooks_dir} or delete it, then re-run — refusing to overwrite it."
            )
            raise HookCaptureError(msg)
        try:
            item.parked.write_bytes(item.blob)
            item.parked.chmod(item.mode)
        except OSError as exc:
            msg = f"Could not park {item.source} at {item.parked}: {exc}"
            raise HookCaptureError(msg) from exc

    def reinstate(self) -> None:
        """Put each destroyed gate back in the slot prek dispatches; leave everything else parked."""
        for item in self._captured:
            try:
                self._reinstate_one(item)
            except OSError:
                logger.exception("Left %s parked at %s — it is NOT gating this clone.", item.source, item.parked)

    @staticmethod
    def _reinstate_one(item: _Captured) -> None:
        if _still_holds(item.source, item.blob):
            item.parked.unlink(missing_ok=True)
            return
        if item.destination is None:
            logger.warning("Parked the pre-existing %s at %s without activating it.", item.source.name, item.parked)
            return
        item.destination.write_bytes(item.blob)
        item.destination.chmod(item.mode)
        item.parked.unlink(missing_ok=True)
        logger.warning("Restored the pre-existing %s the re-install destroyed: %s", item.source.name, item.destination)


__all__ = [
    "QUARANTINE_DIRNAME",
    "HookCaptureError",
    "Quarantine",
    "parked_finding",
    "pending",
    "quarantine_dir",
]
