import logging
import re
from pathlib import Path

from teatree.core.step_runner import StepResult, run_step

logger = logging.getLogger(__name__)

_PREK_MARKER = "File generated by prek"
_HOOK_NAMES = ("pre-commit", "pre-push", "commit-msg")
_PREK_ASSIGNMENT_RE = re.compile(r'^PREK="([^"]*)"$', re.MULTILINE)
_PATH_RESOLVED_PREK = 'PREK="prek"'


def _shared_hooks_dir(wt_path: str) -> Path | None:
    result = run_step(
        "git-hooks-path",
        ["git", "rev-parse", "--git-path", "hooks"],
        cwd=wt_path,
        check=False,
    )
    if not result.success or not result.stdout.strip():
        return None
    hooks_dir = Path(result.stdout.strip())
    if not hooks_dir.is_absolute():
        hooks_dir = (Path(wt_path) / hooks_dir).resolve()
    return hooks_dir


def _is_prek_hook(path: Path) -> bool:
    return path.is_file() and _PREK_MARKER in _read(path)


def _read(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except OSError:
        return ""


def _baked_prek_path(body: str) -> str | None:
    match = _PREK_ASSIGNMENT_RE.search(body)
    return match.group(1) if match else None


def install(wt_path: str) -> StepResult:
    result = run_step("prek-install", ["prek", "install", "-f"], cwd=wt_path, check=False)
    if result.success:
        harden_hooks(wt_path)
    return result


def harden_hooks(wt_path: str) -> None:
    """Rewrite prek-generated hooks so ``prek`` resolves via PATH, not a baked path.

    ``prek install`` bakes the install-time absolute path of the binary into
    ``PREK="<abs>"``. That path belongs to whichever worktree provisioned the
    SHARED ``.git/hooks`` last; once that worktree is torn down the absolute
    path is stale and ``exec "$PREK"`` hangs or fails for every other worktree
    (souliane/teatree#1462). Resolving via PATH removes the worktree coupling.
    """
    hooks_dir = _shared_hooks_dir(wt_path)
    if hooks_dir is None:
        return
    for name in _HOOK_NAMES:
        hook = hooks_dir / name
        if not _is_prek_hook(hook):
            continue
        body = _read(hook)
        hardened = _PREK_ASSIGNMENT_RE.sub(_PATH_RESOLVED_PREK, body)
        if hardened != body:
            hook.write_text(hardened, encoding="utf-8")
            logger.info("Hardened prek hook to resolve via PATH: %s", hook)


def remove_stale_hooks(wt_path: str, removed_dir: str) -> list[str]:
    """Remove SHARED prek hooks whose baked ``PREK=`` path lives in ``removed_dir``.

    The pre-push/pre-commit hooks live in the SHARED git common dir, so a hook
    baked with a path inside a torn-down worktree poisons every sibling
    worktree (souliane/teatree#1462). Teardown removes only the hooks coupled
    to the worktree being removed; PATH-resolved hooks are left untouched.
    """
    hooks_dir = _shared_hooks_dir(wt_path)
    if hooks_dir is None:
        return []
    removed = Path(removed_dir).resolve()
    cleaned: list[str] = []
    for name in _HOOK_NAMES:
        hook = hooks_dir / name
        if not _is_prek_hook(hook):
            continue
        baked = _baked_prek_path(_read(hook))
        if baked and _is_within(Path(baked), removed):
            hook.unlink()
            cleaned.append(str(hook))
            logger.info("Removed stale prek hook pointing into %s: %s", removed, hook)
    return cleaned


def _is_within(candidate: Path, parent: Path) -> bool:
    try:
        candidate.resolve().relative_to(parent)
    except ValueError:
        return False
    return True
