import logging
import re
import stat
from dataclasses import dataclass
from pathlib import Path

import yaml

from teatree.core import hook_quarantine
from teatree.core.provision.provision_report import StepResult
from teatree.core.provision.step_runner import run_step

logger = logging.getLogger(__name__)

_PREK_MARKER = "File generated by prek"
_PREK_ASSIGNMENT_RE = re.compile(r'^PREK="([^"]*)"$', re.MULTILINE)
_FOREIGN_CONFIG_FLAG = "--cd="
_PREK_CONFIG_NAME = ".pre-commit-config.yaml"
_INSTALL_STEP = "prek-install"
#: Every hook name git RUNS — ``githooks(5)``, git 2.50.1, derived with
#: ``man githooks | col -bx | grep -E '^   [a-z][a-z0-9-]*$'``.
_GIT_HOOK_NAMES = frozenset(
    {
        "applypatch-msg",
        "pre-applypatch",
        "post-applypatch",
        "pre-commit",
        "pre-merge-commit",
        "prepare-commit-msg",
        "commit-msg",
        "post-commit",
        "pre-rebase",
        "post-checkout",
        "post-merge",
        "pre-push",
        "pre-receive",
        "update",
        "proc-receive",
        "post-receive",
        "post-update",
        "reference-transaction",
        "push-to-checkout",
        "pre-auto-gc",
        "post-rewrite",
        "sendemail-validate",
        "fsmonitor-watchman",
        "p4-changelist",
        "p4-prepare-changelist",
        "p4-post-changelist",
        "p4-pre-submit",
        "post-index-change",
    }
)
#: What ``harden_hooks`` writes in place of prek's baked ``PREK="<abs>"``.
#:
#: A stat is not a resolution: the baked path belongs to whichever checkout
#: installed these SHARED hooks last, and read from another platform it passes
#: ``[ -x ]`` and dies ``Exec format error`` — refusing every push. So candidates
#: are PROBED, and the repository the hook runs FOR comes first: git chdirs to the
#: working-tree root before running a hook, which is what makes ``$PWD`` it.
#: The bare ``PREK=`` also keeps ``_PREK_ASSIGNMENT_RE`` from matching what we just
#: wrote, which is what makes a second hardening a no-op.
#:
#: Each candidate clears THREE filters, none of them redundant:
#: ``/*`` — ``command -v`` answers a shell function or builtin with its bare NAME, and
#: ``exec`` re-resolves that through PATH, running a binary this loop never probed.
#: ``[ -x ]`` — on dash (the container's ``/bin/sh``) ``command -v`` exits 0 for a
#: present-but-NON-EXECUTABLE file, where bash-as-sh exits 1; on the platform this bug
#: bites, the exit status alone therefore filters nothing.
#: ``--version`` — the only filter that catches executable-but-not-runnable-HERE, which
#: is the bind-mounted host venv that passes ``[ -x ]`` and dies ``Exec format error``.
_PROBED_PREK_RESOLUTION = """PREK=
for _t3_candidate in "$PWD/.venv/bin/prek" prek; do
    _t3_found="$(command -v "$_t3_candidate" 2>/dev/null)" || continue
    case "$_t3_found" in /*) ;; *) continue ;; esac
    [ -x "$_t3_found" ] || continue
    "$_t3_found" --version >/dev/null 2>&1 || continue
    PREK="$_t3_found"
    break
done
if [ -z "$PREK" ]; then
    echo "prek: nothing runnable at $PWD/.venv/bin/prek or on PATH - cannot gate this operation" >&2
    exit 1
fi"""


def _shared_hooks_dir(wt_path: str) -> Path | None:
    result = run_step(
        "git-hooks-path",
        ["git", "rev-parse", "--git-path", "hooks"],
        cwd=wt_path,
    )
    if not result.success or not result.stdout.strip():
        return None
    hooks_dir = Path(result.stdout.strip())
    if not hooks_dir.is_absolute():
        hooks_dir = (Path(wt_path) / hooks_dir).resolve()
    return hooks_dir


def _local_hooks_path(wt_path: str) -> str | None:
    """Return the LOCAL-scope ``core.hooksPath`` value, or ``None`` if unset.

    Reads ``--local`` only: a redundant value baked into the repo's own config
    (the #2706 footgun) is what blocks ``prek install``; a global/system
    ``core.hooksPath`` is the user's machine-wide intent and is never touched.
    """
    result = run_step(
        "git-hookspath-get",
        ["git", "config", "--local", "--get", "core.hooksPath"],
        cwd=wt_path,
    )
    value = result.stdout.strip()
    return value or None


def _git_common_dir(wt_path: str) -> Path | None:
    """The clone's shared git dir — the anchor for both the hooks dir and the quarantine."""
    result = run_step(
        "git-common-dir",
        ["git", "rev-parse", "--git-common-dir"],
        cwd=wt_path,
    )
    if not result.success or not result.stdout.strip():
        return None
    common = Path(result.stdout.strip())
    if not common.is_absolute():
        common = Path(wt_path) / common
    return common.resolve()


def _default_hooks_dir(wt_path: str) -> Path | None:
    """The repo's DEFAULT hooks dir (``<git-common-dir>/hooks``).

    This is where git looks for hooks when ``core.hooksPath`` is unset — and
    where ``prek install`` writes. A ``core.hooksPath`` resolving here is
    redundant; one resolving elsewhere is a genuine custom override.
    """
    common = _git_common_dir(wt_path)
    return None if common is None else (common / "hooks").resolve()


def _clear_redundant_hooks_path(wt_path: str) -> bool:
    """Unset a LOCAL ``core.hooksPath`` that merely re-points at the default.

    ``prek install`` refuses ("Cowardly refusing to install hooks with
    ``core.hooksPath`` set") whenever the key is present, even when its value
    equals git's own default hooks dir — so a redundant value left by an IDE
    or a stale setup silently disables every commit/push hook (#2706). When
    the local value resolves to the default hooks dir it carries no intent, so
    we unset it (local scope only) and let ``prek install`` proceed. A value
    pointing ELSEWHERE is a real custom override and is left untouched.

    Returns ``True`` when a redundant value was unset.
    """
    configured = _local_hooks_path(wt_path)
    if configured is None:
        return False
    default = _default_hooks_dir(wt_path)
    if default is None:
        return False
    # git resolves a relative ``core.hooksPath`` against the REPOSITORY, not the
    # calling process's cwd — resolving it here made a provisioning run from
    # elsewhere compare two unrelated dirs and preserve a redundant value.
    configured_path = Path(configured)
    if not configured_path.is_absolute():
        configured_path = Path(wt_path) / configured_path
    if configured_path.resolve() != default:
        return False  # genuine custom hooksPath — preserve the user's intent
    result = run_step(
        "git-hookspath-unset",
        ["git", "config", "--local", "--unset", "core.hooksPath"],
        cwd=wt_path,
    )
    if result.success:
        logger.info("Unset redundant local core.hooksPath (== default hooks dir) so prek can install")
    return result.success


def is_root_bound_prek_hook(path: Path) -> bool:
    """True when *path* is a prek shim gating the repo on its OWN root config.

    An acceptor states the property positively and fails CLOSED, where a detector fails
    open. Asking instead whether a FAULT was detected answers "no fault" for a file
    nothing could read, so an undecodable hook reported itself installed and the repair
    keyed off that verdict never ran — the clone pushed ungated, permanently and quietly.
    """
    body = _read(path)
    return _PREK_MARKER in body and _FOREIGN_CONFIG_FLAG not in body


def _read(path: Path) -> str:
    """The file's UTF-8 text, or ``""`` for anything unreadable — undecodable included.

    ``UnicodeDecodeError`` is a ``ValueError``, not an ``OSError``, and enumerating the
    WHOLE hooks dir puts arbitrary non-UTF-8 files in scope — a ``.DS_Store``, a vim
    swapfile, a compiled or latin-1 legacy hook. Skipping beats ``errors="replace"``
    because callers WRITE back what they read: mojibake would let ``harden_hooks``
    rewrite a hook from its own corruption and ``DroppedHook`` restore a corrupted body.
    """
    try:
        return path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as exc:
        logger.warning("Skipping %s: not readable as UTF-8 text (%s)", path, exc)
        return ""


@dataclass(frozen=True, slots=True)
class _PrekHook:
    """The body is carried, not re-read: a second read can fail and hand a restore an empty hook."""

    path: Path
    body: str


def _prek_hooks(hooks_dir: Path) -> list[_PrekHook]:
    """Every prek-generated hook in *hooks_dir*, whatever its TYPE.

    Derived from what ``prek install`` actually wrote, because the hard-coded tuple this
    replaces drifted from the config that decides the set: ``default_install_hook_types``
    in the installing repo's ``.pre-commit-config.yaml``. This fork's root config declares
    ``pre-merge-commit`` and the tuple did not, so that one hook kept the baked absolute
    path every other type had repaired — and inside the container, where that path is
    absent or built for another platform, ``git merge`` was refused by the single hook the
    hardening never reached. A set that is not maintained beside the config cannot fall
    behind it; the prek marker is what keeps a foreign tool's hook out.

    Bounded to the names git RUNS, because this module rewrites and unlinks whatever it
    enumerates: a prek-marked ``pre-push.bak`` / ``.disabled`` / ``~`` is a developer's
    parked copy git never executes, and nothing recreates one that is destroyed here.
    """
    try:
        entries = sorted(hooks_dir.iterdir())
    except OSError:
        return []
    hooks: list[_PrekHook] = []
    for entry in entries:
        if entry.name not in _GIT_HOOK_NAMES or not entry.is_file():
            continue
        body = _read(entry)
        if _PREK_MARKER in body:
            hooks.append(_PrekHook(path=entry, body=body))
    return hooks


def _baked_prek_path(body: str) -> str | None:
    match = _PREK_ASSIGNMENT_RE.search(body)
    return match.group(1) if match else None


def _install_cwd(wt_path: str) -> str:
    """The worktree ROOT ``prek install`` must run from, never a subdirectory.

    ``prek`` resolves its config from the CWD and, when that CWD is a
    subdirectory of the repo, bakes ``--cd=<subdir>`` into the generated shim —
    so the repo's commit gate becomes that subdirectory's config. A repo that
    VENDORS another project carrying its own ``.pre-commit-config.yaml``
    (``<host>/vendor/<core>``) has its ENTIRE gate replaced the moment
    provisioning is pointed at the vendored path: every host hook stops running
    and the vendored project's development lane gates the host instead. Nothing
    reports the swap — commits just start failing on rules the host never
    adopted and passing none of the ones it did.
    """
    result = run_step("git-toplevel", ["git", "rev-parse", "--show-toplevel"], cwd=wt_path)
    if not result.success or not result.stdout.strip():
        return wt_path
    return result.stdout.strip()


@dataclass(frozen=True, slots=True)
class DroppedHook:
    """One prek shim removed ahead of a re-install, kept whole so it can be put back."""

    path: Path
    body: str
    mode: int

    def restore(self) -> None:
        self.path.write_text(self.body, encoding="utf-8")
        self.path.chmod(self.mode)
        logger.warning("Restored the prek hook removed for a failed re-install: %s", self.path)


def drop_foreign_config_hooks(wt_path: str) -> list[DroppedHook]:
    """Remove prek shims bound to a config other than the repo root's.

    ``prek install`` bakes ``--cd=<subdir>`` when it runs from below the repo
    root, and the shim then gates the repo on that subdirectory's config. Running
    the install from the root fixes every hook type the root config DECLARES,
    because each one is overwritten. A type it does not declare is never written
    again, so a shim installed once from a vendored subdir survives the repair
    indefinitely and keeps running the vendored project's lane. Removing it
    BEFORE the install is what lets the repair reach it: a declared type is then
    rewritten correctly, and an undeclared one is simply gone.

    Each removal is returned WHOLE (body + mode), not merely named, because these
    hooks live in the clone's SHARED hooks dir: the removal reaches every sibling
    worktree at once, and until the install that justifies it succeeds the deletion is
    not a repair but an outage. :func:`install` puts them back when it fails.

    All or nothing: a removal that fails part-way puts back what it already took and
    re-raises, because the record :func:`install` restores from is returned only on the
    way out — a raise mid-loop would otherwise lose it along with the hooks it names.
    """
    hooks_dir = _shared_hooks_dir(wt_path)
    if hooks_dir is None:
        return []
    dropped: list[DroppedHook] = []
    for hook in _prek_hooks(hooks_dir):
        if _FOREIGN_CONFIG_FLAG not in hook.body:
            continue
        try:
            dropped.append(DroppedHook(path=hook.path, body=hook.body, mode=stat.S_IMODE(hook.path.stat().st_mode)))
            hook.path.unlink()
        except OSError:
            _restore(dropped)
            raise
        logger.info("Removed prek hook bound to a non-root config: %s", hook.path)
    return dropped


def _installable_hook_types(install_cwd: str) -> tuple[str, ...]:
    """The hook types ``prek install`` will actually write — the only slots ``-f`` destroys.

    Measured on prek 0.4.11: with ``default_install_hook_types: [pre-commit, pre-push]`` a
    foreign ``post-checkout``, ``post-checkout.legacy`` and ``pre-rebase.legacy`` were left
    completely untouched. Quarantining all 28 names would therefore park files nothing was
    going to destroy, and a run that died mid-flight would leave a permanent WARN about a
    hook that is fine — which teaches the operator to ignore the warning that matters.

    Fails SAFE to the full set: over-capturing costs a no-op reinstate, under-capturing costs
    the operator's bytes.
    """
    try:
        config = yaml.safe_load((Path(install_cwd) / _PREK_CONFIG_NAME).read_text(encoding="utf-8"))
        declared = config.get("default_install_hook_types") or ["pre-commit"]
    except (OSError, UnicodeDecodeError, yaml.YAMLError, AttributeError):
        declared = None
    if not isinstance(declared, list):
        return tuple(sorted(_GIT_HOOK_NAMES))
    return tuple(sorted({name for name in declared if isinstance(name, str)} & _GIT_HOOK_NAMES))


def install(wt_path: str) -> StepResult:
    """Install the repo-root prek hooks, keeping the BYTES of every hook prek did not write.

    Bytes, not dispatch: :func:`drop_foreign_config_hooks` unlinks a foreign-config shim at a
    hook type the root config does not declare, ``-f`` never rewrites that type, and the
    operator's ``<name>.legacy`` beside it then survives on disk with nothing left to run it.
    Reporting that needs a channel carried out of the install — the class this design deletes.

    The drop below is only safe because the install that follows rewrites what it
    removed. When the install FAILS the removal has to be undone: the hooks are the
    clone's SHARED ones, so an unrepaired drop leaves EVERY sibling worktree of that
    clone with no pre-commit / pre-push / commit-msg hook at all, and nothing says so —
    commits and pushes simply stop being gated. A shim bound to the wrong config is a
    bad gate; no shim at all is no gate, which is strictly worse and far quieter.

    A hook prek did NOT write is parked in the quarantine BEFORE anything destructive runs,
    and a park that cannot happen REFUSES the install with the clone exactly as found — the
    operator keeps their own gate and teatree's is simply not installed yet. That ordering is
    what makes preservation independent of how this function exits: once the bytes are on
    disk, no raise, return or SIGKILL can lose them, because nothing is carrying them.

    That narrows the contract: a checkout whose shared git dir ``git rev-parse`` cannot
    resolve now FAILS here rather than installing, because the quarantine has nowhere to
    anchor — which also fails a transient git failure this cannot tell from "not a checkout".
    """
    _clear_redundant_hooks_path(wt_path)
    hooks_dir, common_dir = _shared_hooks_dir(wt_path), _git_common_dir(wt_path)
    if hooks_dir is None or common_dir is None:
        return StepResult(
            name=_INSTALL_STEP,
            success=False,
            error=(
                f"{wt_path}: `git rev-parse` did not answer for this checkout, so neither the hooks dir nor "
                f"the quarantine anchored beside it resolves — refusing `prek install -f` rather than running "
                f"it with nowhere to park a hook it would destroy."
            ),
        )
    install_cwd = _install_cwd(wt_path)
    quarantine = hook_quarantine.Quarantine(hooks_dir, common_dir)
    try:
        quarantine.capture(_installable_hook_types(install_cwd))
        quarantine.park()
    except hook_quarantine.HookCaptureError as exc:
        logger.warning("Refusing to run `prek install -f`: %s", exc)
        return StepResult(name=_INSTALL_STEP, success=False, error=str(exc))

    dropped = drop_foreign_config_hooks(wt_path)
    # A RAISED install leaves the clone exactly as ungated as a failed one — the binary
    # missing, the cwd gone, the subprocess timing out — so both paths restore. The restore
    # is NOT in the ``finally``: on SUCCESS the drop is precisely what the install replaced,
    # and putting the old shims back would undo the repair. The reinstate IS, and it is keyed
    # on the parked bytes, so an exit that destroyed nothing simply clears the quarantine.
    try:
        try:
            result = run_step(_INSTALL_STEP, ["prek", "install", "-f"], cwd=install_cwd)
        except BaseException:
            _restore(dropped)
            raise
        if not result.success:
            _restore(dropped)
    finally:
        quarantine.reinstate()
    # Deliberately outside the try/finally: moving it in would swallow its exception. That is
    # safe now — the bytes are either back in their slot or still parked, and either way the
    # filesystem, not this frame, is the record.
    if result.success:
        harden_hooks(wt_path)
    return result


def _restore(dropped: list[DroppedHook]) -> None:
    """Put back every hook the failed install was supposed to have replaced.

    Restoring is itself best-effort — a hooks dir that has become unwritable cannot be
    repaired from here — but a failure to restore is LOUD, because it is the state in
    which the clone is left ungated.
    """
    for hook in dropped:
        try:
            hook.restore()
        except OSError:
            logger.exception(
                "Could NOT restore the prek hook %s after a failed install — every worktree of this "
                "clone is now missing that hook and its commit/push gate is dark until `t3` re-provisions.",
                hook.path,
            )


def harden_hooks(wt_path: str) -> list[Path]:
    """Rewrite prek-generated hooks so ``prek`` is PROBED per repository, not baked.

    ``prek install`` bakes the install-time absolute path of the binary into
    ``PREK="<abs>"``. That path belongs to whichever worktree provisioned the
    SHARED ``.git/hooks`` last, and it goes wrong two ways: torn down, the path is
    stale and ``exec "$PREK"`` hangs or fails for every sibling worktree
    (souliane/teatree#1462); still present but built for another platform, it
    passes ``[ -x ]`` and dies ``Exec format error`` inside the container. Probing
    per-repository candidates removes both couplings.

    Returns the hooks actually rewritten, so a caller can report the repair instead of
    reporting the "already installed" it would otherwise print over a silent fix.
    """
    hooks_dir = _shared_hooks_dir(wt_path)
    if hooks_dir is None:
        return []
    repaired: list[Path] = []
    for hook in _prek_hooks(hooks_dir):
        hardened = _PREK_ASSIGNMENT_RE.sub(lambda _: _PROBED_PREK_RESOLUTION, hook.body)
        if hardened != hook.body:
            hook.path.write_text(hardened, encoding="utf-8")
            repaired.append(hook.path)
            logger.info("Hardened prek hook to probe its own repository's prek: %s", hook.path)
    return repaired


def remove_stale_hooks(wt_path: str, removed_dir: str) -> list[str]:
    """Remove SHARED prek hooks whose baked ``PREK=`` path lives in ``removed_dir``.

    The pre-push/pre-commit hooks live in the SHARED git common dir, so a hook
    baked with a path inside a torn-down worktree poisons every sibling
    worktree (souliane/teatree#1462). Teardown removes only the hooks coupled
    to the worktree being removed; PATH-resolved hooks are left untouched.
    """
    hooks_dir = _shared_hooks_dir(wt_path)
    if hooks_dir is None:
        return []
    removed = Path(removed_dir).resolve()
    cleaned: list[str] = []
    for hook in _prek_hooks(hooks_dir):
        baked = _baked_prek_path(hook.body)
        if baked and _is_within(Path(baked), removed):
            hook.path.unlink()
            cleaned.append(str(hook.path))
            logger.info("Removed stale prek hook pointing into %s: %s", removed, hook.path)
    return cleaned


def _is_within(candidate: Path, parent: Path) -> bool:
    # A PATH-resolved hook bakes the relative ``PREK="prek"`` (#1462); that is a
    # PATH lookup, never a filesystem path inside ``parent``, so it is never
    # "within". Short-circuiting also avoids ``resolve()`` anchoring a relative
    # path against ``os.getcwd()`` — which raises FileNotFoundError once the
    # worktree the process sits in has vanished mid-teardown (#2692).
    if not candidate.is_absolute():
        return False
    try:
        candidate.resolve().relative_to(parent)
    except ValueError:
        return False
    return True
