"""``t3 doctor`` — smoke-test hooks, imports, and services (thin package facade).

The ``doctor`` Typer group, the :class:`DoctorService` / :class:`IntrospectionHelpers`
services, and the individual ``_check_*`` probes live in :mod:`teatree.cli.doctor.app`;
the larger check bodies and plugin-registration repair live in the ``checks`` and
``plugin_repair`` submodules. This ``__init__`` only re-exports the public surface so
``from teatree.cli.doctor import DoctorService`` (and siblings) is unchanged.
"""

from teatree.cli.doctor.app import (
    _CLAUDE_PLUGIN_ID,
    _REQUIRED_TOOLS,
    AGENT_SKILL_RUNTIMES,
    DoctorService,
    IntrospectionHelpers,
    PackageNotFoundError,
    _check_account_switch,
    _check_agent_session_pins,
    _check_connector_manifest,
    _check_dangling_editable_pth,
    _check_dream_staleness,
    _check_editable_sanity,
    _check_entrypoint_is_primary_clone,
    _check_legacy_overlay_alias,
    _check_mcp_connectivity,
    _check_single_db,
    _check_singletons,
    _check_skills,
    _check_slack_dm_ready,
    _check_slack_socket_mode,
    _check_stale_path_t3,
    _check_stale_uv_venv,
    _check_teatree_mcp_registration,
    _check_worker_running,
    _do_ensure_plugin_registered,
    _ensure_plugin_registered,
    _find_host_project_root,
    _find_teatree_pyproject_from_cwd,
    _patch_uv_source,
    _read_json_safe,
    _repair_enabled_plugins,
    _repair_installed_plugins,
    _repair_marketplace_json,
    _resolve_main_clone,
    _write_dev_sources_marker,
    agent_skill_dirs,
    check,
    check_statusline,
    doctor_app,
)

__all__ = [
    "AGENT_SKILL_RUNTIMES",
    "_CLAUDE_PLUGIN_ID",
    "_REQUIRED_TOOLS",
    "DoctorService",
    "IntrospectionHelpers",
    "PackageNotFoundError",
    "_check_account_switch",
    "_check_agent_session_pins",
    "_check_connector_manifest",
    "_check_dangling_editable_pth",
    "_check_dream_staleness",
    "_check_editable_sanity",
    "_check_entrypoint_is_primary_clone",
    "_check_legacy_overlay_alias",
    "_check_mcp_connectivity",
    "_check_single_db",
    "_check_singletons",
    "_check_skills",
    "_check_slack_dm_ready",
    "_check_slack_socket_mode",
    "_check_stale_path_t3",
    "_check_stale_uv_venv",
    "_check_teatree_mcp_registration",
    "_check_worker_running",
    "_do_ensure_plugin_registered",
    "_ensure_plugin_registered",
    "_find_host_project_root",
    "_find_teatree_pyproject_from_cwd",
    "_patch_uv_source",
    "_read_json_safe",
    "_repair_enabled_plugins",
    "_repair_installed_plugins",
    "_repair_marketplace_json",
    "_resolve_main_clone",
    "_write_dev_sources_marker",
    "agent_skill_dirs",
    "check",
    "check_statusline",
    "doctor_app",
]
