FROM mcr.microsoft.com/playwright/python:v1.58.0-noble AS base
RUN apt-get update -qq && \
    apt-get install -y -qq direnv jq && \
    rm -rf /var/lib/apt/lists/*
RUN curl -LsSf https://astral.sh/uv/install.sh | sh -s -- -q
ENV PATH="/root/.local/bin:$PATH"
WORKDIR /app
