r"""End-to-end golden corpus for the AI-signature forge-post-body gate (#11).

Sub-agents running raw ``gh``/``glab`` forge-post commands kept injecting an
AI signature into PR/MR bodies (the robot-emoji "Generated with Claude Code"
footer, a ``Co-Authored-By: Claude`` trailer), violating the BINDING "No AI
Signature on Posts Made on the User's Behalf" rule. A prompt-level directive is
not reliable (it leaked onto souliane/skills#38, #1840, #1845), so the gate
must catch it structurally regardless of the model obeying.

The block-ai-signature gate already existed, but its Bash body extraction was a
SECOND hand-rolled parser that recognised only ``gh pr`` / ``glab mr`` and a
QUOTED ``--body`` — it missed ``gh issue create/comment``, ``glab issue note``,
``glab mr note``, and the ``-b``/``-d``/heredoc body forms. This suite pins the
fix: the gate now reuses the SAME canonical command parser
(``teatree.hooks._command_parser``) as the #1213/#1415/#1530 sibling gates, so
it fires for the whole forge-post command CLASS.

These tests exercise the gate END-TO-END through the REAL matcher
(``scripts/ai_signature_scan.py``) — no mocked subprocess — by pointing
``_ai_sig_scan_argv`` at the real script with the current interpreter. That
proves the command-parse → body-extract → real-match → deny pipeline as a
whole, not just an isolated stub.

Two symmetric dimensions, as the gate-review rule requires. The must-DENY side:
every forge-post command shape carrying a banned trailer is BLOCKED, via
``--body`` and ``--body-file``, for both ``gh`` and ``glab``. The must-ALLOW
side (the over-block dimension): a clean body, a body whose PROSE legitimately
mentions Claude / AI / generated / co-author, and a body with a REAL human
``Co-authored-by:`` trailer for a teammate are all ALLOWED.

Plus anti-vacuity proofs (each side flips RED under the opposite mutation), a
wired-and-exercised proof (the handler is in the live ``PreToolUse`` chain and a
``gh pr create`` routes through it), and a meta-test pinning the closed command
set the gate covers.
"""

import json
import sys
from pathlib import Path
from typing import ClassVar

import pytest

import hooks.scripts.hook_router as router
from hooks.scripts.hook_router import _HANDLERS, _extract_ai_sig_payload, handle_block_ai_signature

_SCRIPT = Path(__file__).resolve().parents[1] / "scripts" / "ai_signature_scan.py"

# Banned trailers — the exact shapes that leaked. The robot emoji is U+1F916.
_EMOJI_FOOTER = "\U0001f916 Generated with [Claude Code](https://claude.com/claude-code)"
_COAUTHOR_CLAUDE = "Co-Authored-By: Claude <noreply@anthropic.com>"

# A clean body and three benign-mention bodies that MUST be allowed.
_CLEAN_BODY = "fix: real change\n\nA proper description of the change.\n\nRelates-to #836"
_PROSE_MENTIONS_BODY = (
    "feat: pairing notes\n\n"
    "Reviewed the design with Claude and an AI pair before writing this.\n"
    "The migration was generated by the schema tool, and I added a co-author note in the README.\n"
)
# A REAL human co-author for a teammate — legitimate, must NOT be blocked.
_HUMAN_COAUTHOR_BODY = "fix: x\n\nbody\n\nCo-authored-by: Dejerre Vanderlin <dejerre@example.test>"


@pytest.fixture
def real_matcher(monkeypatch):
    """Point the gate at the REAL ai-signature matcher with this interpreter.

    Replaces the ``t3 tool ai-sig-scan -`` argv (which needs the installed t3
    binary) with ``<python> scripts/ai_signature_scan.py -`` so the gate shells
    the genuine matcher. This exercises the full command-parse → body-extract →
    match → deny pipeline without mocking the scan.
    """
    monkeypatch.setattr(router, "_ai_sig_scan_argv", lambda: [sys.executable, str(_SCRIPT), "-"])


def _bash(command: str) -> dict:
    return {"tool_name": "Bash", "tool_input": {"command": command}}


# Every forge-post command shape the gate must cover, paired with a {body}
# placeholder for an inline body flag. Spans gh + glab, pr/mr + issue, and the
# create/edit/comment/update/note verbs the canonical parser recognises.
_INLINE_BODY_COMMANDS: dict[str, str] = {
    "gh pr create": "gh pr create --title t --body {body}",
    "gh pr edit": "gh pr edit 7 --body {body}",
    "gh pr comment": "gh pr comment 7 --body {body}",
    "gh issue create": "gh issue create --title t --body {body}",
    "gh issue comment": "gh issue comment 7 --body {body}",
    "gh pr create -b short": "gh pr create -b {body}",
    "glab mr create": "glab mr create --title t --description {body}",
    "glab mr update": "glab mr update 7 --description {body}",
    "glab mr note": "glab mr note 7 --message {body}",
    "glab issue note": "glab issue note 7 --message {body}",
}


def _quote(text: str) -> str:
    # Single-quote with literal newlines — the shell lexer the parser uses
    # decodes the body the same way bash would.
    return "'" + text + "'"


class TestMustDenyInlineBody:
    """Every forge-post shape with a banned trailer in an inline body is BLOCKED."""

    @pytest.mark.parametrize("template", _INLINE_BODY_COMMANDS.values(), ids=list(_INLINE_BODY_COMMANDS))
    @pytest.mark.parametrize("trailer", [_EMOJI_FOOTER, _COAUTHOR_CLAUDE], ids=["emoji-footer", "coauthor-claude"])
    def test_inline_body_with_trailer_is_blocked(self, real_matcher, capsys, template, trailer):
        body = _quote(f"real summary\n\nmore detail\n\n{trailer}")
        blocked = handle_block_ai_signature(_bash(template.format(body=body)))
        assert blocked is True, f"{template} carrying a banned trailer must be BLOCKED"
        out = json.loads(capsys.readouterr().out)
        assert out["permissionDecision"] == "deny"
        assert "AI-signature" in out["permissionDecisionReason"]


class TestMustDenyBodyFile:
    """A banned trailer in a ``--body-file`` / ``--description-file`` is BLOCKED."""

    _TRAILER_BODY = f"fix: x\n\nbody line\n\n{_COAUTHOR_CLAUDE}\n"

    def test_gh_pr_create_body_file_is_blocked(self, real_matcher, tmp_path, capsys):
        body = tmp_path / "pr_body.md"
        body.write_text(self._TRAILER_BODY, encoding="utf-8")
        blocked = handle_block_ai_signature(_bash(f"gh pr create --title t --body-file {body}"))
        assert blocked is True
        assert json.loads(capsys.readouterr().out)["permissionDecision"] == "deny"

    def test_gh_issue_create_body_file_is_blocked(self, real_matcher, tmp_path, capsys):
        body = tmp_path / "issue_body.md"
        body.write_text(f"open: thing\n\n{_EMOJI_FOOTER}\n", encoding="utf-8")
        blocked = handle_block_ai_signature(_bash(f"gh issue create --title t --body-file {body}"))
        assert blocked is True
        assert json.loads(capsys.readouterr().out)["permissionDecision"] == "deny"

    def test_glab_mr_description_file_is_blocked(self, real_matcher, tmp_path, capsys):
        desc = tmp_path / "mr.md"
        desc.write_text(self._TRAILER_BODY, encoding="utf-8")
        blocked = handle_block_ai_signature(_bash(f"glab mr create --title t --description-file {desc}"))
        assert blocked is True
        assert json.loads(capsys.readouterr().out)["permissionDecision"] == "deny"

    def test_git_commit_message_file_is_blocked(self, real_matcher, tmp_path, capsys):
        msg = tmp_path / "COMMIT_MSG"
        msg.write_text(self._TRAILER_BODY, encoding="utf-8")
        blocked = handle_block_ai_signature(_bash(f"git commit -F {msg}"))
        assert blocked is True
        assert json.loads(capsys.readouterr().out)["permissionDecision"] == "deny"


class TestMustAllowOverBlockDimension:
    """The symmetric over-block check — legitimate bodies must NOT be blocked."""

    @pytest.mark.parametrize(
        "body",
        [_CLEAN_BODY, _PROSE_MENTIONS_BODY, _HUMAN_COAUTHOR_BODY],
        ids=["clean-body", "prose-mentions-claude-ai-generated-coauthor", "real-human-coauthor"],
    )
    @pytest.mark.parametrize("template", _INLINE_BODY_COMMANDS.values(), ids=list(_INLINE_BODY_COMMANDS))
    def test_legit_body_is_allowed(self, real_matcher, capsys, template, body):
        allowed = handle_block_ai_signature(_bash(template.format(body=_quote(body))))
        assert allowed is False, f"{template} with a legitimate body must be ALLOWED (over-block guard)"
        # No deny JSON was written.
        assert capsys.readouterr().out.strip() == ""

    def test_human_coauthor_body_file_is_allowed(self, real_matcher, tmp_path, capsys):
        body = tmp_path / "pr_body.md"
        body.write_text(_HUMAN_COAUTHOR_BODY + "\n", encoding="utf-8")
        allowed = handle_block_ai_signature(_bash(f"gh pr create --title t --body-file {body}"))
        assert allowed is False
        assert capsys.readouterr().out.strip() == ""


class TestAntiVacuity:
    """Each side flips RED under the opposite mutation — the corpus is not vacuous.

    The matcher runs in a subprocess, so an in-process ``monkeypatch`` of
    ``scan_text`` would not reach it. These proofs therefore target the matcher
    decision directly (the real ``scan_text`` for the baseline, an explicit
    mutated detector for the counterfactual) on the SAME corpus bodies the gate
    extracts. The deny side flips ALLOW when detection is removed; the allow
    side flips BLOCK when the matcher over-broadens to a bare-word ``claude``
    substring — proving each corpus member depends on the real detection.
    """

    @staticmethod
    def _detection_removed(_text: str) -> list:
        """A no-op matcher — detection removed."""
        return []

    @staticmethod
    def _overbroad_bareword(text: str) -> list:
        """An over-broadened matcher that flags any line mentioning ``claude``."""
        return [(i, "bareword", line) for i, line in enumerate(text.splitlines(), 1) if "claude" in line.lower()]

    def test_real_matcher_blocks_every_deny_body(self):
        # Baseline: the REAL matcher finds a trailer in each must-DENY body.
        from scripts.ai_signature_scan import scan_text  # noqa: PLC0415

        for trailer in (_EMOJI_FOOTER, _COAUTHOR_CLAUDE):
            body = f"real summary\n\nmore detail\n\n{trailer}"
            assert scan_text(body), f"real matcher must flag the {trailer!r} trailer"

    def test_deny_body_goes_red_when_detection_removed(self):
        # Counterfactual: with detection removed, the must-DENY body no longer
        # flags — so the must-DENY tests depend on the detection, not luck.
        for trailer in (_EMOJI_FOOTER, _COAUTHOR_CLAUDE):
            body = f"real summary\n\nmore detail\n\n{trailer}"
            assert self._detection_removed(body) == []

    def test_real_matcher_allows_every_legit_body(self):
        # Baseline: the REAL matcher finds NOTHING in each must-ALLOW body —
        # including the prose body that mentions Claude / AI / generated /
        # co-author and the real human co-author trailer.
        from scripts.ai_signature_scan import scan_text  # noqa: PLC0415

        for body in (_CLEAN_BODY, _PROSE_MENTIONS_BODY, _HUMAN_COAUTHOR_BODY):
            assert scan_text(body) == [], f"real matcher must NOT flag the legitimate body: {body!r}"

    def test_allow_body_goes_red_when_matcher_overbroadens(self):
        # Counterfactual: a bare-word ``claude`` matcher wrongly flags the prose
        # body that merely MENTIONS Claude — so the must-ALLOW tests depend on
        # the position-anchored matcher, not a coincidence.
        assert self._overbroad_bareword(_PROSE_MENTIONS_BODY), (
            "the over-broadened bare-word matcher must (wrongly) flag the prose body — "
            "proving the must-ALLOW corpus depends on anchored matching"
        )


class TestWiredAndExercised:
    """The gate is wired into the live PreToolUse chain and a gh pr create routes through it."""

    def test_handler_registered_in_pretooluse_chain(self):
        assert handle_block_ai_signature in _HANDLERS["PreToolUse"], (
            "handle_block_ai_signature must be in the live PreToolUse handler chain — an unwired gate is a phantom gate"
        )

    def test_pretooluse_chain_routes_gh_pr_create_through_the_gate(self, real_matcher, capsys):
        # Dispatch a gh pr create with a banned trailer through the WHOLE
        # PreToolUse chain exactly as main() does, and assert it is denied by
        # this gate — proving the gate actually fires on a routed tool call, not
        # only when called in isolation.
        body = _quote(f"summary\n\n{_COAUTHOR_CLAUDE}")
        data = _bash(f"gh pr create --title t --body {body}")
        deny_emitted = False
        for handler in _HANDLERS["PreToolUse"]:
            try:
                if handler(data) is True:
                    deny_emitted = True
                    break
            except Exception:  # noqa: BLE001, S112 — mirror main()'s crash-proof skip
                continue
        assert deny_emitted is True
        out = json.loads(capsys.readouterr().out)
        assert out["permissionDecision"] == "deny"
        assert "AI-signature" in out["permissionDecisionReason"]


class TestClosedCommandSetMetaTest:
    """Pin the closed forge-post command set the gate covers (#11).

    The gate keys body extraction on ``is_publish_command`` (the shared
    canonical detector). This meta-test pins the EXACT command shapes the gate
    fires for, so adding a new forge-post entry point that the detector does NOT
    yet recognise surfaces as a visible RED gap here rather than a silent leak.
    Each command is asserted to extract a non-None body (i.e. the gate treats it
    as a forge-post surface); the negative cases pin the read/non-publish shapes
    the gate must NOT claim.
    """

    _COVERED: ClassVar[list[str]] = [
        "gh pr create --title t --body 'x'",
        "gh pr edit 7 --body 'x'",
        "gh pr comment 7 --body 'x'",
        "gh issue create --title t --body 'x'",
        "gh issue comment 7 --body 'x'",
        "glab mr create --title t --description 'x'",
        "glab mr update 7 --description 'x'",
        "glab mr note 7 --message 'x'",
        "glab issue create --title t --description 'x'",
        "glab issue note 7 --message 'x'",
        "git commit -m 'x'",
    ]
    # Shapes the gate must NOT treat as a forge-post body surface: pure reads
    # and non-forge commands (over-block guard at the detection layer).
    _NOT_COVERED: ClassVar[list[str]] = [
        "gh pr view 7",
        "gh issue list",
        "glab mr view 7",
        "git commit -C HEAD~1",
        "ls -la",
        "git push origin main",
    ]

    @pytest.mark.parametrize("command", _COVERED)
    def test_covered_command_is_a_body_surface(self, command):
        assert _extract_ai_sig_payload(_bash(command)) is not None, (
            f"{command!r} is a forge-post body surface the gate must scan"
        )

    @pytest.mark.parametrize("command", _NOT_COVERED)
    def test_uncovered_command_is_not_a_body_surface(self, command):
        assert _extract_ai_sig_payload(_bash(command)) is None, (
            f"{command!r} is a read / non-forge command the gate must NOT claim as a body surface"
        )
