# test-path: cross-cutting — drives deploy/t3 into forge_push against a shared prek hook; no src mirror.
"""`t3 push` through the container wrapper must run THIS venue's prek, not the host's.

A host `prek install` bakes its own absolute binary into the clone's SHARED hooks. From
the container that path is present on the bind mount, passes `[ -x ]`, and cannot run
there, so every push from a mounted host worktree was refused by its own pre-push gate.

The genuine `deploy/t3` dispatches; a docker stub plays the container by running the
dispatched command locally, where a `prek` stub stands in for the image's Linux prek.
"""

import os
import shutil
import stat
import subprocess
import sys
from pathlib import Path

import pytest
from _deploy_wrapper_paths import copy_wrapper

from tests._git_repo import make_git_repo, run_git

WRAPPER = Path(__file__).resolve().parents[1] / "deploy" / "t3"
SYSTEM_PATH = os.defpath.strip(os.pathsep)
MACHO_HEADER = b"\xcf\xfa\xed\xfe\x07\x00\x00\x01"


CONTAINER_DOCKER_STUB = """#!/usr/bin/env bash
for arg in "$@"; do
    [ "$arg" = ps ] && exit 0
done
prologue=""
while [ "$#" -gt 0 ] && [ "$1" != t3-in-container ]; do
    prologue="$1"
    shift
done
[ "$#" -gt 0 ] || exit 0
exec sh -c "$prologue" "$@"
"""

CONTAINER_PREK_STUB = """#!/usr/bin/env bash
[ "$1" = --version ] && exit 0
printf '%s\\n' "$*" >>"$PREK_CALLS"
"""

CONTAINER_T3_STUB = f"""#!/usr/bin/env bash
[ "$1" = push ] && shift
exec "{sys.executable}" -c 'import typer; from teatree.cli.push import push; typer.run(push)' "$@"
"""

MACOS_PREK_SHIM = """#!/bin/sh
# File generated by prek: https://github.com/j178/prek
# ID: 182c10f181da4464a3eec51b83331688

HERE="$(cd "$(dirname "$0")" && pwd)"
PREK="{baked}"

if [ ! -x "$PREK" ]; then
    PREK="prek"
fi

exec "$PREK" hook-impl --hook-dir "$HERE" --script-version 4 --hook-type=pre-push -- "$@"
"""


def _executable(path: Path, body: str | bytes) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    if isinstance(body, bytes):
        path.write_bytes(body)
    else:
        path.write_text(body, encoding="utf-8")
    path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return path


@pytest.fixture
def host_worktree(tmp_path: Path) -> Path:
    workspace = tmp_path / "home" / "workspace" / "t3-workspaces" / "ticket"
    origin = make_git_repo(workspace / "origin.git", bare=True)
    clone = make_git_repo(workspace / "clone")
    run_git(clone, "remote", "add", "origin", str(origin))
    run_git(clone, "checkout", "-q", "-b", "feature")
    (clone / "file.txt").write_text("work\n")
    run_git(clone, "add", "file.txt")
    run_git(clone, "commit", "-q", "-m", "work")
    host_prek = _executable(tmp_path / "opt" / "homebrew" / "bin" / "prek", MACHO_HEADER + bytes(64))
    _executable(clone / ".git" / "hooks" / "pre-push", MACOS_PREK_SHIM.format(baked=host_prek))
    return clone


def _push_through_the_wrapper(tmp_path: Path, repo: Path) -> subprocess.CompletedProcess[str]:
    stubs = tmp_path / "container-bin"
    _executable(stubs / "docker", CONTAINER_DOCKER_STUB)
    _executable(stubs / "prek", CONTAINER_PREK_STUB)
    _executable(stubs / "t3", CONTAINER_T3_STUB)
    entry = tmp_path / "teatree-deploy" / "deploy" / "t3"
    entry.parent.mkdir(parents=True)
    copy_wrapper(WRAPPER, entry)
    git_dir = Path(shutil.which("git") or "/usr/bin/git").parent
    env = {k: v for k, v in os.environ.items() if not k.startswith(("GITLAB_", "GITHUB_", "GH_", "T3_", "TEATREE_"))}
    env |= {
        "PATH": os.pathsep.join((str(stubs), str(git_dir), SYSTEM_PATH)),
        "TEATREE_HOST_HOME": str(tmp_path / "home"),
        "PREK_CALLS": str(tmp_path / "prek-calls.log"),
    }
    return subprocess.run(
        [shutil.which("bash", path=SYSTEM_PATH) or "bash", str(entry), "push", "--repo", str(repo)],
        capture_output=True,
        text=True,
        check=False,
        env=env,
        cwd=tmp_path,
        timeout=300,
    )


def test_a_stale_host_prek_shim_does_not_refuse_the_container_push(tmp_path: Path, host_worktree: Path) -> None:
    proc = _push_through_the_wrapper(tmp_path, host_worktree)

    assert proc.returncode == 0, proc.stdout + proc.stderr
    remote_tip = run_git(host_worktree, "ls-remote", "origin", "refs/heads/feature").split()[0]
    assert remote_tip == run_git(host_worktree, "rev-parse", "HEAD")
    assert "--hook-type=pre-push" in (tmp_path / "prek-calls.log").read_text(encoding="utf-8")


def test_the_repair_leaves_no_host_binary_baked_into_the_shared_hook(tmp_path: Path, host_worktree: Path) -> None:
    _push_through_the_wrapper(tmp_path, host_worktree)

    hook = (host_worktree / ".git" / "hooks" / "pre-push").read_text(encoding="utf-8")
    assert str(tmp_path / "opt") not in hook
    assert "--version" in hook
