"""Architectural anti-pattern catalog — the single source of truth.

``antipatterns.yaml`` is the structured source; :mod:`teatree.quality.catalog`
loads and validates it into frozen :class:`AntiPatternEntry` dataclasses. Three
review tiers consume the SAME catalog rather than re-encoding the rules:

1.  Design-time — ``skills/architecture-design`` points at the generated doc.
2.  Per-PR deterministic — ``scripts/hooks/check_antipatterns.py`` runs each
    ``grep_hint`` over the staged diff (manual stage; gate promotion deferred).
3.  Periodic holistic — ``ac-reviewing-codebase`` reads the same doc.

The generated prose lives at ``docs/generated/antipattern-catalog.md`` and is
regenerated by ``scripts/hooks/generate_antipattern_catalog.py``; the
``check_antipattern_catalog_sync.py`` hook keeps it in lockstep with the YAML.
"""

from teatree.quality.catalog import AntiPatternEntry, CatalogError, catalog_path, load_catalog
from teatree.quality.test_shape import (
    Baseline,
    DupConfig,
    DuplicateCluster,
    Mode,
    RatioMeasurement,
    RatioRegression,
    TestShapeConfig,
    TestShapeReport,
    build_report,
    collect_source_files,
    collect_test_files,
    detect_ratio_regression,
    find_duplicate_clusters,
    load_config,
    loosens_baseline,
    measure_ratio,
)

__all__ = [
    "AntiPatternEntry",
    "Baseline",
    "CatalogError",
    "DupConfig",
    "DuplicateCluster",
    "Mode",
    "RatioMeasurement",
    "RatioRegression",
    "TestShapeConfig",
    "TestShapeReport",
    "build_report",
    "catalog_path",
    "collect_source_files",
    "collect_test_files",
    "detect_ratio_regression",
    "find_duplicate_clusters",
    "load_catalog",
    "load_config",
    "loosens_baseline",
    "measure_ratio",
]
