"""Real-git integration tests for ``t3 setup``'s git-hook installation step.

Every test pins the checkout set explicitly (or patches discovery): a test that
let discovery run free would probe — and install into — the developer's own
clones.
"""

import logging
import os
import shutil
import subprocess
from collections.abc import Callable
from pathlib import Path
from types import SimpleNamespace
from unittest.mock import MagicMock, patch

import pytest

from teatree.cli.doctor import checks_bootstrap
from teatree.cli.setup import command as setup_command
from teatree.cli.setup import git_hooks_installer
from teatree.cli.setup.git_hooks_installer import GitHooksInstaller
from teatree.cli.setup.statusline_installer import StatuslineInstall
from teatree.config import UserSettings
from teatree.core import hook_quarantine, prek_hook
from teatree.core.gates.git_hooks_preflight import REQUIRED_HOOK_NAMES, probe_git_hooks
from teatree.core.provision.provision_report import StepResult
from teatree.utils.git_worktree_query import git_common_dir
from tests._git_repo import make_git_repo, run_git
from tests._unreadable_file import skip_if_root

_MINIMAL_PREK_CONFIG = """\
default_install_hook_types: [pre-commit, pre-push]
repos:
-   repo: local
    hooks:
    -   id: noop
        name: noop
        language: system
        entry: "true"
        pass_filenames: false
        always_run: true
"""

_PREK_BIN = shutil.which("prek") or "prek"

pytestmark = pytest.mark.skipif(shutil.which("prek") is None, reason="prek is not on PATH")


def make_prek_checkout(path: Path) -> Path:
    checkout = make_git_repo(path)
    (checkout / ".pre-commit-config.yaml").write_text(_MINIMAL_PREK_CONFIG, encoding="utf-8")
    return checkout


@pytest.fixture
def repo(tmp_path: Path) -> Path:
    return make_prek_checkout(tmp_path / "repo")


#: A prek-generated hook whose baked binary belongs to another checkout — present,
#: executable there, and unrunnable on this platform.
_FOREIGN_PREK = "/elsewhere/another-worktree/.venv/bin/prek"

_BAKED_FOREIGN_HOOK = f"""#!/bin/sh
# File generated by prek: https://github.com/j178/prek
# ID: feedface

HERE="$(cd "$(dirname "$0")" && pwd)"
PREK="{_FOREIGN_PREK}"

exec "$PREK" hook-impl --hook-dir "$HERE" --script-version 4 --hook-type=pre-push -- "$@"
"""


def _install(*checkouts: Path) -> list[str]:
    lines: list[str] = []
    GitHooksInstaller(checkouts[0], checkouts=list(checkouts)).install(echo=lines.append)
    return lines


class TestGitHooksInstaller:
    def test_fresh_checkout_ends_with_both_hooks_installed(self, repo: Path) -> None:
        assert probe_git_hooks(repo).missing == REQUIRED_HOOK_NAMES

        lines = _install(repo)

        assert probe_git_hooks(repo).ok
        for name in REQUIRED_HOOK_NAMES:
            assert (repo / ".git" / "hooks" / name).is_file()
        assert any(line.startswith("OK") and "installed git hooks" in line for line in lines)

    def test_an_unprotected_second_clone_is_installed_into_as_well(self, tmp_path: Path) -> None:
        """The container/host split: one clone protected, the other silently not."""
        container = make_prek_checkout(tmp_path / "container-clone")
        host = make_prek_checkout(tmp_path / "host-checkout")
        _install(container)
        assert probe_git_hooks(host).missing == REQUIRED_HOOK_NAMES

        _install(container, host)

        assert probe_git_hooks(host).ok
        assert probe_git_hooks(container).ok

    def test_rerun_is_a_no_op(self, repo: Path) -> None:
        _install(repo)
        hooks = {name: (repo / ".git" / "hooks" / name).read_bytes() for name in REQUIRED_HOOK_NAMES}

        lines = _install(repo)

        for name, body in hooks.items():
            assert (repo / ".git" / "hooks" / name).read_bytes() == body
        assert any("already installed" in line for line in lines)
        assert not any(line.startswith("WARN") for line in lines)

    def test_an_existing_hook_baked_with_another_checkouts_binary_is_hardened(self, repo: Path) -> None:
        # `probe.ok` answers "is the hook PRESENT?", and a hook baked with a
        # sibling worktree's macOS venv IS present — it just dies
        # `Exec format error` inside the Linux worker. Returning early on `ok` is
        # why no re-run ever reached it.
        _install(repo)
        hook = probe_git_hooks(repo).hooks_dir / "pre-push"
        hook.write_text(_BAKED_FOREIGN_HOOK, encoding="utf-8")

        lines = _install(repo)

        surviving = hook.read_text()
        assert _FOREIGN_PREK not in surviving, f"a foreign baked path survived a re-run:\n{surviving}"
        assert "hook-impl" in surviving, "the repair must not destroy the dispatch line"
        assert any("re-hardened git hooks (pre-push)" in line for line in lines), (
            f"a silent repair still reported as a no-op:\n{lines}"
        )
        assert not any("already installed" in line for line in lines)

    def test_a_shim_bound_to_a_nested_config_is_repaired(self, repo: Path) -> None:
        """The whole point of `drop_foreign_config_hooks`, reachable only if the probe reports a gap."""
        _install(repo)
        shim = repo / ".git" / "hooks" / "pre-commit"
        shim.write_text(
            shim.read_text(encoding="utf-8").replace("hook-impl", 'hook-impl --cd="vendor/core"'), encoding="utf-8"
        )

        _install(repo)

        assert "--cd=" not in shim.read_text(encoding="utf-8")
        assert probe_git_hooks(repo).ok

    def test_deliberate_hooks_path_is_left_untouched(self, repo: Path, tmp_path: Path) -> None:
        elsewhere = tmp_path / "operator-hooks"
        elsewhere.mkdir()
        run_git(repo, "config", "core.hooksPath", str(elsewhere))

        lines = _install(repo)

        assert list(elsewhere.iterdir()) == []
        assert not (repo / ".git" / "hooks" / "pre-push").is_file()
        assert run_git(repo, "config", "--get", "core.hooksPath") == str(elsewhere)
        assert any(str(elsewhere) in line for line in lines)

    def test_checkout_without_a_prek_config_is_skipped(self, tmp_path: Path) -> None:
        plain = make_git_repo(tmp_path / "no-config")

        lines = _install(plain)

        assert any("No prek-managed checkout found" in line for line in lines)
        assert probe_git_hooks(plain).missing == REQUIRED_HOOK_NAMES

    def test_non_repo_warns_and_continues(self, tmp_path: Path) -> None:
        (tmp_path / ".pre-commit-config.yaml").write_text(_MINIMAL_PREK_CONFIG, encoding="utf-8")

        lines = _install(tmp_path)

        assert any(line.startswith("WARN") and "not a git checkout" in line for line in lines)

    @pytest.mark.parametrize(
        "gitdir",
        ["/another/venue/repo/.git/worktrees/linked-checkout", "../owner/.git/worktrees/linked-checkout"],
    )
    def test_linked_checkout_unavailable_in_this_venue_is_not_called_broken(self, tmp_path: Path, gitdir: str) -> None:
        foreign = tmp_path / "linked-checkout"
        foreign.mkdir()
        pointer = f"gitdir: {gitdir}\n"
        (foreign / ".git").write_text(pointer)
        (foreign / ".pre-commit-config.yaml").write_text(_MINIMAL_PREK_CONFIG, encoding="utf-8")

        lines = _install(foreign)

        assert len(lines) == 1
        assert lines[0].startswith("INFO")
        assert "unavailable in this venue" in lines[0]
        assert "parked-hook" not in lines[0]
        assert (foreign / ".git").read_text() == pointer


_INVALID_START_BYTE = "invalid start byte"


class TestOneBadCheckoutDoesNotUngateTheRest:
    """The loop installs into EVERY checkout, so a per-checkout failure must not escape it.

    A hooks dir holds whatever the filesystem put there — a `.DS_Store`, a hook owned by
    another user, a read-only dir. One raise aborted the loop, leaving every checkout
    AFTER it ungated, and `prepare_claude_runtime` runs `t3 setup` under `set -e`, so
    container init died on the traceback.
    """

    def test_a_raising_checkout_warns_and_the_next_one_is_still_installed(self, tmp_path: Path) -> None:
        poisoned = make_prek_checkout(tmp_path / "poisoned")
        healthy = make_prek_checkout(tmp_path / "healthy")
        _install(poisoned)  # so the second run takes the `probe.ok` short-circuit
        real_harden = git_hooks_installer.prek_hook.harden_hooks

        def _raise_for_the_poisoned_one(wt_path: str) -> list[Path]:
            if Path(wt_path) == poisoned:
                undecodable = UnicodeDecodeError("utf-8", b"\xff", 0, 1, _INVALID_START_BYTE)
                raise undecodable
            return real_harden(wt_path)

        with patch.object(git_hooks_installer.prek_hook, "harden_hooks", _raise_for_the_poisoned_one):
            lines = _install(poisoned, healthy)

        assert probe_git_hooks(healthy).ok, "the checkout after the failing one was left ungated"
        assert any(line.startswith("WARN") and str(poisoned) in line for line in lines)

    def test_junk_in_the_hooks_dir_is_not_a_failure_at_all(self, repo: Path) -> None:
        """The concrete case: the widened read now skips the junk instead of raising."""
        _install(repo)
        hooks_dir = probe_git_hooks(repo).hooks_dir
        (hooks_dir / ".DS_Store").write_bytes(b"\x00\x00\x00\x01Bud1\xff\xfe")

        lines = _install(repo)

        assert not any(line.startswith("WARN") for line in lines), lines
        assert probe_git_hooks(repo).ok
        assert (hooks_dir / ".DS_Store").is_file()


#: A prek shim gating the repo on a subdirectory's config — present and executable, so
#: the probe reports it missing and `install` reaches the drop that removes it.
_FOREIGN_CONFIG_SHIM = """#!/bin/sh
# File generated by prek: https://github.com/j178/prek
# ID: cafebabe

exec prek hook-impl --cd="vendor/core" --hook-type={name} -- "$@"
"""

_FOREIGN_SHIM_TYPES = ("commit-msg", "pre-commit", "pre-merge-commit", "pre-push")


def _write_foreign_config_shims(repo: Path) -> Path:
    hooks_dir = repo / ".git" / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    for name in _FOREIGN_SHIM_TYPES:
        shim = hooks_dir / name
        shim.write_text(_FOREIGN_CONFIG_SHIM.format(name=name), encoding="utf-8")
        shim.chmod(0o755)
    return hooks_dir


def _unlink_failing_on_call(nth: int) -> Callable[..., None]:
    real = Path.unlink
    calls: list[Path] = []

    def _unlink(self: Path, *args: object, **kwargs: object) -> None:
        calls.append(self)
        if len(calls) == nth:
            raise PermissionError(13, "Permission denied", str(self))
        real(self, *args, **kwargs)

    return _unlink


def _restore_that_fails(self: object) -> None:
    raise OSError(30, "Read-only file system")


def _prek_install_failing() -> Callable[..., StepResult]:
    """Fail the `prek install` step alone; every git step the behaviour depends on still runs."""
    real = git_hooks_installer.prek_hook.run_step

    def _dispatch(name: str, *args: object, **kwargs: object) -> StepResult:
        if name == "prek-install":
            return StepResult(name=name, success=False, error="prek exploded")
        return real(name, *args, **kwargs)

    return _dispatch


class TestTheFailureLineSaysWhatTheCheckoutIs:
    """`skipping; setup continues` is a claim about intent; the operator needs one about state.

    The install reaches destructive steps before it can fail, so one raise covers both a
    clone left exactly as found and a clone left with no commit or push gate at all. The
    line printed the same reassuring sentence for both, at exit 0.
    """

    def test_the_operator_line_says_the_clone_is_ungated_when_the_drop_could_not_be_undone(self, repo: Path) -> None:
        _write_foreign_config_shims(repo)

        with (
            patch.object(Path, "unlink", _unlink_failing_on_call(2)),
            patch.object(git_hooks_installer.prek_hook.DroppedHook, "restore", _restore_that_fails),
        ):
            lines = _install(repo)

        assert probe_git_hooks(repo).missing, "the fixture no longer leaves the clone ungated"
        line = "\n".join(lines)
        assert "skipping" not in line
        assert any(one.startswith("ERROR") for one in lines), lines
        assert str(repo) in line
        for name in probe_git_hooks(repo).missing:
            assert name in line

    def test_a_failed_install_still_preserves_what_it_already_overwrote(self, repo: Path) -> None:
        """`prek install -f` writes type by type and stops at the first it cannot — measured, exit 2.

        Everything it overwrote before that point is already destroyed, so a preservation
        reached only on the success path is the one the operator needed and did not get.
        """
        _write_hook_bytes(repo, "pre-commit", _HAND_WRITTEN_PRE_COMMIT)
        (repo / ".git" / "hooks" / "pre-push").mkdir()

        lines = _install(repo)

        assert (repo / ".git" / "hooks" / "pre-commit.legacy").read_bytes() == _HAND_WRITTEN_PRE_COMMIT
        assert any(line.startswith("WARN") and "`prek install` failed" in line for line in lines), lines

    def test_a_failed_install_that_overwrote_nothing_writes_no_copy(self, repo: Path) -> None:
        """The control: an unconditional preservation leaves a duplicate behind every failed run."""
        _write_hook_bytes(repo, "pre-commit", _HAND_WRITTEN_PRE_COMMIT)

        with patch.object(git_hooks_installer.prek_hook, "run_step", side_effect=_prek_install_failing()):
            lines = _install(repo)

        assert not list((repo / ".git" / "hooks").glob("*.legacy"))
        assert any(line.startswith("WARN") and "`prek install` failed" in line for line in lines), lines

    def test_an_install_that_landed_before_the_repair_raised_says_so(self, repo: Path) -> None:
        """The third arm: a re-probe alone cannot separate "nothing happened" from "post-steps failed".

        `_ensure_installed` reaches `prek_hook.install` only on a gap, and a FAILED install
        returns rather than raises — so a raise with a gap BEFORE and none after means the
        install landed and a step after it did not.
        """
        assert probe_git_hooks(repo).missing == REQUIRED_HOOK_NAMES

        undecodable = UnicodeDecodeError("utf-8", b"\xff", 0, 1, _INVALID_START_BYTE)

        def _raise(wt_path: str) -> list[Path]:
            raise undecodable

        with patch.object(git_hooks_installer.prek_hook, "harden_hooks", _raise):
            lines = _install(repo)

        line = "\n".join(lines)
        assert "left as found" not in line, lines
        assert not any(one.startswith("ERROR") for one in lines), lines
        assert "post-install repair did not complete" in line, lines
        assert "t3 setup" in line, lines
        assert probe_git_hooks(repo).ok

    def test_a_raise_with_no_destruction_still_reports_left_as_found(self, repo: Path) -> None:
        """The control without which the test above passes under a line that ERRORs on everything."""
        _install(repo)

        undecodable = UnicodeDecodeError("utf-8", b"\xff", 0, 1, _INVALID_START_BYTE)

        def _raise(wt_path: str) -> list[Path]:
            raise undecodable

        with patch.object(git_hooks_installer.prek_hook, "harden_hooks", _raise):
            lines = _install(repo)

        line = "\n".join(lines)
        assert "left as found" in line, lines
        assert not any(one.startswith("ERROR") for one in lines), lines
        assert probe_git_hooks(repo).ok


#: A legacy hook nobody wrote as UTF-8 — the `.git/hooks` any long-lived clone may hold.
_LATIN1_HOOK = "#!/bin/sh\n# caf\xe9 legacy hook\nexit 0\n".encode("latin-1")

#: A gate an operator wrote by hand. prek did not write it, and nothing else will.
_HAND_WRITTEN_HOOK = b"#!/bin/sh\n# the operator's own pre-push gate\nexit 0\n"

#: A second hand-written gate, distinct from the one above so two preserved copies cannot be
#: mistaken for one another.
_HAND_WRITTEN_PRE_COMMIT = b"#!/bin/sh\n# the operator's own pre-commit gate\nexit 0\n"


def _write_hook_bytes(repo: Path, name: str, blob: bytes) -> Path:
    hook = repo / ".git" / "hooks" / name
    hook.parent.mkdir(parents=True, exist_ok=True)
    hook.write_bytes(blob)
    hook.chmod(0o755)
    return hook


class TestAnUnreadableHookIsNeverReportedInstalled:
    """`t3 setup` printed `already installed` over a checkout with no working push gate.

    An undecodable `pre-push` exhibits no detectable fault, so the probe counted it
    installed and the repair keyed off that verdict never ran. The leak gate and
    `dev/push-gate.sh` stayed dark for every worktree of the clone, permanently.
    """

    def test_an_undecodable_pre_push_is_not_reported_already_installed(self, repo: Path) -> None:
        _install(repo)
        hook = _write_hook_bytes(repo, "pre-push", _LATIN1_HOOK)

        lines = _install(repo)

        assert not any("already installed" in line for line in lines), lines
        assert any("installed git hooks" in line for line in lines), lines
        assert probe_git_hooks(repo).ok
        body = hook.read_text(encoding="utf-8")
        assert "File generated by prek" in body

    def test_a_hand_written_hook_is_parked_as_legacy_not_destroyed(self, repo: Path) -> None:
        """`prek install -f` destroys what prek did not write, and this probe now triggers it."""
        hook = _write_hook_bytes(repo, "pre-push", _HAND_WRITTEN_HOOK)

        _install(repo)

        legacy = repo / ".git" / "hooks" / "pre-push.legacy"
        assert legacy.is_file(), "the operator's own gate was destroyed by the reinstall"
        assert legacy.read_bytes() == _HAND_WRITTEN_HOOK
        assert os.access(legacy, os.X_OK)
        assert "File generated by prek" in hook.read_text(encoding="utf-8")
        assert probe_git_hooks(repo).ok

    def test_an_undecodable_hook_is_parked_too_never_simply_gone(self, repo: Path) -> None:
        """The bytes nothing could read are still the operator's, and prek `-f` unlinks them."""
        _write_hook_bytes(repo, "pre-push", _LATIN1_HOOK)

        _install(repo)

        legacy = repo / ".git" / "hooks" / "pre-push.legacy"
        assert legacy.is_file(), "an unreadable hook was deleted rather than parked"
        assert legacy.read_bytes() == _LATIN1_HOOK

    def test_a_shim_bound_to_a_nested_config_produces_no_legacy_copy(self, repo: Path) -> None:
        """A prek shim is prek's, so the repair that replaces it preserves nothing.

        The repair has to actually run, so one shim is bound to a nested config — that is what
        makes the probe report a gap and sends `_ensure_installed` into `prek_hook.install`.
        """
        _install(repo)
        shim = repo / ".git" / "hooks" / "pre-commit"
        shim.write_text(
            shim.read_text(encoding="utf-8").replace("hook-impl", 'hook-impl --cd="vendor/core"'), encoding="utf-8"
        )
        assert probe_git_hooks(repo).missing == ("pre-commit",)

        _install(repo)

        assert not list((repo / ".git" / "hooks").glob("*.legacy"))
        assert probe_git_hooks(repo).ok

    def test_only_the_hook_prek_actually_overwrote_is_preserved(self, repo: Path) -> None:
        """Preserving whatever was captured duplicates every hook of every uninstalled type.

        `commit-msg` is that control precisely because the config declares only `pre-commit`
        and `pre-push`, so `prek install -f` never writes it — measured on prek 0.4.11, which
        reaps `<name>.legacy` only for the types it installs.
        """
        assert "default_install_hook_types: [pre-commit, pre-push]" in _MINIMAL_PREK_CONFIG
        assert "commit-msg" not in _MINIMAL_PREK_CONFIG
        hooks = repo / ".git" / "hooks"
        commit_msg = _write_hook_bytes(repo, "commit-msg", _HAND_WRITTEN_PRE_COMMIT)
        _write_hook_bytes(repo, "pre-push", _HAND_WRITTEN_HOOK)
        assert prek_hook._installable_hook_types(str(repo)) == ("pre-commit", "pre-push")

        _install(repo)

        assert sorted(path.name for path in hooks.glob("*.legacy")) == ["pre-push.legacy"]
        assert commit_msg.read_bytes() == _HAND_WRITTEN_PRE_COMMIT
        assert probe_git_hooks(repo).ok

    def test_doctor_fails_on_an_undecodable_pre_push(self, repo: Path) -> None:
        _install(repo)
        assert self._doctor_verdict(repo) is True

        _write_hook_bytes(repo, "pre-push", _LATIN1_HOOK)

        assert self._doctor_verdict(repo) is False

    @staticmethod
    def _doctor_verdict(repo: Path) -> bool:
        with patch("teatree.core.gates.git_checkouts.discover_checkouts", return_value=[repo]):
            return checks_bootstrap._check_git_hooks_installed()


class TestSetupCommandInstallsHooks:
    """``t3 setup`` itself must leave every discovered checkout with its hooks."""

    def test_run_installs_into_every_discovered_checkout(self, tmp_path: Path, monkeypatch) -> None:
        installed_clone = make_prek_checkout(tmp_path / "container-clone")
        host = make_prek_checkout(tmp_path / "host-checkout")
        home = tmp_path / "home"
        home.mkdir(exist_ok=True)
        monkeypatch.setattr("pathlib.Path.home", classmethod(lambda cls: home))
        config = MagicMock()
        config.user = UserSettings()

        with (
            patch("teatree.cli.setup.git_hooks_installer.discover_checkouts", return_value=[installed_clone, host]),
            patch.object(setup_command, "find_main_clone", return_value=installed_clone),
            patch.object(setup_command, "validate_repo", return_value=installed_clone),
            patch.object(setup_command, "_repair_dep_drift"),
            patch.object(setup_command, "ToolInstaller"),
            patch.object(setup_command, "strip_apm_hooks", return_value=0),
            patch.object(setup_command, "install_statusline", return_value=StatuslineInstall.ALREADY_PRESENT),
            patch.object(setup_command, "retire_alias"),
            patch.object(setup_command, "agent_skill_dirs", return_value=[]),
            patch.object(setup_command, "ensure_self_db_migrated", return_value=False),
            patch.object(setup_command, "seed_default_loops"),
            patch.object(setup_command, "provision_declared_notion_routing"),
            patch.object(setup_command, "provision_all_overlay_dm_channels"),
            patch.object(setup_command, "ensure_django"),
            patch("teatree.config.load_config", return_value=config),
            patch("teatree.config.clone_root", return_value=tmp_path / "workspace"),
            patch("teatree.cli.recommended_authorizations.report_missing_authorizations"),
        ):
            setup_command.run(SimpleNamespace(invoked_subcommand=None), skip_plugin=True)

        assert probe_git_hooks(installed_clone).ok
        assert probe_git_hooks(host).ok


def _prek_migrate(repo: Path, hook_type: str) -> None:
    """Plain `prek install -t <type>` — the migration mode that parks the operator's gate live."""
    subprocess.run([_PREK_BIN, "install", "-t", hook_type], cwd=repo, check=True, capture_output=True)


class TestAPreExistingLegacyGateSurvivesTheRepair:
    """`<name>.legacy` is a live dispatch slot, and `prek install -f` unlinks it.

    Migration mode parks the operator's gate there and the shim it installs RUNS it, so a
    capture that takes only `<name>` leaves the still-firing gate to be deleted by the very
    repair that exists to leave the checkout no weaker than it was found.
    """

    def test_the_migrated_gate_and_a_hand_written_hook_both_survive(self, repo: Path) -> None:
        _write_hook_bytes(repo, "pre-push", _HAND_WRITTEN_HOOK)
        _prek_migrate(repo, "pre-push")
        legacy = repo / ".git" / "hooks" / "pre-push.legacy"
        assert legacy.read_bytes() == _HAND_WRITTEN_HOOK, "the fixture never reached prek's migration mode"
        _write_hook_bytes(repo, "pre-commit", _HAND_WRITTEN_PRE_COMMIT)
        assert probe_git_hooks(repo).missing == ("pre-commit",)

        _install(repo)

        assert legacy.read_bytes() == _HAND_WRITTEN_HOOK, "the operator's migrated gate was deleted by the repair"
        assert (repo / ".git" / "hooks" / "pre-commit.legacy").read_bytes() == _HAND_WRITTEN_PRE_COMMIT
        assert probe_git_hooks(repo).ok

    def test_a_repair_that_never_runs_leaves_the_legacy_slot_alone(self, repo: Path) -> None:
        """The control: `probe.ok` short-circuits before `-f`, so this asserts nothing about it."""
        _install(repo)
        legacy = repo / ".git" / "hooks" / "pre-push.legacy"
        legacy.write_bytes(_HAND_WRITTEN_HOOK)
        legacy.chmod(0o755)

        _install(repo)

        assert legacy.read_bytes() == _HAND_WRITTEN_HOOK


def _quarantine(repo: Path) -> Path:
    return hook_quarantine.quarantine_dir(git_common_dir(repo))


def _parked(repo: Path, name: str) -> Path:
    return _quarantine(repo) / name


_REINSTATE_FAILED = ValueError("the reinstate could not complete")


def _reinstate_refusing(_self: object) -> None:
    raise _REINSTATE_FAILED


class TestNoOkLineOverAPendingQuarantine:
    """`OK` over a destroyed gate is a success line about a loss, and the RE-RUN is where it hid.

    The run that destroys the gate at least reports a failure. The re-run it advises finds the
    hooks genuinely installed, knows nothing about what an earlier run destroyed, and used to
    print `OK ... already installed` forever. The line is qualified by LISTING the quarantine
    rather than by anything carried out of the install, so both runs say the same thing.
    """

    @staticmethod
    def _install_over_a_gate_the_reinstate_could_not_restore(repo: Path) -> list[str]:
        _write_hook_bytes(repo, "pre-push", _HAND_WRITTEN_HOOK)
        with patch.object(hook_quarantine.Quarantine, "reinstate", _reinstate_refusing):
            return _install(repo)

    def test_the_failing_run_names_the_parked_gate(self, repo: Path) -> None:
        lines = self._install_over_a_gate_the_reinstate_could_not_restore(repo)

        assert not any(line.startswith("OK") for line in lines), lines
        assert any(str(_parked(repo, "pre-push")) in line for line in lines), lines
        assert _parked(repo, "pre-push").read_bytes() == _HAND_WRITTEN_HOOK

    def test_the_advised_re_run_still_refuses_to_say_ok(self, repo: Path) -> None:
        """The teeth of this whole change.

        The failing run at least WARNs; the re-run it advises finds the hooks genuinely
        installed, knows nothing about the destruction, and printed `OK` forever.
        """
        self._install_over_a_gate_the_reinstate_could_not_restore(repo)
        parked = _parked(repo, "pre-push")

        lines = _install(repo)

        assert probe_git_hooks(repo).ok, "the re-run is only interesting once the hooks ARE installed"
        assert not any(line.startswith("OK") for line in lines), lines
        assert any(str(parked) in line for line in lines), lines
        assert parked.read_bytes() == _HAND_WRITTEN_HOOK

    def test_a_clean_install_and_its_re_run_both_say_ok(self, repo: Path) -> None:
        """The control: a qualifier that WARNs unconditionally passes the test above."""
        first = _install(repo)
        second = _install(repo)

        assert any(line.startswith("OK") and "installed git hooks" in line for line in first), first
        assert any(line.startswith("OK") and "already installed" in line for line in second), second
        assert hook_quarantine.pending(git_common_dir(repo)) == ()

    def test_the_doctor_fails_on_the_same_fact(self, repo: Path) -> None:
        _write_hook_bytes(repo, "pre-push", _HAND_WRITTEN_HOOK)

        with patch.object(hook_quarantine.Quarantine, "reinstate", _reinstate_refusing):
            _install(repo)

        with patch("teatree.core.gates.git_checkouts.discover_checkouts", return_value=[repo]):
            assert checks_bootstrap._check_git_hooks_installed() is False


class TestBothForeignCopiesAreKeptAndOnlyOneChannelReportsIt:
    """`prek install -f` reaps `<name>` AND `<name>.legacy`; only one of them can be put back.

    Round 2 preserved the gating copy and told the OTHER one's loss to the logger alone, which
    no operator reads. Both copies are parked now, the gating one is restored, and the dark one
    is named on the same line — so there is no second channel left to lose anything on.
    """

    def test_the_dark_legacy_is_parked_beside_the_restored_gate(
        self, repo: Path, caplog: pytest.LogCaptureFixture
    ) -> None:
        _write_hook_bytes(repo, "pre-push", _HAND_WRITTEN_HOOK)
        _write_hook_bytes(repo, "pre-push.legacy", _HAND_WRITTEN_PRE_COMMIT)

        with caplog.at_level(logging.WARNING):
            lines = _install(repo)

        assert (repo / ".git" / "hooks" / "pre-push.legacy").read_bytes() == _HAND_WRITTEN_HOOK
        assert _parked(repo, "pre-push.legacy").read_bytes() == _HAND_WRITTEN_PRE_COMMIT
        assert not any(line.startswith("OK") for line in lines), lines
        assert any(str(_parked(repo, "pre-push.legacy")) in line for line in lines), lines
        assert "only the live" not in caplog.text, "a second channel is reporting what the line already says"

    def test_one_foreign_copy_alone_still_says_ok(self, repo: Path) -> None:
        """The control: the WARN must be caused by the SECOND copy, not by any foreign hook at all."""
        _write_hook_bytes(repo, "pre-push", _HAND_WRITTEN_HOOK)

        lines = _install(repo)

        assert any(line.startswith("OK") and "installed git hooks" in line for line in lines), lines
        assert hook_quarantine.pending(git_common_dir(repo)) == ()


def _touching(sentinel: Path) -> bytes:
    return f'#!/bin/sh\n: > "{sentinel}"\nexit 0\n'.encode()


def _run_pre_push(repo: Path) -> subprocess.CompletedProcess[bytes]:
    """Invoke the installed shim the way git does — from the worktree root, with empty stdin."""
    return subprocess.run(
        [str(repo / ".git" / "hooks" / "pre-push"), "origin", "https://example.invalid/x.git"],
        cwd=repo,
        input=b"",
        capture_output=True,
        check=False,
    )


class TestAnOrphanLegacyIsNeitherDestroyedNorActivated:
    """`<name>.legacy` with no `<name>` beside it: two histories, one filesystem, no way to tell.

    Either prek migrated the operator's gate and the shim was later removed — reachable inside
    teatree itself, since `remove_stale_hooks` unlinks `<name>` and never touches
    `<name>.legacy` — or the operator broke the chain deliberately. Measured: `-f` DELETES the
    orphan, and a resurrected one really does execute on every push. So it is parked: the bytes
    survive, nothing dormant is made live, and the operator is told where it is.
    """

    def test_the_orphan_is_parked_and_named_never_put_back(self, repo: Path) -> None:
        _write_hook_bytes(repo, "pre-push.legacy", _HAND_WRITTEN_HOOK)

        lines = _install(repo)

        assert not (repo / ".git" / "hooks" / "pre-push.legacy").exists()
        assert _parked(repo, "pre-push.legacy").read_bytes() == _HAND_WRITTEN_HOOK
        assert not any(line.startswith("OK") for line in lines), lines
        assert any(str(_parked(repo, "pre-push.legacy")) in line for line in lines), lines

    def test_a_migrated_gate_is_still_restored_in_place(self, repo: Path) -> None:
        """THE control on the orphan decision.

        "`destination is None` always" passes the test above while silently ending
        preservation for every gate prek's own migration mode parked.
        """
        _write_hook_bytes(repo, "pre-push", _HAND_WRITTEN_HOOK)
        _prek_migrate(repo, "pre-push")
        legacy = repo / ".git" / "hooks" / "pre-push.legacy"
        assert legacy.read_bytes() == _HAND_WRITTEN_HOOK, "the fixture never reached prek's migration mode"
        _write_hook_bytes(repo, "pre-commit", _HAND_WRITTEN_PRE_COMMIT)

        lines = _install(repo)

        assert legacy.read_bytes() == _HAND_WRITTEN_HOOK
        assert hook_quarantine.pending(git_common_dir(repo)) == ()
        assert any(line.startswith("OK") for line in lines), lines

    def test_the_parked_orphan_does_not_run_on_a_push(self, repo: Path, tmp_path: Path) -> None:
        sentinel = tmp_path / "ORPHAN_RAN"
        _write_hook_bytes(repo, "pre-push.legacy", _touching(sentinel))

        _install(repo)
        completed = _run_pre_push(repo)

        assert not sentinel.exists(), f"the parked orphan executed on a push: {completed.stderr!r}"

    def test_a_migrated_gate_does_run_on_a_push(self, repo: Path, tmp_path: Path) -> None:
        """Its control: without it, a probe that never actually executes the shim passes vacuously."""
        sentinel = tmp_path / "MIGRATED_RAN"
        _write_hook_bytes(repo, "pre-push", _touching(sentinel))
        _prek_migrate(repo, "pre-push")
        _write_hook_bytes(repo, "pre-commit", _HAND_WRITTEN_PRE_COMMIT)

        _install(repo)
        completed = _run_pre_push(repo)

        assert sentinel.exists(), f"the restored gate never ran: {completed.stdout!r} {completed.stderr!r}"


class TestNoOkLineOverAnUnreadableQuarantine:
    """`OK` over a quarantine nothing could read is a success line about an unknown.

    The `quarantined is None` branch was reachable only by a permission denial, so a mutation
    collapsing it into the `== ()` one survived every test in the suite.
    """

    def test_an_unreadable_quarantine_still_refuses_to_say_ok(self, repo: Path) -> None:
        _quarantine(repo).write_bytes(b"a regular file where the quarantine dir belongs")
        assert hook_quarantine.pending(git_common_dir(repo)) is None, "the fixture did not make the read fail"

        lines = _install(repo)

        assert not any(line.startswith("OK") for line in lines), lines
        assert any(hook_quarantine.QUARANTINE_DIRNAME in line for line in lines), lines

    @skip_if_root
    def test_a_permission_denied_quarantine_refuses_the_ok_too(self, repo: Path) -> None:
        """The positive control: the branch is reachable by a genuine denial, not only ENOTDIR."""
        quarantine = _quarantine(repo)
        quarantine.mkdir(parents=True)
        quarantine.chmod(0o000)
        try:
            assert hook_quarantine.pending(git_common_dir(repo)) is None, "chmod(0o000) did not deny the read"
            lines = _install(repo)
        finally:
            quarantine.chmod(0o700)

        assert not any(line.startswith("OK") for line in lines), lines
        assert any(hook_quarantine.QUARANTINE_DIRNAME in line for line in lines), lines

    def test_a_readable_empty_quarantine_still_says_ok(self, repo: Path) -> None:
        """The negative control: a qualifier that WARNs on any quarantine dir passes both above."""
        quarantine = _quarantine(repo)
        quarantine.mkdir(parents=True)
        quarantine.chmod(0o700)

        lines = _install(repo)

        assert any(line.startswith("OK") for line in lines), lines


class TestASuccessfulInstallThatLeftTheHookAbsentIsNotOk:
    """`prek install` reporting success says nothing about a hook being on disk afterwards."""

    def test_a_successful_install_that_left_the_hook_absent_is_not_ok(self, repo: Path) -> None:
        with patch.object(prek_hook, "install", return_value=StepResult(name="prek-install", success=True)):
            lines = _install(repo)

        assert not any(line.startswith("OK") for line in lines), lines
        assert any("still absent" in line for line in lines), lines


class TestAnUnprobeableCheckoutStillSpeaks:
    """A probe that never reached the quarantine did not find it empty, and the line must say so.

    Its sibling polarity lives in ``tests/teatree_core/gates/test_git_hooks_preflight.py``: the
    DOCTOR must stay silent on the same checkout, where a line is a hard FAIL with no cause.
    """

    def test_an_unprobeable_checkout_never_yields_an_ok_line(self, tmp_path: Path) -> None:
        not_a_checkout = tmp_path / "plain"
        not_a_checkout.mkdir()
        probe = probe_git_hooks(not_a_checkout)
        assert probe.indeterminate_reason is not None, "the fixture turned out to be a checkout"

        line = git_hooks_installer._qualified(probe, git_hooks_installer._HookLine("OK", "already installed"))

        assert line.status == "WARN", line
        assert hook_quarantine.QUARANTINE_DIRNAME in line.text, line

    def test_a_probeable_clean_checkout_keeps_its_ok(self, repo: Path) -> None:
        """The control: a qualifier that WARNs unconditionally passes the test above."""
        _install(repo)

        line = git_hooks_installer._qualified(
            probe_git_hooks(repo), git_hooks_installer._HookLine("OK", "already installed")
        )

        assert line.status == "OK", line
