# Generated by Django 6.0.3 on 2026-03-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_deduplicate_tickets"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                condition=models.Q(("issue_url", ""), _negated=True),
                fields=("issue_url",),
                name="unique_nonempty_issue_url",
            ),
        ),
    ]
