"""Django-free, pydantic-free stdlib reader for the shipped ``defaults.toml``.

The cold-path twin of :func:`teatree.config.schema.shipped_defaults`. The pydantic
model (``schema``) is the hot/Django path's default source — importing it costs
~110ms, too heavy for a per-tool hook leaf. This module reads the SAME
``defaults.toml`` with the stdlib ``tomllib`` (~2ms) so the cold hook / statusline
path gets the shipped default for a key without paying the pydantic import.

Only the standard library is imported — never ``schema``/``pydantic``, never Django,
never a sibling that would pull either — so importing this module keeps the cold
path cheap. The file is packaged data (regenerated by
``manage.py generate_settings_defaults``); the ``[teatree]`` table it exposes carries
EXACTLY the ``Category.DEFAULT`` keys (Secret/Personal keys are absent by
construction and have no shipped default). A coherence test pins each cold default
equal to the model's default per key.

The parse is cached per file mtime — a regenerated ``defaults.toml`` invalidates the
cache on the next read, so a fresh value is never masked by a stale parse.
"""

import threading
import tomllib
from pathlib import Path
from typing import Any

#: The packaged shipped-defaults file — the ONE path every default reader resolves
#: it from: this stdlib one, ``schema.shipped_defaults``, and the resolver's
#: TOML-default tier (``resolution._toml_default_rows``).
DEFAULTS_TOML = Path(__file__).with_name("defaults.toml")
_TEATREE_TABLE = "teatree"

_lock = threading.Lock()
_cache: dict[int, dict[str, Any]] = {}

__all__ = ["DEFAULTS_TOML", "default_for", "shipped_defaults_table"]


def shipped_defaults_table(path: Path = DEFAULTS_TOML) -> dict[str, Any]:
    """The ``[teatree]`` table of ``defaults.toml``, parsed once per file mtime.

    Returns a fresh copy so a caller can never mutate the cached parse. A missing
    file yields an empty table (a fresh checkout always ships the file; the empty
    fallback keeps a cold read from raising).
    """
    try:
        mtime = path.stat().st_mtime_ns
    except OSError:
        return {}
    with _lock:
        table = _cache.get(mtime)
        if table is None:
            table = tomllib.loads(path.read_text(encoding="utf-8")).get(_TEATREE_TABLE, {})
            _cache.clear()  # only the current-mtime parse is worth keeping
            _cache[mtime] = table
    return dict(table)


def default_for(key: str, fallback: object = None, *, path: Path = DEFAULTS_TOML) -> object:
    """The shipped default VALUE for *key*, or *fallback* when it carries none.

    A Default-category key resolves to its ``defaults.toml`` value; a Secret/Personal
    key (absent from the file) resolves to *fallback* — its empty code default.
    """
    return shipped_defaults_table(path).get(key, fallback)
