"""Pure generator for ``defaults.toml`` — in-code defaults + safe live-adopted tunables.

``generate_defaults`` decides, per ``Category.DEFAULT`` key, whether the shipped
default VALUE is the operator's live GLOBAL-scope override or the conservative
in-code default, then serialises the result into the canonical
``config_setting export`` shape (a ``[teatree]`` table with ``speak`` /
``mr_reminder`` sub-tables). It is pure over its inputs — the DB read, the
banned-term term source, and the file write live in the management command
(:mod:`teatree.core.management.commands.generate_settings_defaults`), so this
module stays in the ``config`` layer and is unit-testable with plain dicts.

Adoption policy (owner decision O2). SAFETY-posture keys and DARK feature-flags
ALWAYS keep the fail-closed/off in-code default — a write to one is an
authorization, never a shipped default. Owner-workflow / engagement keys
(:data:`WORKFLOW_ENGAGEMENT_KEYS`) keep the conservative in-code default too: the
live box has turned them on for its own operation, which is wrong for a fresh
install. Every other DEFAULT key adopts the live GLOBAL value when one exists, it
coerces cleanly through the key's own validator, and it survives the injected
banned-term content scan; otherwise it keeps the in-code default.

SECRET / PERSONAL keys are never emitted (their empty code default stays in the
model); overlay-scope rows and stale/retired keys are reported, never emitted.
"""

import json
from collections.abc import Callable
from dataclasses import dataclass, field
from typing import cast

import tomlkit
from tomlkit import items as tomlkit_items

from teatree.config.feature_flags import dark_flags
from teatree.config.known_settings import ALL_KNOWN_CONFIG_SETTINGS
from teatree.config.schema import Category, setting_meta
from teatree.config.setting_registries import SAFETY_POSTURE_KEYS

# A stored config value — the JSON/TOML shapes a ConfigSetting row round-trips.
type SettingValue = bool | int | float | str | list[object] | dict[str, object]

_MISSING = object()

#: Owner-workflow + engagement keys kept at the conservative in-code default even
#: when the live box overrides them (O2). The first row is the owner-named workflow
#: set; the second is the loop / engagement enable-toggles (and their inert config)
#: — a fresh install must not auto-start autonomous work, so these never ship the
#: live "turned on" value.
WORKFLOW_ENGAGEMENT_KEYS: frozenset[str] = frozenset(
    {
        "wip",
        "mode",
        "autoload",
        "contribute",
        "agent_runtime",
        "issue_implementer_enabled",
        "issue_implementer_label",
        "triage_assessor_enabled",
        "active_loop_schedule",
    }
)

#: The two dict-valued DEFAULT keys that render as their own ``[teatree.<name>]``
#: sub-table rather than an inline value in the ``[teatree]`` table.
_SUBTABLE_KEYS: tuple[str, ...] = ("mr_reminder", "speak")

_HEADER = """\
# teatree shipped config defaults — the DEFAULT-category keys at their ship values.
#
# Generated by `manage.py generate_settings_defaults` (do not hand-edit — regenerate).
# Shape: the `config_setting export`/`import` schema — a `[teatree]` table with
# `speak`/`mr_reminder` as sub-tables. EXACTLY the Category.DEFAULT keys of
# `teatree.config.schema.TeatreeSettingsSchema` appear here; PERSONAL/SECRET keys
# (operator identifiers, machine paths, model-routing tables, customer/brand terms,
# credential coordinates) are ABSENT by construction and resolve from their empty
# code defaults.
#
# Per-key VALUE policy: safety-posture keys, dark feature-flags, and owner-workflow /
# engagement keys are pinned to their fail-closed/off/conservative in-code default;
# every other key adopts the operator's live global value only when it coerces
# cleanly and passes the banned-term content scan.
"""

# The scan takes the `"<key> <json-value>"` text and returns the first matched
# banned term (or None). Injected so `config` never imports `hooks` (the layer
# above it); the command binds it to `hooks.term_match.matched_term`.
BannedScan = Callable[[str], str | None]


@dataclass(frozen=True)
class Adoption:
    """One DEFAULT key's emit decision, for the human report."""

    key: str
    emitted: SettingValue
    in_code_default: SettingValue
    disposition: str  # "adopted-live" | "kept-default" | "kept-conservative:<reason>" | "banned-abort:<term>"


@dataclass
class GenerationReport:
    """Everything the run decided, for the operator to review before committing."""

    adopted: list[Adoption] = field(default_factory=list)
    kept_conservative: list[Adoption] = field(default_factory=list)
    banned_aborted: list[Adoption] = field(default_factory=list)
    skipped_secret: list[str] = field(default_factory=list)
    skipped_personal: list[str] = field(default_factory=list)
    overlay_scope_rows: list[tuple[str, str]] = field(default_factory=list)
    stale_keys: list[str] = field(default_factory=list)


@dataclass(frozen=True)
class GenerationResult:
    toml: str
    report: GenerationReport


def conservative_keys() -> frozenset[str]:
    """The keys that ALWAYS ship their in-code default, never the live override."""
    return SAFETY_POSTURE_KEYS | frozenset(dark_flags()) | WORKFLOW_ENGAGEMENT_KEYS


def _default_keys() -> set[str]:
    return {k for k in ALL_KNOWN_CONFIG_SETTINGS if setting_meta(k).category is Category.DEFAULT}


def _conservative_reason(key: str) -> str:
    if key in SAFETY_POSTURE_KEYS:
        return "safety-posture"
    if key in dark_flags():
        return "dark-flag"
    return "workflow-engagement"


def _classify_non_default(
    live_global: dict[str, SettingValue],
    report: GenerationReport,
) -> None:
    """File every non-DEFAULT live global row into the report (never emitted)."""
    for key in sorted(live_global):
        if key not in ALL_KNOWN_CONFIG_SETTINGS:
            report.stale_keys.append(key)
            continue
        category = setting_meta(key).category
        if category is Category.SECRET:
            report.skipped_secret.append(key)
        elif category is Category.PERSONAL:
            report.skipped_personal.append(key)


def _decide_key(
    key: str,
    in_code_default: SettingValue,
    live_global: dict[str, SettingValue],
    banned_scan: BannedScan,
    conservative: frozenset[str],
) -> Adoption:
    """The emit decision for one DEFAULT key."""
    if key in conservative:
        return Adoption(key, in_code_default, in_code_default, f"kept-conservative:{_conservative_reason(key)}")
    live = live_global.get(key, _MISSING)
    if live is _MISSING:
        return Adoption(key, in_code_default, in_code_default, "kept-default")
    try:
        coerced = ALL_KNOWN_CONFIG_SETTINGS[key](live)
    except Exception:  # noqa: BLE001 — a malformed live row is kept-default, not fatal
        return Adoption(key, in_code_default, in_code_default, "kept-default")
    hit = banned_scan(f"{key} {json.dumps(coerced, default=str)}")
    if hit is not None:
        return Adoption(key, in_code_default, in_code_default, f"banned-abort:{hit}")
    disposition = "adopted-live" if coerced != in_code_default else "kept-default"
    return Adoption(key, coerced, in_code_default, disposition)


def generate_defaults(
    *,
    in_code_defaults: dict[str, SettingValue],
    live_global: dict[str, SettingValue],
    overlay_scope_rows: list[tuple[str, str]],
    banned_scan: BannedScan,
) -> GenerationResult:
    """Build ``defaults.toml`` text + the decision report.

    *in_code_defaults* is the DEFAULT-category baseline keyed exactly like the
    ``[teatree]`` table (``speak`` / ``mr_reminder`` as nested dicts). *live_global*
    is every GLOBAL-scope ``ConfigSetting`` row (any category). *overlay_scope_rows*
    is ``(scope, key)`` for every non-global row (reported, never emitted).
    *banned_scan* returns the first banned term hit in a ``"<key> <value>"`` text.
    """
    report = GenerationReport(overlay_scope_rows=sorted(overlay_scope_rows))
    _classify_non_default(live_global, report)
    conservative = conservative_keys()

    emitted: dict[str, SettingValue] = {}
    for key in sorted(_default_keys()):
        decision = _decide_key(key, in_code_defaults[key], live_global, banned_scan, conservative)
        emitted[key] = decision.emitted
        if decision.disposition == "adopted-live":
            report.adopted.append(decision)
        elif decision.disposition.startswith("kept-conservative"):
            report.kept_conservative.append(decision)
        elif decision.disposition.startswith("banned-abort"):
            report.banned_aborted.append(decision)

    return GenerationResult(_serialise(emitted), report)


def _serialise(emitted: dict[str, SettingValue]) -> str:
    """Render *emitted* into the canonical ``[teatree]`` + sub-table TOML text."""
    document = tomlkit.document()
    teatree = tomlkit.table()
    for key in sorted(k for k in emitted if k not in _SUBTABLE_KEYS):
        teatree[key] = emitted[key]
    for name in _SUBTABLE_KEYS:
        teatree[name] = _nested_table(cast("dict[str, SettingValue]", emitted[name]))
    document["teatree"] = teatree
    return _HEADER + "\n" + tomlkit.dumps(document)


def _nested_table(value: dict[str, SettingValue]) -> tomlkit_items.Table:
    """A ``dict``-valued setting rendered as a nested TOML table (channels -> sub-table)."""
    table = tomlkit.table()
    for key in sorted(value):
        inner = value[key]
        table[key] = _nested_table(cast("dict[str, SettingValue]", inner)) if isinstance(inner, dict) else inner
    return table
