"""Host-visible, strictly-derived projection of the container-owned control DB.

The control database lives in a named Docker volume, so a host process cannot open
it at all. Five Claude Code hooks must still resolve their DB-home settings without
Django, under a 30-second ceiling and a restricted PATH — spawning a container per
hook is not viable, and letting them fall through to compiled-in defaults is #3499,
where fourteen kill-switches silently stopped honouring their stored values for
months and the only symptom was an advisory telling the owner to set a flag they had
already set.

So the write seam publishes what those readers need into the bind-mounted data dir.
Five properties define the artifact:

* **Atomic** — temp file plus rename, never an in-place rewrite, so a concurrent
    reader sees the whole old file or the whole new one. A whole-file replace is safe
    across the bind mount where SQLite is not: there is no page-level or shared-memory
    machinery whose coherence the VM boundary has to preserve.
* **Generation-carrying** — :data:`GENERATION_KEY` is a row IN the source, bumped by
    the write seam, so the counter is derived from the database rather than from the
    file it labels, and only ever ratchets.
* **Write-triggered** — regenerated by the same seam that writes those settings,
    never on a timer. A timer is how a projection silently goes stale.
* **Strictly derived, zero authority** — nothing reads it as the source of truth for
    a write, and nothing but :class:`ProjectionPublisher` writes it.
* **Loudly stale** — :class:`ProjectionReader` classifies an absent, unreadable,
    schema-shifted or generation-regressed file and hands back an advisory the hooks
    print, instead of quietly serving values whose freshness it cannot vouch for.
"""

import json
import os
import sqlite3
import sys
import tempfile
from collections.abc import Mapping
from dataclasses import dataclass
from datetime import UTC, datetime
from enum import StrEnum
from pathlib import Path
from typing import cast

PROJECTION_FILENAME = "host-projection.json"
HIGHWATER_FILENAME = ".host-projection-generation"

#: The global-scope ``teatree_config_setting`` row carrying the generation counter.
#: It lives in the source so the counter is a property of the database, and every
#: write seam ratchets it before publishing.
GENERATION_KEY = "host_projection_generation"

#: Bumped whenever the projected SHAPE changes — the version this publisher emits.
SCHEMA_VERSION = 3

#: Every payload schema a reader can still read, which is deliberately a RANGE rather
#: than the one constant above: the reader ships with the source tree while the publisher
#: ships inside the container, so between those two deploys the file on disk is the older
#: shape. Refusing it would put every host cold read back on compiled-in defaults — the
#: exact failure the projection exists to prevent. A version outside the range is a shape
#: this reader has no business interpreting and is still refused loudly.
READABLE_SCHEMA_VERSIONS = frozenset({1, 2, 3})

GLOBAL_SCOPE = ""

_SETTINGS_SQL = "SELECT scope, key, value FROM teatree_config_setting"
_LOOP_STATE_SQL = "SELECT name, status FROM teatree_loop_state"

_FILE_MODE = 0o600


class ProjectionPublishError(RuntimeError):
    """The projection could not be published, or did not survive its own re-read."""


class ProjectionNotWrittenError(ProjectionPublishError):
    """The atomic write itself failed, so the previous projection is still in place."""

    def __init__(self, target: Path, cause: OSError) -> None:
        super().__init__(f"could not publish the host projection at {target}: {cause}")


class ProjectionDidNotLandError(ProjectionPublishError):
    """The write reported success but the file does not read back as what was published."""

    def __init__(self, target: Path, published: int, read_back: object) -> None:
        super().__init__(
            f"host projection at {target} did not survive its own re-read (published generation "
            f"{published}, read back {read_back}). Host hooks are now serving values this write "
            "did not produce."
        )


class Staleness(StrEnum):
    """Why a reader may not trust the projection it just opened."""

    FRESH = "fresh"
    ABSENT = "absent"
    UNREADABLE = "unreadable"
    SCHEMA_MISMATCH = "schema-mismatch"
    REGRESSED = "regressed"


#: A value as the control DB stores it — arbitrary JSON, so the element type is genuinely
#: open. Naming it says that once, instead of six bare `object`s a reader has to re-derive.
type JsonValue = object
#: scope -> key -> value, the shape `ConfigSetting` rows project into. The keys are data
#: (any scope, any setting), so this is a mapping by nature and not a struct.
type ScopedSettings = dict[str, dict[str, JsonValue]]


@dataclass(frozen=True, slots=True)
class HostProjection:
    """The projected read surface: config settings, loop statuses, one generation."""

    generation: int
    settings: ScopedSettings
    loop_state: dict[str, str]
    source: str
    projected_at: str
    schema_version: int = SCHEMA_VERSION

    def setting(self, key: str, *, scope: str = GLOBAL_SCOPE) -> object | None:
        return self.settings.get(scope, {}).get(key)

    def loop_status(self, name: str) -> str | None:
        return self.loop_state.get(name)

    def as_payload(self) -> dict[str, JsonValue]:
        return {
            "schema_version": self.schema_version,
            "generation": self.generation,
            "source": self.source,
            "projected_at": self.projected_at,
            "settings": self.settings,
            "loop_state": self.loop_state,
        }

    @classmethod
    def from_payload(cls, payload: object) -> "HostProjection | None":
        """Rebuild from a decoded payload; ``None`` when any field is the wrong shape.

        Deliberately total: a malformed field is a reason to refuse the whole file,
        not to substitute a plausible-looking partial answer. A schema-2 payload's mode
        tables are simply ignored — a reader that no longer interprets them must not
        forfeit the settings and loop statuses the same file carries.
        """
        if not isinstance(payload, dict):
            return None
        fields = cast("dict[str, JsonValue]", payload)
        generation = fields.get("generation")
        settings = fields.get("settings")
        loop_state = fields.get("loop_state")
        schema_version = fields.get("schema_version")
        if not isinstance(generation, int) or isinstance(generation, bool):
            return None
        if not isinstance(schema_version, int) or not isinstance(settings, dict) or not isinstance(loop_state, dict):
            return None
        return cls(
            generation=generation,
            settings=cast("ScopedSettings", settings),
            loop_state=cast("dict[str, str]", loop_state),
            source=str(fields.get("source", "")),
            projected_at=str(fields.get("projected_at", "")),
            schema_version=schema_version,
        )


@dataclass(frozen=True, slots=True)
class ProjectionRead:
    """What a reader got, and whether it may be trusted."""

    projection: HostProjection | None
    staleness: Staleness
    advisory: str

    @property
    def trustworthy(self) -> bool:
        return self.projection is not None and self.staleness is Staleness.FRESH


def next_generation(current: object) -> int:
    """The generation a write seam stores after this write — a pure ratchet.

    A missing, non-integer or negative stored value restarts at 1 rather than
    propagating garbage, so a hand-edited row cannot wedge the counter.
    """
    if isinstance(current, bool) or not isinstance(current, int) or current < 0:
        return 1
    return current + 1


class ProjectionPublisher:
    """Publishes the host projection from *db_path* into *data_dir*.

    Reads the source READ-ONLY: the publisher runs wherever the write seam runs, and
    the seam has already committed its own write by the time it calls here, so the
    projection needs no second writable handle on the database.
    """

    def __init__(self, db_path: Path, data_dir: Path) -> None:
        self.db_path = db_path
        self.data_dir = data_dir

    @property
    def target(self) -> Path:
        return self.data_dir / PROJECTION_FILENAME

    def build(self) -> HostProjection:
        conn = sqlite3.connect(f"{self.db_path.absolute().as_uri()}?mode=ro", uri=True)
        try:
            settings = self._read_settings(conn)
            loop_state = {str(name): str(status) for name, status in conn.execute(_LOOP_STATE_SQL)}
        finally:
            conn.close()
        stored = settings.get(GLOBAL_SCOPE, {}).get(GENERATION_KEY)
        return HostProjection(
            generation=stored if isinstance(stored, int) and not isinstance(stored, bool) else 0,
            settings=settings,
            loop_state=loop_state,
            source=str(self.db_path),
            projected_at=datetime.now(tz=UTC).isoformat(),
        )

    def publish(self) -> HostProjection:
        """Build, write atomically, then verify by re-read; raise when it did not land."""
        projection = self.build()
        self._write_atomically(projection)
        landed = ProjectionReader(self.data_dir).read().projection
        if landed is None or landed.generation != projection.generation:
            raise ProjectionDidNotLandError(
                self.target,
                projection.generation,
                landed.generation if landed else "nothing",
            )
        return projection

    @staticmethod
    def _read_settings(conn: sqlite3.Connection) -> ScopedSettings:
        settings: ScopedSettings = {}
        for scope, key, raw in conn.execute(_SETTINGS_SQL):
            try:
                value = json.loads(raw)
            except (TypeError, ValueError):
                continue
            settings.setdefault(str(scope), {})[str(key)] = value
        return settings

    def _write_atomically(self, projection: HostProjection) -> None:
        self.data_dir.mkdir(parents=True, exist_ok=True)
        fd, tmp_name = tempfile.mkstemp(prefix=".host-projection-", suffix=".tmp", dir=self.data_dir)
        tmp_path = Path(tmp_name)
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as handle:
                json.dump(projection.as_payload(), handle, sort_keys=True)
                handle.write("\n")
                handle.flush()
                os.fsync(handle.fileno())
            tmp_path.chmod(_FILE_MODE)
            tmp_path.replace(self.target)
        except OSError as error:
            tmp_path.unlink(missing_ok=True)
            raise ProjectionNotWrittenError(self.target, error) from error


class ProjectionReader:
    """Reads and CLASSIFIES the projection — never silently serves an untrusted one.

    The high-water file is what turns "the generation" into a usable signal on a host
    that cannot see the source: a projection whose generation is BELOW one this host
    has already observed is a stale artifact (a restored backup, a rolled-back deploy,
    a publisher writing an older snapshot), and saying so is the whole point.
    """

    def __init__(self, data_dir: Path) -> None:
        self.data_dir = data_dir

    @property
    def target(self) -> Path:
        return self.data_dir / PROJECTION_FILENAME

    @property
    def highwater_path(self) -> Path:
        return self.data_dir / HIGHWATER_FILENAME

    def read(self) -> ProjectionRead:
        try:
            payload = json.loads(self.target.read_text(encoding="utf-8"))
        except FileNotFoundError:
            return self._untrusted(Staleness.ABSENT, "no host projection has been published")
        except (OSError, ValueError) as error:
            return self._untrusted(Staleness.UNREADABLE, f"the host projection could not be decoded ({error})")

        unreadable = self._unsupported_schema(payload)
        if unreadable is not None:
            return unreadable
        projection = HostProjection.from_payload(payload)
        if projection is None:
            return self._untrusted(Staleness.UNREADABLE, "the host projection is malformed")

        seen = self._highwater()
        if projection.generation < seen:
            return ProjectionRead(
                projection,
                Staleness.REGRESSED,
                self._advisory(
                    f"the host projection is at generation {projection.generation}, behind the {seen} "
                    "this host has already seen"
                ),
            )
        self._record_highwater(projection.generation)
        return ProjectionRead(projection, Staleness.FRESH, self._older_schema_advisory(projection))

    def _unsupported_schema(self, payload: object) -> ProjectionRead | None:
        """The refusal for a payload outside :data:`READABLE_SCHEMA_VERSIONS`, else ``None``.

        Checked BEFORE parsing, because a payload of an unknown version is not malformed —
        it is a shape this reader cannot interpret, and naming the version is the
        difference between a diagnosable deploy and a mystery. A payload that is not even
        an object falls through to the parse, which classifies it as malformed.
        """
        if not isinstance(payload, dict):
            return None
        version = cast("Mapping[str, object]", payload).get("schema_version")
        if version in READABLE_SCHEMA_VERSIONS:
            return None
        return self._untrusted(
            Staleness.SCHEMA_MISMATCH,
            f"the host projection is schema v{version}, this reader reads {sorted(READABLE_SCHEMA_VERSIONS)}",
        )

    def _older_schema_advisory(self, projection: HostProjection) -> str:
        """What to say about a payload this reader accepts but that predates its schema.

        Its settings and loop statuses are current and are served — an older shape is a
        superset of what this reader interprets. Naming the version is what makes a
        not-yet-redeployed publisher visible rather than silent.
        """
        if projection.schema_version >= SCHEMA_VERSION:
            return ""
        return (
            f"teatree: the host projection at {self.target} is schema v{projection.schema_version}: its settings and "
            f"loop statuses are served (v{SCHEMA_VERSION} is the current shape). The publisher in the containers has "
            "not been redeployed yet."
        )

    def _untrusted(self, staleness: Staleness, detail: str) -> ProjectionRead:
        return ProjectionRead(None, staleness, self._advisory(detail))

    def _advisory(self, detail: str) -> str:
        return (
            f"teatree: {detail} ({self.target}). DB-home settings are falling back to compiled-in "
            "defaults, so a kill-switch you have set may not be in force. Run `t3 doctor check` "
            "to see whether the containerized stack is publishing."
        )

    def _highwater(self) -> int:
        try:
            return int(self.highwater_path.read_text(encoding="utf-8").strip())
        except (OSError, ValueError):
            return 0

    def _record_highwater(self, generation: int) -> None:
        """Ratchet the observed generation — best effort; a read-only data dir must still read."""
        if generation <= self._highwater():
            return
        try:
            fd, tmp_name = tempfile.mkstemp(prefix=".highwater-", suffix=".tmp", dir=self.data_dir)
            tmp_path = Path(tmp_name)
            with os.fdopen(fd, "w", encoding="utf-8") as handle:
                handle.write(f"{generation}\n")
            tmp_path.replace(self.highwater_path)
        except OSError:
            return


_warned: set[str] = set()

#: Suppresses the once-per-process advisory. Read INSIDE :func:`warn_once` rather than
#: patched onto it: callers bind the function directly (``from … import warn_once`` in
#: :mod:`teatree.config.cold_db`), so a patched module attribute would never reach them —
#: the env seam is the only one every caller shares. The test harness sets it because the
#: advisory is a process-global write to stderr, and whichever test happens to run first in
#: an xdist worker would otherwise read it as trailing output; :mod:`tests.teatree_config`
#: unsets it to cover the advisory itself.
SILENCE_ADVISORY_ENV = "T3_SILENCE_HOST_PROJECTION_ADVISORY"


def reset_advisory_memo() -> None:
    """Forget which advisories were written — for tests, so the once-ness never crosses one."""
    _warned.clear()


def warn_once(advisory: str, env: Mapping[str, str] = os.environ) -> None:
    """Print *advisory* to stderr at most once per process, so a hot hook path stays quiet."""
    if not advisory or advisory in _warned or env.get(SILENCE_ADVISORY_ENV):
        return
    _warned.add(advisory)
    sys.stderr.write(advisory + "\n")
