"""Host-visible, strictly-derived projection of the container-owned control DB.

The control database lives in a named Docker volume, so a host process cannot open
it at all. Five Claude Code hooks must still resolve their DB-home settings without
Django, under a 30-second ceiling and a restricted PATH — spawning a container per
hook is not viable, and letting them fall through to compiled-in defaults is #3499,
where fourteen kill-switches silently stopped honouring their stored values for
months and the only symptom was an advisory telling the owner to set a flag they had
already set.

So the write seam publishes what those readers need into the bind-mounted data dir.
Five properties define the artifact:

* **Atomic** — temp file plus rename, never an in-place rewrite, so a concurrent
    reader sees the whole old file or the whole new one. A whole-file replace is safe
    across the bind mount where SQLite is not: there is no page-level or shared-memory
    machinery whose coherence the VM boundary has to preserve.
* **Generation-carrying** — :data:`GENERATION_KEY` is a row IN the source, bumped by
    the write seam, so the counter is derived from the database rather than from the
    file it labels, and only ever ratchets.
* **Write-triggered** — regenerated by the same seam that writes those settings,
    never on a timer. A timer is how a projection silently goes stale.
* **Strictly derived, zero authority** — nothing reads it as the source of truth for
    a write, and nothing but :class:`ProjectionPublisher` writes it.
* **Loudly stale** — :class:`ProjectionReader` classifies an absent, unreadable,
    schema-shifted or generation-regressed file and hands back an advisory the hooks
    print, instead of quietly serving values whose freshness it cannot vouch for.
"""

import json
import os
import sqlite3
import sys
import tempfile
from collections.abc import Callable, Mapping
from dataclasses import dataclass
from datetime import UTC, datetime
from enum import StrEnum
from pathlib import Path
from typing import cast

PROJECTION_FILENAME = "host-projection.json"
HIGHWATER_FILENAME = ".host-projection-generation"

#: The global-scope ``teatree_config_setting`` row carrying the generation counter.
#: It lives in the source so the counter is a property of the database, and every
#: write seam ratchets it before publishing.
GENERATION_KEY = "host_projection_generation"

#: Bumped whenever the projected SHAPE changes — the version this publisher emits.
SCHEMA_VERSION = 2

#: Every payload schema a reader can still read, which is deliberately a RANGE rather
#: than the one constant above: the reader ships with the source tree while the publisher
#: ships inside the container, so between those two deploys the file on disk is the older
#: shape. Refusing it would put every host cold read back on compiled-in defaults — the
#: exact failure the projection exists to prevent. A version outside the range is a shape
#: this reader has no business interpreting and is still refused loudly.
READABLE_SCHEMA_VERSIONS = frozenset({1, 2})

GLOBAL_SCOPE = ""

_SETTINGS_SQL = "SELECT scope, key, value FROM teatree_config_setting"
_LOOP_STATE_SQL = "SELECT name, status FROM teatree_loop_state"

# The four mode tables the Django-free posture resolver walks. Read here as whole
# tables (the projection is the host's only view of them) except the override, whose
# `ORDER BY set_at DESC LIMIT 1` is the resolver's own query verbatim: the newest row
# is the only one that governs, so projecting the rest would invite a second answer.
_MODE_SQL = "SELECT name, defers_questions, pauses_self_pump, presence_sensitive FROM teatree_loop_preset"
_MODE_OVERRIDE_SQL = "SELECT preset_name, until FROM teatree_loop_preset_override ORDER BY set_at DESC LIMIT 1"
_MODE_SCHEDULE_SQL = "SELECT name, id, timezone FROM teatree_loop_schedule"
_MODE_SLOT_SQL = "SELECT schedule_id, days, start_time, preset_name FROM teatree_loop_schedule_slot"

_FILE_MODE = 0o600


class ProjectionPublishError(RuntimeError):
    """The projection could not be published, or did not survive its own re-read."""


class ProjectionNotWrittenError(ProjectionPublishError):
    """The atomic write itself failed, so the previous projection is still in place."""

    def __init__(self, target: Path, cause: OSError) -> None:
        super().__init__(f"could not publish the host projection at {target}: {cause}")


class ProjectionDidNotLandError(ProjectionPublishError):
    """The write reported success but the file does not read back as what was published."""

    def __init__(self, target: Path, published: int, read_back: object) -> None:
        super().__init__(
            f"host projection at {target} did not survive its own re-read (published generation "
            f"{published}, read back {read_back}). Host hooks are now serving values this write "
            "did not produce."
        )


class Staleness(StrEnum):
    """Why a reader may not trust the projection it just opened."""

    FRESH = "fresh"
    ABSENT = "absent"
    UNREADABLE = "unreadable"
    SCHEMA_MISMATCH = "schema-mismatch"
    REGRESSED = "regressed"


def _text(value: object) -> str:
    """A nullable TEXT column as the projected string — ``""`` for a SQL ``NULL``."""
    return "" if value is None else str(value)


def _strings(payload: object, keys: tuple[str, ...]) -> tuple[str, ...] | None:
    """The *keys* of *payload* when every one of them is a string, else ``None``."""
    if not isinstance(payload, dict):
        return None
    entries = cast("Mapping[str, object]", payload)
    values = tuple(entries.get(key) for key in keys)
    return cast("tuple[str, ...]", values) if all(isinstance(value, str) for value in values) else None


def _booleans(payload: object, keys: tuple[str, ...]) -> tuple[bool, ...] | None:
    """The *keys* of *payload* when every one of them is a real bool, else ``None``."""
    if not isinstance(payload, dict):
        return None
    entries = cast("Mapping[str, object]", payload)
    values = tuple(entries.get(key) for key in keys)
    return cast("tuple[bool, ...]", values) if all(isinstance(value, bool) for value in values) else None


#: A value as the control DB stores it — arbitrary JSON, so the element type is genuinely
#: open. Naming it says that once, instead of six bare `object`s a reader has to re-derive.
type JsonValue = object
#: scope -> key -> value, the shape `ConfigSetting` rows project into. The keys are data
#: (any scope, any setting), so this is a mapping by nature and not a struct.
type ScopedSettings = dict[str, dict[str, JsonValue]]


@dataclass(frozen=True, slots=True)
class ModeRow:
    """One ``teatree_loop_preset`` row — the three booleans that ARE a mode's posture."""

    defers_questions: bool
    pauses_self_pump: bool
    presence_sensitive: bool

    def as_payload(self) -> dict[str, bool]:
        return {
            "defers_questions": self.defers_questions,
            "pauses_self_pump": self.pauses_self_pump,
            "presence_sensitive": self.presence_sensitive,
        }

    @classmethod
    def from_payload(cls, payload: object) -> "ModeRow | None":
        values = _booleans(payload, ("defers_questions", "pauses_self_pump", "presence_sensitive"))
        return None if values is None else cls(*values)


@dataclass(frozen=True, slots=True)
class OverrideRow:
    """The one ``teatree_loop_preset_override`` row that governs — newest by ``set_at``.

    ``until`` carries the raw ``DateTimeField`` text; empty means the override holds
    until it is cleared, which is what a SQL ``NULL`` in that column says.
    """

    preset_name: str
    until: str

    def as_payload(self) -> dict[str, str]:
        return {"preset_name": self.preset_name, "until": self.until}

    @classmethod
    def from_payload(cls, payload: object) -> "OverrideRow | None":
        values = _strings(payload, ("preset_name", "until"))
        return None if values is None else cls(*values)


@dataclass(frozen=True, slots=True)
class ScheduleRow:
    """One ``teatree_loop_schedule`` row: the key its slots group under, and their zone.

    ``schedule_id`` is the table's opaque join key stringified, because it is a mapping
    key in the payload — the resolver only ever hands it back to look the slots up.
    """

    schedule_id: str
    timezone: str

    def as_payload(self) -> dict[str, str]:
        return {"schedule_id": self.schedule_id, "timezone": self.timezone}

    @classmethod
    def from_payload(cls, payload: object) -> "ScheduleRow | None":
        values = _strings(payload, ("schedule_id", "timezone"))
        return None if values is None else cls(*values)


@dataclass(frozen=True, slots=True)
class SlotRow:
    """One ``teatree_loop_schedule_slot`` start point, every column as its raw text.

    Projected verbatim — ``days`` still the ``JSONField``'s JSON text, ``start_time``
    still the ``TimeField``'s ``HH:MM[:SS]`` — so the weekday and time parsers in
    :mod:`teatree.config.cold_mode` stay the only things that interpret them, on the
    projected side exactly as on the database one.
    """

    days: str
    start_time: str
    preset_name: str

    def as_payload(self) -> dict[str, str]:
        return {"days": self.days, "start_time": self.start_time, "preset_name": self.preset_name}

    @classmethod
    def from_payload(cls, payload: object) -> "SlotRow | None":
        values = _strings(payload, ("days", "start_time", "preset_name"))
        return None if values is None else cls(*values)


def _parse_mapping[T](payload: object, parse: Callable[[object], T | None]) -> dict[str, T] | None:
    """Every entry parsed under a string key, or ``None`` — one bad entry refuses the map."""
    if not isinstance(payload, dict):
        return None
    parsed: dict[str, T] = {}
    for key, value in cast("Mapping[object, object]", payload).items():
        entry = parse(value)
        if not isinstance(key, str) or entry is None:
            return None
        parsed[key] = entry
    return parsed


def _parse_slot_list(payload: object) -> tuple[SlotRow, ...] | None:
    """One schedule's slots, or ``None`` when any entry is the wrong shape."""
    if not isinstance(payload, list):
        return None
    parsed = [SlotRow.from_payload(entry) for entry in cast("list[object]", payload)]
    if any(slot is None for slot in parsed):
        return None
    return cast("tuple[SlotRow, ...]", tuple(parsed))


def _parse_override(payload: object) -> tuple[OverrideRow | None, bool]:
    """The projected override row, and whether its payload was a sound shape at all.

    An ABSENT override and a MALFORMED one are different answers: the first is the
    ordinary no-override state, the second must refuse the whole file.
    """
    if payload is None:
        return None, True
    row = OverrideRow.from_payload(payload)
    return row, row is not None


@dataclass(frozen=True, slots=True)
class HostProjection:
    """The projected read surface: config settings, loop statuses, the mode tables, one generation.

    The four mode tables are here because the Django-free posture resolver walks them
    on every hook, and on a host the database they live in cannot be opened at all — so
    without them every cold hook resolved "unreadable" and the deferring postures the
    owner had configured stopped being honoured.
    """

    generation: int
    settings: ScopedSettings
    loop_state: dict[str, str]
    modes: dict[str, ModeRow]
    mode_override: OverrideRow | None
    mode_schedules: dict[str, ScheduleRow]
    mode_schedule_slots: dict[str, tuple[SlotRow, ...]]
    source: str
    projected_at: str
    schema_version: int = SCHEMA_VERSION

    def setting(self, key: str, *, scope: str = GLOBAL_SCOPE) -> object | None:
        return self.settings.get(scope, {}).get(key)

    def loop_status(self, name: str) -> str | None:
        return self.loop_state.get(name)

    def mode(self, name: str) -> ModeRow | None:
        return self.modes.get(name)

    def schedule(self, name: str) -> ScheduleRow | None:
        return self.mode_schedules.get(name)

    def slots(self, schedule_id: str) -> tuple[SlotRow, ...]:
        """The slots of *schedule_id* — the projected side of ``WHERE schedule_id=?``."""
        return self.mode_schedule_slots.get(schedule_id, ())

    def as_payload(self) -> dict[str, JsonValue]:
        return {
            "schema_version": self.schema_version,
            "generation": self.generation,
            "source": self.source,
            "projected_at": self.projected_at,
            "settings": self.settings,
            "loop_state": self.loop_state,
            "modes": {name: mode.as_payload() for name, mode in self.modes.items()},
            "mode_override": self.mode_override.as_payload() if self.mode_override is not None else None,
            "mode_schedules": {name: schedule.as_payload() for name, schedule in self.mode_schedules.items()},
            "mode_schedule_slots": {
                schedule_id: [slot.as_payload() for slot in slots]
                for schedule_id, slots in self.mode_schedule_slots.items()
            },
        }

    @classmethod
    def from_payload(cls, payload: object) -> "HostProjection | None":
        """Rebuild from a decoded payload; ``None`` when any field is the wrong shape.

        Deliberately total: a malformed field is a reason to refuse the whole file,
        not to substitute a plausible-looking partial answer. The mode tables are
        the one exception, and only by ABSENCE: an older publisher emits none of them,
        so a payload without them rebuilds with an empty mode surface rather than
        forfeiting the settings and loop statuses it does carry. Present-but-malformed
        mode fields still refuse the whole payload.
        """
        if not isinstance(payload, dict):
            return None
        fields = cast("dict[str, JsonValue]", payload)
        generation = fields.get("generation")
        settings = fields.get("settings")
        loop_state = fields.get("loop_state")
        schema_version = fields.get("schema_version")
        modes = _parse_mapping(fields.get("modes", {}), ModeRow.from_payload)
        schedules = _parse_mapping(fields.get("mode_schedules", {}), ScheduleRow.from_payload)
        slots = _parse_mapping(fields.get("mode_schedule_slots", {}), _parse_slot_list)
        override, override_sound = _parse_override(fields.get("mode_override"))
        if not isinstance(generation, int) or isinstance(generation, bool):
            return None
        if not isinstance(schema_version, int) or not isinstance(settings, dict) or not isinstance(loop_state, dict):
            return None
        if modes is None or schedules is None or slots is None or not override_sound:
            return None
        return cls(
            generation=generation,
            settings=cast("ScopedSettings", settings),
            loop_state=cast("dict[str, str]", loop_state),
            modes=modes,
            mode_override=override,
            mode_schedules=schedules,
            mode_schedule_slots=slots,
            source=str(fields.get("source", "")),
            projected_at=str(fields.get("projected_at", "")),
            schema_version=schema_version,
        )


@dataclass(frozen=True, slots=True)
class ProjectionRead:
    """What a reader got, and whether it may be trusted."""

    projection: HostProjection | None
    staleness: Staleness
    advisory: str

    @property
    def trustworthy(self) -> bool:
        return self.projection is not None and self.staleness is Staleness.FRESH


def next_generation(current: object) -> int:
    """The generation a write seam stores after this write — a pure ratchet.

    A missing, non-integer or negative stored value restarts at 1 rather than
    propagating garbage, so a hand-edited row cannot wedge the counter.
    """
    if isinstance(current, bool) or not isinstance(current, int) or current < 0:
        return 1
    return current + 1


class ProjectionPublisher:
    """Publishes the host projection from *db_path* into *data_dir*.

    Reads the source READ-ONLY: the publisher runs wherever the write seam runs, and
    the seam has already committed its own write by the time it calls here, so the
    projection needs no second writable handle on the database.
    """

    def __init__(self, db_path: Path, data_dir: Path) -> None:
        self.db_path = db_path
        self.data_dir = data_dir

    @property
    def target(self) -> Path:
        return self.data_dir / PROJECTION_FILENAME

    def build(self) -> HostProjection:
        conn = sqlite3.connect(f"{self.db_path.absolute().as_uri()}?mode=ro", uri=True)
        try:
            settings = self._read_settings(conn)
            loop_state = {str(name): str(status) for name, status in conn.execute(_LOOP_STATE_SQL)}
            modes = self._read_modes(conn)
            override = self._read_override(conn)
            schedules = self._read_schedules(conn)
            slots = self._read_slots(conn)
        finally:
            conn.close()
        stored = settings.get(GLOBAL_SCOPE, {}).get(GENERATION_KEY)
        return HostProjection(
            generation=stored if isinstance(stored, int) and not isinstance(stored, bool) else 0,
            settings=settings,
            loop_state=loop_state,
            modes=modes,
            mode_override=override,
            mode_schedules=schedules,
            mode_schedule_slots=slots,
            source=str(self.db_path),
            projected_at=datetime.now(tz=UTC).isoformat(),
        )

    def publish(self) -> HostProjection:
        """Build, write atomically, then verify by re-read; raise when it did not land."""
        projection = self.build()
        self._write_atomically(projection)
        landed = ProjectionReader(self.data_dir).read().projection
        if landed is None or landed.generation != projection.generation:
            raise ProjectionDidNotLandError(
                self.target,
                projection.generation,
                landed.generation if landed else "nothing",
            )
        return projection

    @staticmethod
    def _read_settings(conn: sqlite3.Connection) -> ScopedSettings:
        settings: ScopedSettings = {}
        for scope, key, raw in conn.execute(_SETTINGS_SQL):
            try:
                value = json.loads(raw)
            except (TypeError, ValueError):
                continue
            settings.setdefault(str(scope), {})[str(key)] = value
        return settings

    @staticmethod
    def _mode_rows(conn: sqlite3.Connection, sql: str) -> list[tuple[object, ...]]:
        """The rows of *sql*, or none at all when the table is not there yet.

        A control plane whose mode tables have not been migrated must still publish the
        settings the kill-switches read: letting one unreachable table forfeit the whole
        projection is #3499's failure shape, and an empty mode surface resolves to
        reachable — the direction the posture reader deliberately fails in anyway.
        """
        try:
            return conn.execute(sql).fetchall()
        except sqlite3.Error:
            return []

    @classmethod
    def _read_modes(cls, conn: sqlite3.Connection) -> dict[str, ModeRow]:
        return {
            str(name): ModeRow(
                defers_questions=bool(defers), pauses_self_pump=bool(pauses), presence_sensitive=bool(sensitive)
            )
            for name, defers, pauses, sensitive in cls._mode_rows(conn, _MODE_SQL)
        }

    @classmethod
    def _read_override(cls, conn: sqlite3.Connection) -> OverrideRow | None:
        rows = cls._mode_rows(conn, _MODE_OVERRIDE_SQL)
        return next((OverrideRow(preset_name=str(name), until=_text(until)) for name, until in rows), None)

    @classmethod
    def _read_schedules(cls, conn: sqlite3.Connection) -> dict[str, ScheduleRow]:
        return {
            str(name): ScheduleRow(schedule_id=str(schedule_id), timezone=_text(zone))
            for name, schedule_id, zone in cls._mode_rows(conn, _MODE_SCHEDULE_SQL)
        }

    @classmethod
    def _read_slots(cls, conn: sqlite3.Connection) -> dict[str, tuple[SlotRow, ...]]:
        grouped: dict[str, list[SlotRow]] = {}
        for schedule_id, days, start_time, preset_name in cls._mode_rows(conn, _MODE_SLOT_SQL):
            grouped.setdefault(str(schedule_id), []).append(
                SlotRow(days=_text(days), start_time=_text(start_time), preset_name=str(preset_name))
            )
        return {schedule_id: tuple(slots) for schedule_id, slots in grouped.items()}

    def _write_atomically(self, projection: HostProjection) -> None:
        self.data_dir.mkdir(parents=True, exist_ok=True)
        fd, tmp_name = tempfile.mkstemp(prefix=".host-projection-", suffix=".tmp", dir=self.data_dir)
        tmp_path = Path(tmp_name)
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as handle:
                json.dump(projection.as_payload(), handle, sort_keys=True)
                handle.write("\n")
                handle.flush()
                os.fsync(handle.fileno())
            tmp_path.chmod(_FILE_MODE)
            tmp_path.replace(self.target)
        except OSError as error:
            tmp_path.unlink(missing_ok=True)
            raise ProjectionNotWrittenError(self.target, error) from error


class ProjectionReader:
    """Reads and CLASSIFIES the projection — never silently serves an untrusted one.

    The high-water file is what turns "the generation" into a usable signal on a host
    that cannot see the source: a projection whose generation is BELOW one this host
    has already observed is a stale artifact (a restored backup, a rolled-back deploy,
    a publisher writing an older snapshot), and saying so is the whole point.
    """

    def __init__(self, data_dir: Path) -> None:
        self.data_dir = data_dir

    @property
    def target(self) -> Path:
        return self.data_dir / PROJECTION_FILENAME

    @property
    def highwater_path(self) -> Path:
        return self.data_dir / HIGHWATER_FILENAME

    def read(self) -> ProjectionRead:
        try:
            payload = json.loads(self.target.read_text(encoding="utf-8"))
        except FileNotFoundError:
            return self._untrusted(Staleness.ABSENT, "no host projection has been published")
        except (OSError, ValueError) as error:
            return self._untrusted(Staleness.UNREADABLE, f"the host projection could not be decoded ({error})")

        unreadable = self._unsupported_schema(payload)
        if unreadable is not None:
            return unreadable
        projection = HostProjection.from_payload(payload)
        if projection is None:
            return self._untrusted(Staleness.UNREADABLE, "the host projection is malformed")

        seen = self._highwater()
        if projection.generation < seen:
            return ProjectionRead(
                projection,
                Staleness.REGRESSED,
                self._advisory(
                    f"the host projection is at generation {projection.generation}, behind the {seen} "
                    "this host has already seen"
                ),
            )
        self._record_highwater(projection.generation)
        return ProjectionRead(projection, Staleness.FRESH, self._older_schema_advisory(projection))

    def _unsupported_schema(self, payload: object) -> ProjectionRead | None:
        """The refusal for a payload outside :data:`READABLE_SCHEMA_VERSIONS`, else ``None``.

        Checked BEFORE parsing, because a payload of an unknown version is not malformed —
        it is a shape this reader cannot interpret, and naming the version is the
        difference between a diagnosable deploy and a mystery. A payload that is not even
        an object falls through to the parse, which classifies it as malformed.
        """
        if not isinstance(payload, dict):
            return None
        version = cast("Mapping[str, object]", payload).get("schema_version")
        if version in READABLE_SCHEMA_VERSIONS:
            return None
        return self._untrusted(
            Staleness.SCHEMA_MISMATCH,
            f"the host projection is schema v{version}, this reader reads {sorted(READABLE_SCHEMA_VERSIONS)}",
        )

    def _older_schema_advisory(self, projection: HostProjection) -> str:
        """What to say about a payload this reader accepts but that predates its schema.

        Its settings and loop statuses are current and are served; what an older shape
        cannot carry is the mode rows, so the posture resolver degrades to the answer it
        gave before they were projected. Naming that is what makes a not-yet-redeployed
        publisher visible rather than silent.
        """
        if projection.schema_version >= SCHEMA_VERSION:
            return ""
        return (
            f"teatree: the host projection at {self.target} is schema v{projection.schema_version}: its settings and "
            f"loop statuses are served, but it carries no mode rows (v{SCHEMA_VERSION} projects them), so the mode "
            "posture resolves as if the control plane were unreadable. The publisher in the containers has not been "
            "redeployed yet."
        )

    def _untrusted(self, staleness: Staleness, detail: str) -> ProjectionRead:
        return ProjectionRead(None, staleness, self._advisory(detail))

    def _advisory(self, detail: str) -> str:
        return (
            f"teatree: {detail} ({self.target}). DB-home settings are falling back to compiled-in "
            "defaults, so a kill-switch you have set may not be in force. Run `t3 doctor check` "
            "to see whether the containerized stack is publishing."
        )

    def _highwater(self) -> int:
        try:
            return int(self.highwater_path.read_text(encoding="utf-8").strip())
        except (OSError, ValueError):
            return 0

    def _record_highwater(self, generation: int) -> None:
        """Ratchet the observed generation — best effort; a read-only data dir must still read."""
        if generation <= self._highwater():
            return
        try:
            fd, tmp_name = tempfile.mkstemp(prefix=".highwater-", suffix=".tmp", dir=self.data_dir)
            tmp_path = Path(tmp_name)
            with os.fdopen(fd, "w", encoding="utf-8") as handle:
                handle.write(f"{generation}\n")
            tmp_path.replace(self.highwater_path)
        except OSError:
            return


_warned: set[str] = set()

#: Suppresses the once-per-process advisory. Read INSIDE :func:`warn_once` rather than
#: patched onto it: callers bind the function directly (``from … import warn_once`` in
#: :mod:`teatree.config.cold_db`), so a patched module attribute would never reach them —
#: the env seam is the only one every caller shares. The test harness sets it because the
#: advisory is a process-global write to stderr, and whichever test happens to run first in
#: an xdist worker would otherwise read it as trailing output; :mod:`tests.teatree_config`
#: unsets it to cover the advisory itself.
SILENCE_ADVISORY_ENV = "T3_SILENCE_HOST_PROJECTION_ADVISORY"


def reset_advisory_memo() -> None:
    """Forget which advisories were written — for tests, so the once-ness never crosses one."""
    _warned.clear()


def warn_once(advisory: str, env: Mapping[str, str] = os.environ) -> None:
    """Print *advisory* to stderr at most once per process, so a hot hook path stays quiet."""
    if not advisory or advisory in _warned or env.get(SILENCE_ADVISORY_ENV):
        return
    _warned.add(advisory)
    sys.stderr.write(advisory + "\n")
