"""One sentence per config key — authored ONCE, rendered by every surface that explains one.

Two consumers today: :func:`~teatree.config.setting_groups.grouped_settings_table` emits each
entry as the tail of the trailing comment beside its key in ``defaults.toml`` (behind what the
key ACCEPTS — :mod:`teatree.config.setting_annotation`), and the dashboard settings grid renders
it as the tooltip on the setting name. Maintaining the two separately is the #3854
shape — a second copy that drifts the first time a setting changes meaning.

Deliberately Django-free AND pydantic-free, a plain dict with no imports. ``defaults.toml``
is written from the cold path, which must never reach ``schema`` (~110ms of pydantic); a
``Field(description=...)`` on the model would put the help text behind exactly that import,
and would un-share the per-``(category, registry)`` ``SettingMeta`` markers the schema keeps
one-line-per-field. The key name is the join, and
``tests/config/test_setting_help.py`` pins this table total over the schema — a new setting
with no entry fails the build rather than shipping an unexplained key.

An entry is one sentence, no trailing period, and carries no ``" = "`` (the shipped-file
conformance suite reads ``key = value`` lines out of the rendered TOML by that separator).
"""

#: Every schema key's one-line explanation. Pinned total and exact against the schema.
SETTING_HELP: dict[str, str] = {
    "active_loop_schedule": "name of the weekly schedule deciding when the autonomous loops may run",
    "admin_autologin_enabled": "log the loopback operator into Django admin without a password prompt",
    "adaptive_intake_concurrency_enabled": "let the resource loop set intake concurrency from observed headroom",
    "admission_governor_enabled": "let the governor refuse new work when the box is already saturated",
    "admit_colleague_prs_to_board": "put pull requests opened by colleagues onto the review board",
    "agent_compaction_keep_recent": "per-phase count of recent messages a compacted history keeps",
    "agent_harness": "which agent CLI teatree drives (claude, codex, ...)",
    "agent_harness_provider": "credential provider the harness authenticates with; empty inherits the ambient one",
    "agent_honesty_model": "model used for honesty-critical verification, where over-claiming costs most",
    "agent_phase_fanout": "how many sub-agents each lifecycle phase may dispatch in parallel",
    "agent_phase_harness": "per-phase harness override, for a phase that needs a different CLI",
    "agent_phase_models": "per-phase model override, keyed by lifecycle phase name",
    "agent_pydantic_ai_tier_models": "model per tier for the pydantic-ai lane",
    "agent_session_effort": "reasoning effort the main session runs at",
    "agent_session_model": "model the main orchestrating session runs on",
    "agent_session_permission_mode": "permission mode the main session is pinned to; empty keeps the unattended pin",
    "agent_signature": "append an agent signature to artifacts posted under the operator's identity",
    "agent_skill_models": "per-skill model override, for a skill that needs a stronger or cheaper model",
    "agent_tier_effort": "reasoning effort per cost tier",
    "agent_tier_models": "which model each cost tier resolves to",
    "allow_destructive_disk": "allow disk reclamation to remove artifacts it cannot prove are rebuildable",
    "allow_destructive_ram": "allow the RAM reaper to kill processes outside its allowlist",
    "anthropic_api_key_pass_paths": "password-store paths the Anthropic API key is read from",
    "anthropic_oauth_pass_paths": "password-store paths the Anthropic OAuth credential is read from",
    "approved_recipe_sha": "commit of the provisioning recipe the operator reviewed and approved",
    "architectural_review_after_merge_count": "merges that must land before another architectural review is due",
    "architectural_review_cadence_hours": "hours between architectural review runs",
    "architectural_review_disabled": "stop scheduling architectural reviews",
    "architectural_review_retry_backoff_hours": "hours to wait before retrying a failed architectural review",
    "architectural_review_skill": "skill the architectural review loop runs",
    "ask_before_backlog_sweep_closes": "ask the operator before a backlog sweep closes an issue",
    "ask_before_creating_news_tickets": "ask the operator before the news scanner files a ticket",
    "attachment_gate_enabled": "refuse a post whose attachment was never verified to exist",
    "auto_disposition_enabled": "let the loop close or re-label issues it has decided about",
    "auto_disposition_max_closes_per_tick": "ceiling on issues auto-disposition may close in one tick",
    "auto_update_reinstall": "reinstall the CLI after an update instead of only pulling",
    "auto_update_require_green_main": "only self-update onto a main whose CI is green",
    "autoload": "load the suggested skills automatically at session start",
    "autonomy": "how far the factory may act without asking the operator",
    "backlog_sweep_cadence_hours": "hours between backlog sweeps",
    "backlog_sweep_disabled": "stop scheduling backlog sweeps",
    "backlog_sweep_skill": "skill the backlog sweep loop runs",
    "ban_close_trailers_on_namespaces": "repo namespaces where a commit may not carry a closing trailer",
    "banned_brands": "brand names refused in anything published to a public surface",
    "banned_term_registry": "extra banned-term groups, each name mapped to its own term list",
    "answer_first_gate_enabled": "refuse a turn that reports a dispatch instead of answering the user's question",
    "banned_terms": "terms refused in anything published to a public surface",
    "banned_terms_allowlist": "phrases exempted from the banned-term scan despite matching a term",
    "banned_terms_gate_enabled": "run the banned-term scan before a publish",
    "banned_terms_required": "refuse to scan when no banned-term list is configured, instead of warning",
    "billing_cycle_anchor_day": "day of the month the subscription's usage window resets",
    "boost_concurrency": "extra concurrent units allowed while the box is in boost",
    "bulk_close_threshold": "how many closes in one run count as a bulk action needing approval",
    "cheap_phase_admission_ceiling": "how many cheap-class phase agents still run while the box is braked",
    "check_updates": "check for a newer teatree on startup",
    "chrome_devtools_headless": "run the devtools browser headless",
    "chrome_devtools_mcp_enabled": "expose the Chrome devtools MCP server to agents",
    "ci_eval_heal_autofix_enabled": "let CI propose a fix for a red eval scenario on its own",
    "claude_chrome": "drive Chrome through the Claude browser integration",
    "clean_ignore": "branch globs the cleanup reapers never touch",
    "colleague_repo_url_pattern": "regex matching repo URLs owned by colleagues rather than the operator",
    "completion_claim_gate_enabled": "refuse a multi-deliverable completion claim carrying no evidence map",
    "config_overwrite_gate_enabled": "refuse a blind overwrite of a config file that was not read first",
    "contribute": "allow a retro to edit teatree's own skills",
    "contribute_plugin_dir": "directory holding the plugin a contribute run writes to",
    "cost_model_prices": "price per model, used to cost a run",
    "critic_gate_mode": "how hard the critic gate blocks work it judges inadequate",
    "danger_gate_fail_open": "let the danger gate pass when it cannot evaluate, instead of refusing",
    "dashboard_instance_label": "name shown in the dashboard header, to tell two boxes apart",
    "db_backup_cadence_hours": "hours between database backups",
    "db_backup_disabled": "stop scheduling database backups",
    "db_backup_retention_days": "days a database backup is kept before it is pruned",
    "deny_circuit_breaker_enabled": "pause dispatch after repeated classifier denials instead of retrying",
    "deny_circuit_breaker_threshold": "consecutive denials that trip the circuit breaker",
    "directive_intake_per_tick": "how many owner directives the directive loop intakes per tick",
    "directive_loop_enabled": "run the directive loop that turns owner directives into config",
    "directive_verify_days": "days a ratified directive is watched before it is considered settled",
    "disk_cache_allowlist": "cache directories disk reclamation may empty",
    "disk_crit_free_gb": "free disk below this many GB is critical",
    "disk_warn_free_gb": "free disk below this many GB warns",
    "dispatch_quote_gate_on_task_create_enabled": "check quoting of a dispatch brief when the task is created",
    "dogfood_smoke_cadence_hours": "hours between dogfood smoke runs",
    "dogfood_smoke_disabled": "stop scheduling dogfood smoke runs",
    "dogfood_smoke_overlay": "overlay the dogfood smoke run exercises",
    "dogfood_smoke_skill": "skill the dogfood smoke loop runs",
    "dream_propose_evals": "let the dream loop propose new eval scenarios",
    "e2e_confidence_threshold": "confidence an E2E verdict must reach before it counts as evidence",
    "e2e_mandatory_gate_enabled": "require posted E2E evidence before a display-impacting change ships",
    "e2e_repos": "repos whose changes are subject to the E2E gate",
    "enforce_regulated_path": "route work touching a regulated path through the allowlisted models only",
    "envelope_stop_gate_refusals": "refuse a turn that ends without the required result envelope",
    "eval_local_cadence_hours": "hours between local eval runs",
    "eval_local_disabled": "stop scheduling local eval runs",
    "eval_local_skill": "skill the local eval loop runs",
    "excluded_skills": "skills never offered to an agent, whatever the loader suggests",
    "expected_required_contexts": "CI check names a pull request must carry before it can merge",
    "factory_score_enabled": "compute and record the factory health score each tick",
    "fleet_claim_enabled": "let this box claim work from the shared fleet queue",
    "gate_relaxation_gate_enabled": "refuse a change that weakens a safety gate without approval",
    "git_add_all_gate_enabled": "refuse a whole-tree `git add -A` / `git add .` stage",
    "gitlab_approval_scanner_enabled": "scan GitLab for approvals that should advance a ticket",
    "glab_stale_base_remote_gate_enabled": "refuse a merge-request create on a stale glab-base remote (glab no-ops)",
    "handover_mirror_path": "path a hand-off document is mirrored to, beside the durable record",
    "headless_authoring_gate_enabled": "refuse headless authoring outside a live worktree",
    "agent_max_turns": "turn ceiling for one agent run",
    "hook_fetch_titles": "let hooks fetch issue titles, at the cost of a network call per prompt",
    "hook_validator_timeout_seconds": "seconds a hook validator may run before it is abandoned",
    "idle_stack_e2e_recent_minutes": "minutes an E2E run keeps a stack safe from the idle reaper",
    "idle_stack_idle_minutes": "minutes of inactivity after which a local stack counts as idle",
    "idle_stack_reaper_cadence_minutes": "minutes between idle-stack reaper runs",
    "idle_stack_reaper_disabled": "stop reaping idle local stacks",
    "incoming_event_retention_days": "days an incoming event row is kept",
    "incremental_push_gate": "scope the push gate to the diff instead of running it whole-tree",
    "independent_reviewer_identities": (
        "extra identities trusted to record an independent review, beside the operator's own handles"
    ),
    "intake_ram_per_agent_gb": "RAM one admitted ticket is sized at when deriving intake concurrency",
    "intake_ram_reserve_gb": "RAM held back from intake sizing so a burst is absorbed instead of OOMing",
    "internal_publish_namespaces": "repo namespaces treated as internal, where internal identifiers may appear",
    "issue_implementer_enabled": "let the loop claim and implement labelled issues",
    "issue_implementer_label": "label an issue must carry for the implementer to claim it",
    "issue_implementer_max_concurrent": "fallback in-flight ceiling when the resource loop has no adaptive reading",
    "limit_autorecovery_enabled": "resume automatically once a usage limit window reopens",
    "local_stack_queue_disabled": "stop queueing work that needs a local stack",
    "local_stack_queue_max_attempts": "attempts a queued local-stack unit gets before it is abandoned",
    "loop_cadence_seconds": "default seconds between ticks of a loop that declares none",
    "loop_runner_enabled": "run the worker that drives the loop ticks",
    "loops": "per-loop overrides, keyed by loop name",
    "low_power_auto_engage": "switch to the low-token preset by itself when the box is under pressure",
    "low_power_preset_name": "preset engaged when low power is on",
    "main_clone_guard_gate_enabled": "refuse an edit to the main clone's working tree",
    "max_concurrent_local_stacks": "how many tickets may hold a running local stack at once",
    "max_open_prs_per_repo_per_ticket": "open pull requests one ticket may hold in one repo",
    "max_worktree_gc_per_tick": "worktrees the garbage collector may reap in one tick",
    "mcp_privacy_gate_enabled": "scan MCP tool payloads for private data before they leave the box",
    "mcp_slack_write_gate_enabled": "gate MCP Slack writes behind the on-behalf rules",
    "memory_recall_enabled": "recall durable memories into a session's context",
    "merge_wip": "how many merges may be in flight at once",
    "missing_issue_ref_policy": "what to do with a branch carrying no issue reference",
    "mode": "publishing posture: auto pushes without waiting, interactive asks first",
    "mr_conflict_scan_enabled": "scan open merge requests for conflicts, at the cost of a forge read each",
    "mr_reminder": "when and how often a stale review request is chased",
    "mr_state_questions_max_per_tick": "merge-request state questions that may be raised in one tick",
    "mr_title_regex": "regex a pull request title must match",
    "mr_triage_enabled": "run the merge-request triage ladder, which surfaces verdicts and never acts",
    "mr_triage_max_mrs_per_tick": "merge requests the triage ladder may assess in one tick",
    "no_self_reviewer_assign_gate_enabled": "refuse assigning the author as their own reviewer",
    "notify_on_post_on_behalf": "DM the operator a receipt after every post made under their identity",
    "notify_user_via_bot": "deliver notifications through the overlay bot rather than silently",
    "on_behalf_auto_actions": "actions the agent may take under the operator's identity unattended",
    "on_behalf_post_mode": "whether a colleague-visible post drafts, asks, or publishes immediately",
    "openai_compatible_base_url": "base URL of the OpenAI-compatible endpoint",
    "openai_compatible_credential_entry": "secret-store entry holding the OpenAI-compatible key",
    "openai_compatible_lane": "which work lane routes to the OpenAI-compatible endpoint",
    "openai_compatible_model": "model name requested from the OpenAI-compatible endpoint",
    "orchestrate_claim_enabled": "let the orchestrator claim work rather than only routing it",
    "orchestrator_bash_gate_enabled": "refuse heavy shell commands run directly by the orchestrator",
    "orchestrator_boundary_agent_gate_enabled": "refuse orchestrator work that belongs in a sub-agent",
    "orchestrator_investigation_gate_enabled": "refuse an orchestrator investigation that should be dispatched",
    "orchestrator_turn_budget": "output-token budget for one orchestrator turn",
    "orchestrator_turn_wall_clock_seconds": "seconds one orchestrator turn may take",
    "out_of_band_merge_gate_enabled": "refuse a merge that skipped the recorded review path",
    "outer_loop_enabled": "run the outer loop that measures and improves the factory itself",
    "outer_loop_max_per_week": "outer-loop runs allowed per week",
    "outer_loop_measure_days": "days of history the outer loop measures over",
    "outer_loop_stop_after_consecutive_failures": "consecutive failures that stop the outer loop",
    "overlay_leak_terms": "overlay-specific terms treated as private in a public artifact",
    "overlays": "per-overlay settings, keyed by overlay name",
    "park_attempt_retention_days": "days a parked attempt is kept before it is pruned",
    "plan_edit_gate_enabled": "refuse a source edit made while the session is still planning",
    "pr_review_backend": "which reviewer runs the self-authored-PR cold review; auto resolves per tick",
    "private_repos": "repos treated as private, where internal identifiers are allowed",
    "provision_fast_step_timeout_seconds": "seconds a step declared fast may take before it is failed",
    "provision_max_concurrency": "provisioning steps that may run at once",
    "provision_ram_ceiling_percent": "percent of RAM provisioning may consume before it backs off",
    "provision_slow_threshold_seconds": "seconds after which a provisioning step is reported as slow",
    "provision_step_timeout_seconds": "seconds an ordinary provisioning step may take",
    "pull_main_clone_cadence_hours": "hours between pulls of each main clone",
    "pull_main_clone_disabled": "stop pulling the main clones on a cadence",
    "pydantic_ai_max_tokens": "token ceiling for one pydantic-ai request",
    "pydantic_ai_request_limit": "requests one pydantic-ai run may make",
    "ram_crit_avail_gb": "available RAM below this many GB is critical",
    "ram_kill_allowlist": "processes the RAM reaper may kill under pressure",
    "ram_warn_avail_gb": "available RAM below this many GB warns",
    "regulated_path_model_allowlist": "models allowed to touch a regulated path",
    "repo_mode": "whether this box works on its own repos, colleagues' repos, or both",
    "require_anti_vacuity_attestation": "require proof a regression test was observed red before its fix",
    "require_debt_delta": "require a change to state whether it added or removed tech debt",
    "require_executed_repro": "require an executed reproduction before a bug fix is accepted",
    "require_human_approval_to_answer": "require the operator to approve an answer before it is posted",
    "require_human_approval_to_merge": "require a recorded human approver before a merge",
    "require_integration_review": "require an integration-level review beside the unit one",
    "require_merge_evidence": "require merge evidence to be recorded before the merge lands",
    "require_merge_quality_verdict": "require a quality verdict on the change before it merges",
    "require_plan_adequacy": "require the plan to be judged adequate before coding starts",
    "require_review_context": "require the reviewer to record what context they read",
    "require_reviewed_state_for_review_request": "require a reviewed ticket before a review is requested",
    "require_rubric_verification": "require the rubric to be verified rather than asserted",
    "require_spec_coverage": "require every spec deliverable to carry its own evidence",
    "require_work_group_batch": "refuse to broadcast one work-group member while a sibling is not review-ready",
    "resource_pressure_cadence_minutes": "minutes between resource-pressure checks",
    "resource_pressure_disabled": "stop checking resource pressure",
    "resource_pressure_min_free_interval_minutes": "minutes before the same pressure alarm may fire again",
    "review_backend_cooldown_hours": "hours a review backend stays parked after its account ran out of quota",
    "review_exempt_repos": "repos whose merge requests need no review request",
    "review_exempt_repos_count_toward_group_readiness": "let review-exempt merge requests still hold their work group",
    "review_nag_enabled": "chase a review request that has gone unanswered",
    "review_nag_max_interval_days": "ceiling on the review nag's widening re-ask interval",
    "review_pause_reaction_emojis": "Slack reaction names meaning a review request is deliberately paused",
    "review_request_dedup_max_pages": "pages of history searched for an existing review request",
    "review_request_dedup_window_days": "days a prior review request suppresses a duplicate",
    "review_request_post_disabled": "stop posting review requests",
    "review_resume_reply_enabled": "reply in-thread that a paused review request is ready again",
    "review_skill": "skill a review dispatch runs",
    "review_skill_alternates": "extra skills whose recorded run also satisfies the reviewing-phase evidence gate",
    "scanning_news_cadence_hours": "hours between news scans",
    "scanning_news_disabled": "stop scheduling news scans",
    "scanning_news_skill": "skill the news scanning loop runs",
    "schema_readiness_gate_enabled": "refuse work when the database schema is not migrated",
    "sdk_monthly_credit_usd": "monthly SDK credit the cost tracker measures spend against",
    "self_dm_gate_enabled": "classify a self-DM apart from a colleague post, so it is not gated",
    "scratch_retention_days": "days of agent scratch the sweep reclaims under the temp root; disabled by default",
    "scratch_sweep_root": "temp root the scratch sweep reclaims from (blank auto-resolves the host view)",
    "self_update_cadence_hours": "hours between self-update checks",
    "self_update_disabled": "stop self-updating",
    "send_proxy_allowlist": "destinations the send proxy may deliver to",
    "send_proxy_mode": "whether outbound messages go direct, through the proxy, or nowhere",
    "session_stale_after_hours": "hours after which a session with no heartbeat counts as stale",
    "single_branch_repo_gate_enabled": "refuse a second branch in a repo declared single-branch",
    "single_branch_repos": "repos that may carry only one branch at a time",
    "skill_loading_gate_enabled": "refuse a turn that skipped a skill the loader required",
    "slack_user_channel": "Slack channel the operator is DMed on",
    "slack_user_id": "the operator's Slack user id",
    "slack_voice_classifier_mode": "how a Slack message is classified as the operator's voice",
    "snapshot_baseline_gate_enabled": "refuse a snapshot diff taken against a stale baseline",
    "snapshot_warmer_disabled": "stop warming the snapshot caches",
    "snapshot_warmer_max_age_days": "days a warmed snapshot stays usable",
    "solo_repo_url_pattern": "regex matching repos the operator works on alone",
    "speak": "text-to-speech delivery, and which surfaces are spoken",
    "stale_stack_min_age_minutes": "minutes a stack must exist before staleness is judged",
    "standing_goal_stop_gate_enabled": "refuse ending a turn as done while a standing goal is unmet",
    "statusline_chain": "which statusline segments render, in order",
    "statusline_engaged_render": "render the statusline only while the session is engaged",
    "stop_snapshotter_enabled": "snapshot session findings before a stop, so context survives",
    "subagent_spawn_ceiling": "sub-agents one dispatch may spawn",
    "substrate_auto_merge_authorized_by": "who authorized substrate changes to auto-merge",
    "substrate_self_signoff": "let a substrate change be signed off by its own author",
    "target_branch": "long-lived integration branch every pull request targets instead of the repo default",
    "task_attempt_retention_days": "days a task attempt row is kept",
    "task_result_retention_days": "days a task result row is kept",
    "task_sweep_disabled": "stop sweeping abandoned tasks back into the queue",
    "task_sweep_recheck_interval_hours": "hours between rechecks of a swept task",
    "test_worker_ram_gb": "RAM one pytest worker is sized at when the governor caps test parallelism",
    "ticket_budget_max_cost_usd": "dollars one ticket may cost before it is halted",
    "ticket_transition_prune_disabled": "stop pruning old ticket transition rows",
    "timeouts": "per-operation timeout overrides, keyed by operation name",
    "triage_assessor_cadence_hours": "hours between triage assessor runs",
    "triage_assessor_enabled": "run the triage assessor over untriaged issues",
    "triage_assessor_max_issues_per_tick": "issues the triage assessor may assess in one tick",
    "trusted_issue_authors": "issue authors whose issues may be claimed without extra triage",
    "umbrella_issue_labels": "labels marking an issue as an umbrella/epic parent intake never claims",
    "unbacked_claim_gate_enabled": "refuse a diagnosis or an escalation that cites no artefact the agent read",
    "verbatim_paste_gate_enabled": "refuse a publish whose body reproduces the operator's own words verbatim",
    "unknown_repo_push_gate_enabled": "refuse a push to a repo teatree does not recognise",
    "user_identity_aliases": "other identities that are the same person as the operator",
    "watchdog_max_cost_usd": "dollars a watched run may spend before the watchdog stops it",
    "watchdog_max_runtime_seconds": "seconds a watched run may take before the watchdog stops it",
    "watchdog_max_turns": "turns a watched run may take before the watchdog stops it",
    "wip": "how much work may be in progress at once",
    "work_group_generic_scopes": "commit scopes too generic to group merge requests on",
    "work_group_max_members": "members above which a work group is surfaced as a question rather than held",
    "worker_quiescing": "stop claiming new work and let the running units finish",
    "workspace_dir": "directory new worktrees are created under",
    "worktree_stale_days": "days after which an untouched worktree counts as stale",
    "write_wip": "how many writing units may be in flight at once",
}


def setting_help(key: str) -> str:
    """*key*'s one-line explanation, or ``""`` for a key this table does not carry."""
    return SETTING_HELP.get(key, "")


__all__ = ["SETTING_HELP", "setting_help"]
