"""The position-anchored AI-signature matcher, in-process (the CLI is ``tests/test_ai_signature_scan_script.py``)."""

import pytest

from teatree.hooks.ai_signature_scan import scan_text, summary

_FOOTER = "\U0001f916 Generated with [Claude Code](https://claude.com/claude-code)"


@pytest.mark.parametrize(
    ("trailer", "category"),
    [
        (_FOOTER, "generated-with"),
        (
            "Co-Authored-By: Claude <noreply@anthropic.com>",  # privacy-scan:allow fake trailer fixture
            "co-authored-by-model",
        ),
        (
            "> Co-Authored-By: Claude <noreply@anthropic.com>",  # privacy-scan:allow fake trailer fixture
            "co-authored-by-model",
        ),
        ("- Generated with Claude", "generated-with"),
        ("(via AI)", "via-agent"),
        ("This PR was generated by a bot", "written-by-agent"),
    ],
)
def test_a_trailer_in_footer_position_is_a_finding(trailer: str, category: str) -> None:
    assert scan_text(f"Tidy the widget\n\nTidies it.\n\n{trailer}") == [(5, category, trailer)]


@pytest.mark.parametrize(
    "body",
    [
        "",
        "Tidies it.\n\nCo-authored-by: Jane Doe <jane@example.com>",
        f"Refuses a body ending in `{_FOOTER}`.",
        "Reviewed the design with Claude before shipping.",
    ],
)
def test_prose_and_human_trailers_are_not_findings(body: str) -> None:
    assert scan_text(body) == []


def test_the_summary_names_each_finding_or_reports_clean() -> None:
    assert summary([]) == "AI-signature scan: clean (0 findings)"
    assert summary([(3, "generated-with", _FOOTER)]) == (
        f"AI-signature scan: 1 banned trailer(s)\n  line 3: generated-with: {_FOOTER}"
    )
