"""The pre-destruction hook quarantine: durability before destruction, report read from the world.

Every disposition below is asserted on the FILESYSTEM after a modelled ``prek install -f``
(measured on prek 0.4.11: it unlinks ``<name>`` and ``<name>.legacy`` for each type it
installs, then writes a fresh shim at ``<name>``), never on the capture record — the record
is the carried channel this whole mechanism exists to stop relying on.
"""

import logging
import stat
from pathlib import Path
from unittest.mock import patch

import pytest

from teatree.cli.setup import git_hooks_installer
from teatree.core import hook_quarantine, prek_hook
from teatree.core.gates.git_hooks_preflight import format_remediation, probe_git_hooks
from teatree.core.runners import worktree_provision
from teatree.utils.git_worktree_query import git_common_dir
from tests._git_repo import make_git_repo, run_git

_OPERATOR_GATE = b"#!/bin/sh\n# the operator's own pre-push gate\nexit 0\n"
_SECOND_GATE = b"#!/bin/sh\n# a second, distinct operator gate\nexit 1\n"
_PREK_SHIM = b'#!/bin/sh\n# File generated by prek: https://github.com/j178/prek\nexec prek hook-impl -- "$@"\n'


def _plant(hooks: Path, name: str, blob: bytes | None) -> None:
    if blob is None:
        return
    hook = hooks / name
    hook.write_bytes(blob)
    hook.chmod(0o755)


def _dirs(tmp_path: Path) -> tuple[Path, Path]:
    common = tmp_path / "git-common"
    hooks = common / "hooks"
    hooks.mkdir(parents=True)
    return hooks, common


def _install_dash_f(hooks: Path, name: str) -> None:
    """What ``prek install -f`` does to one installed type — both slots reaped, a fresh shim written."""
    (hooks / name).unlink(missing_ok=True)
    (hooks / f"{name}.legacy").unlink(missing_ok=True)
    _plant(hooks, name, _PREK_SHIM)


def _captured(hooks: Path, common: Path, name: str = "pre-push") -> hook_quarantine.Quarantine:
    quarantine = hook_quarantine.Quarantine(hooks, common)
    quarantine.capture([name])
    quarantine.park()
    return quarantine


class TestTheMarkerIsTheSameOneTheInstallerClassifiesOn:
    def test_the_byte_marker_equals_prek_hooks_text_marker(self) -> None:
        assert prek_hook._PREK_MARKER.encode() == hook_quarantine._PREK_MARKER


class TestPendingIsThreeValued:
    """A read failure reading as ``()`` is the silent-empty every consumer would take as "nothing lost"."""

    def test_a_missing_directory_is_nothing_parked(self, tmp_path: Path) -> None:
        assert hook_quarantine.pending(tmp_path) == ()

    def test_a_parked_hook_is_listed(self, tmp_path: Path) -> None:
        parked = hook_quarantine.quarantine_dir(tmp_path)
        parked.mkdir()
        (parked / "pre-push").write_bytes(_OPERATOR_GATE)

        assert hook_quarantine.pending(tmp_path) == (parked / "pre-push",)

    def test_an_unreadable_directory_is_none_never_empty(self, tmp_path: Path) -> None:
        hook_quarantine.quarantine_dir(tmp_path).mkdir()

        def _refuse(self: Path) -> None:
            raise PermissionError(13, "Permission denied", str(self))

        with patch.object(Path, "iterdir", _refuse):
            assert hook_quarantine.pending(tmp_path) is None


class TestTheDispositionOfEverySlotCombination:
    """Which slot is put back, which stays parked, and which is neither — decided per name.

    A foreign ``<name>`` is run by git itself, so the ``.legacy`` beside it is dark; a prek
    shim at ``<name>`` dispatches ``<name>.legacy`` at hook time, so THAT file is the gate;
    and with ``<name>`` absent the ``.legacy`` is an orphan nothing dispatches — restoring it
    would make dormant code run on every push, deleting it would lose the operator's bytes,
    so it is parked and reported.
    """

    @pytest.mark.parametrize(
        ("live", "legacy", "restored", "still_parked"),
        [
            pytest.param(_OPERATOR_GATE, None, _OPERATOR_GATE, (), id="a-foreign-live-hook-is-the-gate"),
            pytest.param(
                _OPERATOR_GATE,
                _SECOND_GATE,
                _OPERATOR_GATE,
                ("pre-push.legacy",),
                id="a-dark-legacy-is-parked-beside-the-restored-live-gate",
            ),
            pytest.param(_PREK_SHIM, _OPERATOR_GATE, _OPERATOR_GATE, (), id="a-shim-dispatches-its-legacy-gate"),
            pytest.param(_PREK_SHIM, _PREK_SHIM, None, (), id="preks-own-debris-is-not-operator-state"),
            pytest.param(_PREK_SHIM, None, None, (), id="a-plain-shim-puts-nothing-at-risk"),
            pytest.param(
                None, _OPERATOR_GATE, None, ("pre-push.legacy",), id="an-orphan-legacy-is-parked-never-activated"
            ),
        ],
    )
    def test_the_slot_prek_dispatches_is_restored_and_nothing_else_is(
        self,
        tmp_path: Path,
        live: bytes | None,
        legacy: bytes | None,
        restored: bytes | None,
        still_parked: tuple[str, ...],
    ) -> None:
        hooks, common = _dirs(tmp_path)
        _plant(hooks, "pre-push", live)
        _plant(hooks, "pre-push.legacy", legacy)
        quarantine = _captured(hooks, common)

        _install_dash_f(hooks, "pre-push")
        quarantine.reinstate()

        dispatched = hooks / "pre-push.legacy"
        assert (dispatched.read_bytes() if dispatched.exists() else None) == restored
        assert hook_quarantine.pending(common) == tuple(
            hook_quarantine.quarantine_dir(common) / name for name in still_parked
        )


class TestNothingDestroyedLeavesNothingParked:
    """The control on the whole mechanism: a run that touched nothing must not leave a permanent WARN."""

    def test_an_install_that_destroyed_nothing_clears_the_quarantine(self, tmp_path: Path) -> None:
        hooks, common = _dirs(tmp_path)
        _plant(hooks, "pre-push", _OPERATOR_GATE)
        quarantine = _captured(hooks, common)
        assert hook_quarantine.pending(common), "the fixture never parked anything"

        quarantine.reinstate()

        assert hook_quarantine.pending(common) == ()
        assert (hooks / "pre-push").read_bytes() == _OPERATOR_GATE
        assert not (hooks / "pre-push.legacy").exists()


class TestTheReinstateHandlerIsExactlyOSError:
    """Widening it swallows a real bug in the ``finally``; narrowing it turns a full disk into a raise.

    Neither half pins it alone — (a) is the ceiling, (b) is the floor.
    """

    def test_a_non_oserror_from_a_reinstate_propagates(self, tmp_path: Path) -> None:
        hooks, common = _dirs(tmp_path)
        _plant(hooks, "pre-push", _OPERATOR_GATE)
        quarantine = _captured(hooks, common)

        not_an_oserror = ValueError("a bug in the reinstate, not a filesystem refusal")

        def _explode(_path: Path, _blob: bytes) -> bool:
            raise not_an_oserror

        with (
            patch.object(hook_quarantine, "_still_holds", _explode),
            pytest.raises(ValueError, match="not a filesystem refusal"),
        ):
            quarantine.reinstate()

    def test_a_reinstate_that_does_not_raise_returns_and_clears_the_entry(self, tmp_path: Path) -> None:
        """The control for (a): an always-raising reinstate would satisfy it without pinning anything."""
        hooks, common = _dirs(tmp_path)
        _plant(hooks, "pre-push", _OPERATOR_GATE)
        quarantine = _captured(hooks, common)

        quarantine.reinstate()

        assert hook_quarantine.pending(common) == ()

    def test_an_unwritable_destination_leaves_the_bytes_parked_and_does_not_raise(self, tmp_path: Path) -> None:
        hooks, common = _dirs(tmp_path)
        _plant(hooks, "pre-push", _OPERATOR_GATE)
        quarantine = _captured(hooks, common)
        _install_dash_f(hooks, "pre-push")

        def _refuse(self: Path, _blob: bytes) -> int:
            raise OSError(30, "Read-only file system", str(self))

        with patch.object(Path, "write_bytes", _refuse):
            quarantine.reinstate()

        assert hook_quarantine.pending(common) == (hook_quarantine.quarantine_dir(common) / "pre-push",)
        assert (hook_quarantine.quarantine_dir(common) / "pre-push").read_bytes() == _OPERATOR_GATE


class TestTheParkNeverOverwritesAnEarlierRunsCopy:
    def test_a_differing_parked_copy_refuses_the_park(self, tmp_path: Path) -> None:
        hooks, common = _dirs(tmp_path)
        parked = hook_quarantine.quarantine_dir(common)
        parked.mkdir(parents=True)
        (parked / "pre-push").write_bytes(_SECOND_GATE)
        _plant(hooks, "pre-push", _OPERATOR_GATE)
        quarantine = hook_quarantine.Quarantine(hooks, common)
        quarantine.capture(["pre-push"])

        with pytest.raises(hook_quarantine.HookCaptureError, match=str(parked / "pre-push")):
            quarantine.park()

        assert (parked / "pre-push").read_bytes() == _SECOND_GATE
        assert (hooks / "pre-push").read_bytes() == _OPERATOR_GATE

    def test_an_identical_parked_copy_is_a_no_op(self, tmp_path: Path) -> None:
        """The control: refusing whenever the file exists breaks every re-run of `t3 setup`."""
        hooks, common = _dirs(tmp_path)
        parked = hook_quarantine.quarantine_dir(common)
        parked.mkdir(parents=True)
        (parked / "pre-push").write_bytes(_OPERATOR_GATE)
        _plant(hooks, "pre-push", _OPERATOR_GATE)
        quarantine = hook_quarantine.Quarantine(hooks, common)
        quarantine.capture(["pre-push"])

        quarantine.park()

        assert (parked / "pre-push").read_bytes() == _OPERATOR_GATE


class TestAnUnreadableHookAbortsTheCapture:
    def test_capture_raises_rather_than_skipping_a_hook_it_cannot_read(self, tmp_path: Path) -> None:
        hooks, common = _dirs(tmp_path)
        _plant(hooks, "pre-push", _OPERATOR_GATE)
        quarantine = hook_quarantine.Quarantine(hooks, common)

        def _refuse(self: Path) -> bytes:
            raise PermissionError(13, "Permission denied", str(self))

        with (
            patch.object(Path, "read_bytes", _refuse),
            pytest.raises(hook_quarantine.HookCaptureError, match="pre-push"),
        ):
            quarantine.capture(["pre-push"])


class TestTheParkedCopyKeepsTheOriginalMode:
    def test_the_execute_bit_survives_the_round_trip(self, tmp_path: Path) -> None:
        hooks, common = _dirs(tmp_path)
        _plant(hooks, "pre-push", _OPERATOR_GATE)
        (hooks / "pre-push").chmod(0o700)
        quarantine = _captured(hooks, common)
        _install_dash_f(hooks, "pre-push")

        quarantine.reinstate()

        assert stat.S_IMODE((hooks / "pre-push.legacy").stat().st_mode) == 0o700


class TestTheParkRefusesWhatItCannotMakeDurable:
    """Every ``HookCaptureError`` here is the durability-precedes-destruction property itself."""

    def test_a_quarantine_dir_that_cannot_be_created_refuses_the_install(self, tmp_path: Path) -> None:
        hooks, common = _dirs(tmp_path)
        hook_quarantine.quarantine_dir(common).write_bytes(b"a regular file where the dir belongs")
        _plant(hooks, "pre-push", _OPERATOR_GATE)
        quarantine = hook_quarantine.Quarantine(hooks, common)
        quarantine.capture(["pre-push"])

        with pytest.raises(hook_quarantine.HookCaptureError, match=str(hook_quarantine.quarantine_dir(common))):
            quarantine.park()

        assert (hooks / "pre-push").read_bytes() == _OPERATOR_GATE

    def test_a_writable_git_dir_parks_the_hook_with_its_mode(self, tmp_path: Path) -> None:
        """The control: a park that refuses unconditionally passes the test above."""
        hooks, common = _dirs(tmp_path)
        _plant(hooks, "pre-push", _OPERATOR_GATE)
        (hooks / "pre-push").chmod(0o700)
        quarantine = hook_quarantine.Quarantine(hooks, common)
        quarantine.capture(["pre-push"])

        quarantine.park()

        parked = hook_quarantine.quarantine_dir(common) / "pre-push"
        assert parked.read_bytes() == _OPERATOR_GATE
        assert stat.S_IMODE(parked.stat().st_mode) == 0o700

    def test_an_unreadable_already_parked_copy_refuses_the_install(self, tmp_path: Path) -> None:
        """An unreadable parked copy is not an absent one — overwriting it would lose bytes."""
        hooks, common = _dirs(tmp_path)
        (hook_quarantine.quarantine_dir(common) / "pre-push").mkdir(parents=True)
        _plant(hooks, "pre-push", _OPERATOR_GATE)
        quarantine = hook_quarantine.Quarantine(hooks, common)
        quarantine.capture(["pre-push"])

        with pytest.raises(hook_quarantine.HookCaptureError, match="already-parked"):
            quarantine.park()

        assert (hooks / "pre-push").read_bytes() == _OPERATOR_GATE


def _finding(repo: Path) -> str:
    probe = probe_git_hooks(repo)
    finding = hook_quarantine.parked_finding(probe.parked, probe.common_dir)
    assert finding is not None, "the fixture produced no finding to compare the surfaces on"
    return finding


def _park_beside(repo: Path, name: str) -> Path:
    parked = hook_quarantine.quarantine_dir(git_common_dir(repo))
    parked.mkdir(parents=True, exist_ok=True)
    (parked / name).write_bytes(_OPERATOR_GATE)
    return parked / name


class TestTheThreeSurfacesSayTheSameThing:
    """One sentence, three consumers — three inlined wordings is how they used to disagree."""

    def test_installer_doctor_and_provisioning_all_carry_the_same_sentence(
        self, tmp_path: Path, caplog: pytest.LogCaptureFixture
    ) -> None:
        repo = make_git_repo(tmp_path / "repo")
        _park_beside(repo, "pre-push")
        finding = _finding(repo)

        installer = git_hooks_installer._qualified(
            probe_git_hooks(repo), git_hooks_installer._HookLine("OK", "already installed")
        )
        doctor = format_remediation(probe_git_hooks(repo))
        with caplog.at_level(logging.WARNING, logger=worktree_provision.__name__):
            worktree_provision._warn_on_parked_hooks(str(repo))

        assert finding in installer.text, installer
        assert any(finding in line for line in doctor), doctor
        assert finding in caplog.text

    def test_the_sentence_names_the_quarantine_directory_it_could_not_read(self, tmp_path: Path) -> None:
        repo = make_git_repo(tmp_path / "repo")
        quarantine = hook_quarantine.quarantine_dir(git_common_dir(repo))
        quarantine.mkdir(parents=True)

        def _refuse(self: Path) -> None:
            raise PermissionError(13, "Permission denied", str(self))

        with patch.object(Path, "iterdir", _refuse):
            finding = _finding(repo)

        assert str(quarantine) in finding

    def test_the_restore_dir_is_the_default_hooks_dir_not_a_custom_hooks_path(self, tmp_path: Path) -> None:
        """A parked hook came from ``<common>/hooks``, whatever ``core.hooksPath`` now points at."""
        repo = make_git_repo(tmp_path / "repo")
        custom = tmp_path / "elsewhere"
        custom.mkdir()
        run_git(repo, "config", "core.hooksPath", str(custom))
        _park_beside(repo, "pre-push")

        finding = _finding(repo)

        assert str(git_common_dir(repo) / "hooks") in finding
        assert str(custom) not in finding


class TestParkedFindingOverItsWholeDomain:
    """One sentence per state the probe can be in, and silence for the two holding nothing to say."""

    def test_an_unread_quarantine_names_its_path_when_the_clone_resolved(self, tmp_path: Path) -> None:
        finding = hook_quarantine.parked_finding(None, tmp_path)

        assert finding is not None
        assert str(hook_quarantine.quarantine_dir(tmp_path)) in finding

    def test_an_unread_quarantine_names_the_directory_when_the_clone_did_not(self) -> None:
        finding = hook_quarantine.parked_finding(None, None)

        assert finding is not None
        assert hook_quarantine.QUARANTINE_DIRNAME in finding

    def test_an_empty_quarantine_is_silent(self, tmp_path: Path) -> None:
        assert hook_quarantine.parked_finding((), tmp_path) is None

    def test_a_listing_with_no_clone_to_restore_into_is_silent(self) -> None:
        """There is no restore dir to name, so the listing has nothing actionable to say."""
        assert hook_quarantine.parked_finding((Path("/nowhere/pre-push"),), None) is None

    def test_a_parked_hook_names_every_path_and_the_default_hooks_dir(self, tmp_path: Path) -> None:
        parked = hook_quarantine.quarantine_dir(tmp_path) / "pre-push"

        finding = hook_quarantine.parked_finding((parked,), tmp_path)

        assert finding is not None
        assert str(parked) in finding
        assert str(tmp_path / "hooks") in finding
