"""Both write seams — ORM and Django-free — regenerate the projection, and nothing else does.

"Regenerated by the same seam that writes those settings" is the property that makes the
projection trustworthy without a timer. A timer is how a projection silently goes stale,
so the test that matters is that a WRITE moves the generation and a mere read does not.
"""

import json
import sqlite3
from pathlib import Path

import pytest
from django.db.models.signals import post_delete, post_save

from teatree.config import cold_db, cold_writer
from teatree.config.host_projection import GENERATION_KEY, GLOBAL_SCOPE, ProjectionReader
from teatree.core import projection_signals
from teatree.core.models.config_setting import ConfigSetting
from teatree.core.models.loop_preset import Mode, ModeOverride
from teatree.core.models.loop_schedule import ModeSchedule, ModeScheduleSlot
from teatree.core.models.loop_state import LoopState

_SCHEMA = """
CREATE TABLE teatree_config_setting (
    id INTEGER PRIMARY KEY,
    scope TEXT NOT NULL,
    key TEXT NOT NULL,
    value TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE (scope, key)
);
CREATE TABLE teatree_loop_state (id INTEGER PRIMARY KEY, name TEXT NOT NULL UNIQUE, status TEXT NOT NULL);
"""


@pytest.fixture
def canonical(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> tuple[Path, Path]:
    """A file-backed control DB in a 'volume' dir, projecting into a separate 'data' dir."""
    volume, data_dir = tmp_path / "control-db", tmp_path / "data"
    volume.mkdir()
    data_dir.mkdir()
    db = volume / "db.sqlite3"
    conn = sqlite3.connect(db)
    try:
        conn.executescript(_SCHEMA)
        conn.commit()
    finally:
        conn.close()
    monkeypatch.setattr(cold_db, "canonical_config_db", lambda **_: db)
    monkeypatch.setattr(cold_db, "canonical_data_dir", lambda **_: data_dir)
    monkeypatch.setattr(cold_writer, "canonical_config_db", lambda **_: db)
    return db, data_dir


def _generation(db: Path) -> object:
    conn = sqlite3.connect(db)
    try:
        row = conn.execute(
            "SELECT value FROM teatree_config_setting WHERE scope=? AND key=?",
            (GLOBAL_SCOPE, GENERATION_KEY),
        ).fetchone()
    finally:
        conn.close()
    return json.loads(row[0]) if row else None


class TestTheColdWriteSeamRepublishes:
    def test_a_setting_write_publishes_a_projection_the_hooks_can_read(self, canonical: tuple[Path, Path]) -> None:
        _, data_dir = canonical
        assert not (data_dir / "host-projection.json").exists(), "control: nothing published before the write"

        cold_writer.write_setting("memory_recall_enabled", value=False)

        published = ProjectionReader(data_dir).read().projection
        assert published is not None
        assert published.setting("memory_recall_enabled") is False

    def test_each_write_ratchets_the_generation_in_the_source(self, canonical: tuple[Path, Path]) -> None:
        db, data_dir = canonical

        cold_writer.write_setting("autoload", value=True)
        first = _generation(db)
        cold_writer.write_setting("autoload", value=False)

        assert first == 1
        assert _generation(db) == 2
        assert ProjectionReader(data_dir).read().projection.generation == 2

    def test_a_read_does_not_move_the_generation(self, canonical: tuple[Path, Path]) -> None:
        db, _ = canonical
        cold_writer.write_setting("autoload", value=True)
        before = _generation(db)

        assert cold_db.canonical_projection() is not None
        assert _generation(db) == before, "only a write regenerates; a timer or a read must not"


class TestTheOrmSeamIsWiredAndScoped:
    def test_the_receivers_are_registered_on_every_projected_model(self) -> None:
        for signal in (post_save, post_delete):
            for model in (ConfigSetting, LoopState, Mode, ModeOverride, ModeSchedule, ModeScheduleSlot):
                assert signal.has_listeners(model), f"{model.__name__} writes would leave the projection stale"

    def test_an_in_memory_database_is_not_projected(self) -> None:
        # The test suite runs on `:memory:`. There is no host side to project to and no
        # second connection can read it, so the seam must be inapplicable rather than
        # noisily failing on every config write in the suite.
        assert not projection_signals.projects_to_a_host()

    def test_a_file_backed_database_is_projected(
        self, canonical: tuple[Path, Path], monkeypatch: pytest.MonkeyPatch
    ) -> None:
        db, _ = canonical
        monkeypatch.setattr(projection_signals, "control_db_path", lambda: db)

        assert projection_signals.projects_to_a_host()
