# Generated by Django 6.0.4 on 2026-05-04 10:05

import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("overlay", models.CharField(max_length=255)),
                ("visited_phases", models.JSONField(blank=True, default=list)),
                ("phase_visits", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("agent_id", models.CharField(blank=True, max_length=255)),
                ("repos_modified", models.JSONField(blank=True, default=list)),
                ("repos_tested", models.JSONField(blank=True, default=list)),
            ],
            options={
                "db_table": "teatree_session",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phase", models.CharField(blank=True, max_length=64)),
                (
                    "execution_target",
                    models.CharField(
                        choices=[("headless", "Headless"), ("interactive", "Interactive")],
                        default="headless",
                        max_length=32,
                    ),
                ),
                ("execution_reason", models.TextField(blank=True)),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("pending", "Pending"),
                            ("claimed", "Claimed"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("claimed_by", models.CharField(blank=True, max_length=255)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("result_artifact_path", models.CharField(blank=True, max_length=500)),
                (
                    "parent_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_tasks",
                        to="core.task",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tasks", to="core.session"
                    ),
                ),
            ],
            options={
                "db_table": "teatree_task",
            },
        ),
        migrations.CreateModel(
            name="TaskAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "execution_target",
                    models.CharField(choices=[("headless", "Headless"), ("interactive", "Interactive")], max_length=32),
                ),
                ("error", models.TextField(blank=True)),
                ("exit_code", models.IntegerField(blank=True, null=True)),
                ("artifact_path", models.CharField(blank=True, max_length=500)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("input_tokens", models.IntegerField(blank=True, null=True)),
                ("output_tokens", models.IntegerField(blank=True, null=True)),
                ("cost_usd", models.FloatField(blank=True, null=True)),
                ("num_turns", models.IntegerField(blank=True, null=True)),
                ("launch_url", models.URLField(blank=True, max_length=500)),
                ("agent_session_id", models.CharField(blank=True, max_length=255)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="attempts", to="core.task"
                    ),
                ),
            ],
            options={
                "db_table": "teatree_taskattempt",
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("overlay", models.CharField(max_length=255)),
                ("issue_url", models.URLField(blank=True, max_length=500)),
                ("variant", models.CharField(blank=True, max_length=100)),
                ("repos", models.JSONField(blank=True, default=list)),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("not_started", "Not started"),
                            ("scoped", "Scoped"),
                            ("started", "Started"),
                            ("coded", "Coded"),
                            ("tested", "Tested"),
                            ("reviewed", "Reviewed"),
                            ("shipped", "Shipped"),
                            ("in_review", "In review"),
                            ("merged", "Merged"),
                            ("retrospected", "Retrospected"),
                            ("delivered", "Delivered"),
                            ("ignored", "Ignored"),
                        ],
                        default="not_started",
                        max_length=32,
                    ),
                ),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("redis_db_index", models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                "db_table": "teatree_ticket",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("issue_url", ""), _negated=True),
                        fields=("issue_url",),
                        name="unique_nonempty_issue_url",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="task",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="tasks", to="core.ticket"
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="sessions", to="core.ticket"
            ),
        ),
        migrations.CreateModel(
            name="TicketTransition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("from_state", models.CharField(max_length=32)),
                ("to_state", models.CharField(max_length=32)),
                ("triggered_by", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transitions",
                        to="core.session",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="transitions", to="core.ticket"
                    ),
                ),
            ],
            options={
                "db_table": "teatree_tickettransition",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Worktree",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("overlay", models.CharField(max_length=255)),
                (
                    "repo_path",
                    models.CharField(
                        help_text="Repo identifier (e.g. 'org/repo' or a short slug) — NOT a filesystem path. The on-disk worktree path lives in extra['worktree_path'].",
                        max_length=500,
                    ),
                ),
                ("branch", models.CharField(max_length=255)),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("created", "Created"),
                            ("provisioned", "Provisioned"),
                            ("services_up", "Services up"),
                            ("ready", "Ready"),
                        ],
                        default="created",
                        max_length=32,
                    ),
                ),
                ("db_name", models.CharField(blank=True, max_length=255)),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="worktrees", to="core.ticket"
                    ),
                ),
            ],
            options={
                "db_table": "teatree_worktree",
            },
        ),
        migrations.CreateModel(
            name="MergeRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("overlay", models.CharField(blank=True, max_length=255)),
                ("url", models.URLField(max_length=500)),
                ("repo", models.CharField(max_length=255)),
                ("iid", models.CharField(max_length=50)),
                ("slack_url", models.URLField(blank=True, max_length=500)),
                ("review_requested_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("open", "Open"),
                            ("review_requested", "Review requested"),
                            ("approved", "Approved"),
                            ("merged", "Merged"),
                        ],
                        default="open",
                        max_length=32,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="merge_requests", to="core.ticket"
                    ),
                ),
            ],
            options={
                "db_table": "teatree_merge_request",
                "constraints": [models.UniqueConstraint(fields=("url",), name="unique_merge_request_url")],
            },
        ),
        migrations.CreateModel(
            name="WorktreeEnvOverride",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=255)),
                ("value", models.TextField(blank=True)),
                (
                    "worktree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="env_overrides", to="core.worktree"
                    ),
                ),
            ],
            options={
                "db_table": "teatree_worktree_env_override",
                "constraints": [models.UniqueConstraint(fields=("worktree", "key"), name="uniq_worktree_env_key")],
            },
        ),
    ]
