# Generated by Django 6.0.3 on 2026-04-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="repos_modified",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="session",
            name="repos_tested",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
