# Generated by Django 6.0.6 on 2026-06-24 04:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskattempt",
            name="error_fingerprint",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="taskattempt",
            name="iteration",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
