# Generated by Django 6.0.6 on 2026-07-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="implementedissuemarker",
            name="claimed_by_instance",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
