# Generated by Django 6.0.3 on 2026-03-21 02:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="execution_target",
            field=models.CharField(
                choices=[("headless", "Headless"), ("interactive", "Interactive")], default="headless", max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="taskattempt",
            name="execution_target",
            field=models.CharField(choices=[("headless", "Headless"), ("interactive", "Interactive")], max_length=32),
        ),
    ]
