# Generated by Django 6.0.6 on 2026-06-24 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_taskattempt_error_fingerprint_taskattempt_iteration"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstructionComplianceSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("instructions_observed", models.PositiveIntegerField(default=0)),
                ("violations", models.PositiveIntegerField(default=0)),
                ("recurrences_count", models.PositiveIntegerField(default=0)),
                ("compliance_rate", models.FloatField(default=1.0)),
                ("overlay", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "teatree_instruction_compliance_snapshot",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InstructionComplianceRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "rule_source",
                    models.CharField(
                        choices=[
                            ("memory", "Durable memory"),
                            ("skill", "Loaded-skill rule"),
                            ("claude_md", "CLAUDE.md clause"),
                            ("gate", "System gate"),
                            ("in_session", "Explicit in-session user directive"),
                        ],
                        max_length=16,
                    ),
                ),
                ("rule_identity", models.CharField(max_length=512)),
                ("evidence", models.TextField(blank=True, default="")),
                ("is_recurrence", models.BooleanField(default=False)),
                (
                    "remediation",
                    models.CharField(
                        choices=[
                            ("none", "Not yet remediated"),
                            ("memory", "Wrote another memory (forbidden for a recurrence)"),
                            ("escalation", "Filed a gate/eval enforcement ticket"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                ("escalation_url", models.CharField(blank=True, default="", max_length=512)),
                ("overlay", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="core.instructioncompliancesnapshot",
                    ),
                ),
            ],
            options={
                "db_table": "teatree_instruction_compliance_record",
                "ordering": ["-created_at"],
            },
        ),
    ]
