# Generated by Django 6.0.7 on 2026-07-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_implementedissuemarker_claimed_by_instance"),
    ]

    operations = [
        migrations.AddField(
            model_name="implementedissuemarker",
            name="claim_ref_sha",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
