# Generated by Django 6.0.5 on 2026-05-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_rename_merge_request_to_pull_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="role",
            field=models.CharField(
                choices=[("author", "Author"), ("reviewer", "Reviewer")], default="author", max_length=16
            ),
        ),
    ]
