# Generated by Django 6.0.3 on 2026-03-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_rename_execution_target_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskattempt",
            name="agent_session_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
