# Generated by Django 6.0.6 on 2026-06-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_instructioncompliancesnapshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="subject",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
