# Generated by Django 6.0.3 on 2026-04-02 15:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_ticket_transition"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="worktree",
            name="ports",
        ),
    ]
