# Generated by Django 6.0.5 on 2026-05-15 05:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_ticket_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncomingEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("slack", "Slack"),
                            ("gitlab", "GitLab"),
                            ("github", "GitHub"),
                            ("notion", "Notion"),
                            ("ci", "CI"),
                        ],
                        max_length=16,
                    ),
                ),
                ("actor", models.CharField(blank=True, max_length=255)),
                ("channel_ref", models.CharField(blank=True, max_length=255)),
                ("thread_ref", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField(blank=True)),
                ("payload_json", models.JSONField(blank=True, default=dict)),
                ("received_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "teatree_incoming_event",
                "ordering": ["-received_at"],
                "indexes": [
                    models.Index(fields=["source", "received_at"], name="teatree_inc_source_203a1a_idx"),
                    models.Index(fields=["processed_at"], name="teatree_inc_process_8931a8_idx"),
                ],
            },
        ),
    ]
