# Generated by Django 6.0.7 on 2026-07-11 09:20

from django.db import migrations, models


def _backfill_outcome(apps, schema_editor):
    """Stamp the new discriminator on existing rows from their exit_code + error (#16).

    Mirrors ``TaskAttempt._classify_outcome`` so a row recorded before this field
    existed reads the same first-class outcome the S5 signal now keys on: a clean
    ``exit_code == 0`` with no error is a success, ``exit_code == 0`` with an error
    is an envelope refusal, any non-zero exit is a crash, and a ``None`` exit_code
    (an attempt still in flight) stays blank.
    """
    TaskAttempt = apps.get_model("core", "TaskAttempt")
    db_alias = schema_editor.connection.alias
    rows = TaskAttempt.objects.using(db_alias)
    rows.filter(exit_code=0, error="").update(outcome="success")
    rows.filter(exit_code=0).exclude(error="").update(outcome="refusal")
    rows.filter(exit_code__isnull=False).exclude(exit_code=0).update(outcome="crash")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_ticket_issue_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskattempt",
            name="outcome",
            field=models.CharField(
                blank=True,
                choices=[("success", "Success"), ("refusal", "Refusal"), ("crash", "Crash")],
                default="",
                max_length=16,
            ),
        ),
        migrations.RunPython(_backfill_outcome, migrations.RunPython.noop),
    ]
