# Generated by Django 6.0.3 on 2026-04-08 13:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_worktree_ports"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="session",
            table="teatree_session",
        ),
        migrations.AlterModelTable(
            name="task",
            table="teatree_task",
        ),
        migrations.AlterModelTable(
            name="taskattempt",
            table="teatree_taskattempt",
        ),
        migrations.AlterModelTable(
            name="ticket",
            table="teatree_ticket",
        ),
        migrations.AlterModelTable(
            name="tickettransition",
            table="teatree_tickettransition",
        ),
        migrations.AlterModelTable(
            name="worktree",
            table="teatree_worktree",
        ),
    ]
