# Generated by Django 6.0.5 on 2026-05-15 06:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_add_incoming_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntentClassification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "intent",
                    models.CharField(
                        choices=[
                            ("task", "Task"),
                            ("question", "Question"),
                            ("approval", "Approval"),
                            ("status_update", "Status update"),
                            ("escalation", "Escalation"),
                            ("noise", "Noise"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ]
                    ),
                ),
                ("rationale", models.CharField(blank=True, max_length=255)),
                ("classified_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classified_as",
                        to="core.incomingevent",
                    ),
                ),
            ],
            options={
                "db_table": "teatree_intent_classification",
                "ordering": ["-classified_at"],
                "indexes": [models.Index(fields=["intent", "classified_at"], name="teatree_int_intent_d217d6_idx")],
            },
        ),
    ]
