# Generated by Django 6.0.7 on 2026-07-11 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_taskattempt_outcome"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoopPreset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.SlugField(max_length=64, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("entries", models.JSONField(default=dict)),
                ("availability_mode", models.CharField(blank=True, default="", max_length=32)),
                ("overlay_scope", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "teatree_loop_preset",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LoopPresetOverride",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("preset_name", models.CharField(max_length=64)),
                ("until", models.DateTimeField(blank=True, null=True)),
                ("reason", models.TextField(blank=True, default="")),
                ("set_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "teatree_loop_preset_override",
                "ordering": ["-set_at"],
            },
        ),
        migrations.CreateModel(
            name="LoopSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.SlugField(max_length=64, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("timezone", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "teatree_loop_schedule",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LoopScheduleSlot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("days", models.JSONField()),
                ("start_time", models.TimeField()),
                ("preset_name", models.CharField(max_length=64)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="slots", to="core.loopschedule"
                    ),
                ),
            ],
            options={
                "db_table": "teatree_loop_schedule_slot",
                "ordering": ["start_time"],
            },
        ),
    ]
