# Generated by Django 6.0.5 on 2026-05-15 06:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_add_intent_classification"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReplyDispatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("target_ref", models.CharField(max_length=255)),
                ("action_name", models.CharField(max_length=64)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("sent", "Sent"), ("failed", "Failed")],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("dispatched_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="dispatches", to="core.incomingevent"
                    ),
                ),
            ],
            options={
                "db_table": "teatree_reply_dispatch",
                "ordering": ["-dispatched_at"],
                "indexes": [models.Index(fields=["status", "dispatched_at"], name="teatree_rep_status_47afee_idx")],
            },
        ),
    ]
