# Generated by Django 6.0.3 on 2026-04-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_session_table_alter_task_table_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="phase_visits",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
