# Generated by Django 6.0.3 on 2026-03-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_ticket_unique_nonempty_issue_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskattempt",
            name="cost_usd",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskattempt",
            name="input_tokens",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskattempt",
            name="num_turns",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskattempt",
            name="output_tokens",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
