# Generated by Django 6.0.6 on 2026-06-27 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_delete_miniloopmarker"),
    ]

    operations = [
        migrations.AddField(
            model_name="deferredquestion",
            name="parked_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deferred_questions",
                to="core.task",
            ),
        ),
    ]
