# Generated by Django 6.1.1 on 2026-10-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_model_verbose_name_plurals"),
    ]

    operations = [
        migrations.AddField(
            model_name="incomingevent",
            name="event_name",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
