# Generated by Django 6.0.3 on 2026-04-09 08:20

import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_add_phase_visits"),
    ]

    operations = [
        migrations.CreateModel(
            name="MergeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("overlay", models.CharField(blank=True, max_length=255)),
                ("url", models.URLField(max_length=500)),
                ("repo", models.CharField(max_length=255)),
                ("iid", models.CharField(max_length=50)),
                ("slack_url", models.URLField(blank=True, max_length=500)),
                ("review_requested_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("open", "Open"),
                            ("review_requested", "Review requested"),
                            ("approved", "Approved"),
                            ("merged", "Merged"),
                        ],
                        default="open",
                        max_length=32,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merge_requests",
                        to="core.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "teatree_merge_request",
                "constraints": [models.UniqueConstraint(fields=("url",), name="unique_merge_request_url")],
            },
        ),
    ]
