# Generated by Django 6.0.5 on 2026-05-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_add_reply_dispatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="replydispatch",
            name="body",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="replydispatch",
            name="next_retry_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="replydispatch",
            name="retry_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="replydispatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("dead_letter", "Dead letter"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="replydispatch",
            index=models.Index(fields=["status", "next_retry_at"], name="teatree_rep_status_52444b_idx"),
        ),
    ]
