# Generated by Django 6.0.5 on 2026-05-15 10:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_reply_dispatch_retry_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyDigestThread",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(unique=True)),
                ("channel_ref", models.CharField(max_length=255)),
                ("root_ts", models.CharField(max_length=64)),
                ("opened_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "teatree_daily_digest_thread",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="DailyDigestMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("posted_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.dailydigestthread",
                    ),
                ),
            ],
            options={
                "db_table": "teatree_daily_digest_message",
                "ordering": ["posted_at"],
            },
        ),
    ]
