# Generated by Django 6.0.6 on 2026-06-29 14:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_deferredquestion_parked_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrustedIdentity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("gitlab", "GitLab"),
                            ("slack", "Slack"),
                            ("internal", "Internal"),
                        ],
                        max_length=16,
                    ),
                ),
                ("handle", models.CharField(max_length=128)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "teatree_trusted_identity",
                "ordering": ["platform", "handle"],
                "constraints": [
                    models.UniqueConstraint(fields=("platform", "handle"), name="uniq_trustedidentity_platform_handle")
                ],
            },
        ),
    ]
