# Generated by Django 6.1.1 on 2026-10-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_incomingevent_event_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="deferredquestion",
            name="evidence",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
