# Generated by Django 6.0.5 on 2026-05-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_add_daily_digest"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoopLease",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128, unique=True)),
                ("owner", models.CharField(blank=True, max_length=255)),
                ("acquired_at", models.DateTimeField(blank=True, null=True)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "teatree_loop_lease",
            },
        ),
    ]
