# Generated by Django 6.0.7 on 2026-07-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_loop_presets"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewrequestpost",
            name="last_nag_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
