# Generated by Django 6.0.4 on 2026-04-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_ticket_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="redis_db_index",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
