# Generated by Django 6.0.7 on 2026-07-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_reviewrequestpost_last_nag_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="implementedissuemarker",
            name="state",
            field=models.CharField(
                choices=[
                    ("dispatched", "Dispatched"),
                    ("ticket_created", "Ticket created"),
                    ("completed", "Completed"),
                    ("abandoned", "Abandoned"),
                ],
                default="dispatched",
                max_length=16,
            ),
        ),
    ]
