# Generated by Django 6.0.5 on 2026-05-16 21:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_looplease"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="looplease",
            name="heartbeat_at",
        ),
    ]
