# Generated by Django 6.0.7 on 2026-07-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_implementedissuemarker_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="botping",
            name="audience",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="deferredquestion",
            name="dedupe_marker",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="botping",
            name="status",
            field=models.CharField(
                choices=[
                    ("sending", "Sending (delivery claimed, in flight)"),
                    ("sent", "Sent"),
                    ("noop", "Noop (no backend)"),
                    ("failed", "Failed"),
                    ("expired", "Expired (re-delivery abandoned)"),
                    ("logged", "Logged (internal audience, never DM'd)"),
                ],
                max_length=16,
            ),
        ),
    ]
