# Generated by Django 6.0.5 on 2026-05-17 16:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_remove_looplease_heartbeat_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="MergeClear",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pr_id", models.IntegerField()),
                ("slug", models.CharField(max_length=255)),
                ("reviewed_sha", models.CharField(max_length=64)),
                ("reviewer_identity", models.CharField(max_length=255)),
                (
                    "gh_verify_result",
                    models.CharField(
                        choices=[("green", "Green"), ("pending", "Pending"), ("failed", "Failed")], max_length=32
                    ),
                ),
                (
                    "blast_class",
                    models.CharField(
                        choices=[
                            ("substrate", "Substrate (healing/gate substrate)"),
                            ("logic", "Logic (non-substrate business logic)"),
                            ("docs", "Docs (documentation/spec only)"),
                        ],
                        max_length=16,
                    ),
                ),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merge_clears",
                        to="core.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "teatree_merge_clear",
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="MergeAudit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("merged_sha", models.CharField(max_length=64)),
                ("merged_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("required_checks_status", models.CharField(max_length=32)),
                (
                    "clear",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="audits", to="core.mergeclear"
                    ),
                ),
            ],
            options={
                "db_table": "teatree_merge_audit",
                "ordering": ["-merged_at"],
            },
        ),
    ]
