# Generated by Django 6.0.4 on 2026-04-21 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_ticket_retrospected_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorktreeEnvOverride",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=255)),
                ("value", models.TextField(blank=True)),
                (
                    "worktree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="env_overrides", to="core.worktree"
                    ),
                ),
            ],
            options={
                "db_table": "teatree_worktree_env_override",
                "constraints": [models.UniqueConstraint(fields=("worktree", "key"), name="uniq_worktree_env_key")],
            },
        ),
    ]
