# Generated by Django 6.0.6 on 2026-07-01 09:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_looplease_generation"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnthropicTokenUsage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pass_path", models.CharField(max_length=255, unique=True)),
                ("organization_id", models.CharField(blank=True, default="", max_length=255)),
                ("utilization_5h", models.FloatField(default=0.0)),
                ("utilization_7d", models.FloatField(default=0.0)),
                ("status_5h", models.CharField(blank=True, default="", max_length=64)),
                ("status_7d", models.CharField(blank=True, default="", max_length=64)),
                ("reset_5h", models.DateTimeField(blank=True, null=True)),
                ("reset_7d", models.DateTimeField(blank=True, null=True)),
                ("checked_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_until", models.DateTimeField()),
            ],
            options={
                "db_table": "teatree_anthropic_token_usage",
                "ordering": ["pass_path"],
            },
        ),
        migrations.CreateModel(
            name="AnthropicActivePick",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(max_length=32)),
                ("scope", models.CharField(blank=True, default="", max_length=255)),
                ("pass_path", models.CharField(max_length=255)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "teatree_anthropic_active_pick",
                "ordering": ["kind", "scope"],
                "constraints": [
                    models.UniqueConstraint(fields=("kind", "scope"), name="uniq_anthropic_active_pick_kind_scope")
                ],
            },
        ),
    ]
