# Generated by Django 6.0.5 on 2026-05-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_mergeclear_mergeaudit"),
    ]

    operations = [
        migrations.AddField(
            model_name="mergeclear",
            name="human_authorizer",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
