# Generated by Django 6.0.7 on 2026-07-16 11:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_cievalhealsession"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlackSelfAckReaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("overlay", models.CharField(blank=True, default="", max_length=64)),
                ("channel", models.CharField(max_length=64)),
                ("item_ts", models.CharField(max_length=64)),
                ("reacted_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "teatree_slack_self_ack_reaction",
                "ordering": ["reacted_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("overlay", "channel", "item_ts"), name="uniq_selfack_overlay_channel_ts"
                    )
                ],
            },
        ),
    ]
