# Generated by Django 6.0.6 on 2026-07-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_anthropictokenusage_anthropicactivepick"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingchatinjection",
            name="answer_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Unanswered"),
                    ("ack", "Ack"),
                    ("simple", "Simple"),
                    ("delegated", "Delegated"),
                    ("question_reply", "Question reply"),
                    ("self", "Self-authored (skipped)"),
                ],
                default="",
                max_length=16,
            ),
        ),
    ]
