# Generated by Django 6.0.5 on 2026-05-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_mergeclear_human_authorizer"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="context",
            field=models.TextField(blank=True, default=""),
        ),
    ]
