# Generated by Django 6.0.5 on 2026-05-18 12:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_ticket_context"),
    ]

    operations = [
        migrations.CreateModel(
            name="SelfImproveFiring",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("detector", models.CharField(max_length=128)),
                ("dedup_key", models.CharField(max_length=255)),
                ("state_hash", models.CharField(max_length=64)),
                (
                    "severity",
                    models.CharField(choices=[("info", "Info"), ("warn", "Warn"), ("error", "Error")], max_length=16),
                ),
                ("first_fired_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_fired_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "last_action",
                    models.CharField(
                        choices=[
                            ("log", "Log"),
                            ("statusline", "Statusline"),
                            ("slack", "Slack"),
                            ("ticket", "Ticket"),
                            ("auto_fix", "Auto-fix"),
                        ],
                        default="log",
                        max_length=16,
                    ),
                ),
                ("action_count", models.IntegerField(default=1)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="self_improve_firings",
                        to="core.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "teatree_self_improve_firing",
                "ordering": ["-last_fired_at"],
                "indexes": [models.Index(fields=["detector", "last_fired_at"], name="si_firing_det_last_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("detector", "dedup_key"), name="unique_self_improve_detector_dedup_key"
                    )
                ],
            },
        ),
    ]
