# Generated by Django 6.0.7 on 2026-07-17 07:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_loopstate_forced_loopstate_forced_reason_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingTriageRecommendation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("overlay", models.CharField(blank=True, default="", max_length=64)),
                ("issue_url", models.URLField(max_length=1024)),
                ("url_hash", models.CharField(max_length=64, unique=True)),
                ("title", models.CharField(blank=True, default="", max_length=512)),
                ("verdict", models.CharField(blank=True, default="", max_length=16)),
                ("suggested_labels", models.JSONField(blank=True, default=list)),
                ("priority", models.CharField(blank=True, default="", max_length=32)),
                ("duplicate_of", models.URLField(blank=True, default="", max_length=1024)),
                ("rationale", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("action_taken", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "teatree_pending_triage_recommendation",
                "ordering": ["-created_at"],
            },
        ),
    ]
