# Generated by Django 6.0.5 on 2026-05-18 11:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_dbapproval_dbaudit"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnBehalfApproval",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("target", models.CharField(max_length=512)),
                ("action", models.CharField(max_length=64)),
                ("approver_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "teatree_on_behalf_approval",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OnBehalfAudit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("target", models.CharField(max_length=512)),
                ("action", models.CharField(max_length=64)),
                ("approver_id", models.CharField(max_length=255)),
                ("executed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "approval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="audits", to="core.onbehalfapproval"
                    ),
                ),
            ],
            options={
                "db_table": "teatree_on_behalf_audit",
                "ordering": ["-executed_at"],
            },
        ),
    ]
