# Generated by Django 6.0.6 on 2026-07-03 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_agent_harness_two_layer_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskattempt",
            name="lane",
            field=models.CharField(
                blank=True,
                choices=[("subscription", "Subscription"), ("metered", "Metered")],
                default="",
                max_length=16,
            ),
        ),
    ]
