# Generated by Django 6.0.7 on 2026-07-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_dreamqaprobe_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evalscenarioresult",
            name="verdict",
            field=models.CharField(
                choices=[("pass", "Pass"), ("fail", "Fail"), ("skip", "Skip"), ("error", "Error")], max_length=8
            ),
        ),
        migrations.AlterField(
            model_name="sessionauditrecord",
            name="verdict",
            field=models.CharField(
                choices=[("pass", "Pass"), ("fail", "Fail"), ("skip", "Skip"), ("error", "Error")], max_length=8
            ),
        ),
    ]
