# Generated by Django 6.0.5 on 2026-05-18 16:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_merge_self_improve_and_on_behalf"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotPing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("answer", "Answer"), ("question", "Question"), ("info", "Info")], max_length=16
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "Sent"), ("noop", "Noop (no backend)"), ("failed", "Failed")], max_length=16
                    ),
                ),
                ("text", models.TextField()),
                ("channel_ref", models.CharField(blank=True, max_length=255)),
                ("posted_ts", models.CharField(blank=True, max_length=64)),
                ("permalink", models.URLField(blank=True, max_length=512)),
                ("error_message", models.TextField(blank=True)),
                ("posted_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "teatree_bot_ping",
                "ordering": ["-posted_at"],
                "indexes": [
                    models.Index(fields=["kind", "posted_at"], name="teatree_bot_kind_907077_idx"),
                    models.Index(fields=["status", "posted_at"], name="teatree_bot_status_6d25f1_idx"),
                ],
            },
        ),
    ]
