# Generated by Django 6.0.6 on 2026-07-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_loop_colleague_facing"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectLearning",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("repo_slug", models.CharField(db_index=True, max_length=300, unique=True)),
                ("content", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "teatree_project_learning",
                "ordering": ["repo_slug"],
            },
        ),
    ]
