# Generated by Django 6.0.7 on 2026-07-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_pendingtriagerecommendation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botping",
            name="status",
            field=models.CharField(
                choices=[
                    ("sending", "Sending (delivery claimed, in flight)"),
                    ("sent", "Sent"),
                    ("sent_unverified", "Sent (unconfirmed round-trip read)"),
                    ("noop", "Noop (no backend)"),
                    ("failed", "Failed"),
                    ("expired", "Expired (re-delivery abandoned)"),
                    ("logged", "Logged (internal audience, never DM'd)"),
                ],
                max_length=16,
            ),
        ),
    ]
