# Generated by Django 6.0.7 on 2026-07-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_alter_botping_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="mergeaudit",
            name="standing_delegation_by",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
