# Generated by Django 6.0.6 on 2026-07-03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_projectlearning"),
    ]

    operations = [
        migrations.CreateModel(
            name="MRReviewLock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.CharField(max_length=255)),
                ("pr_id", models.IntegerField()),
                ("mr_url", models.URLField(blank=True, default="", max_length=512)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("review_dispatched", "Review dispatched"),
                            ("verdict_pending", "Verdict pending"),
                            ("resolved", "Resolved"),
                        ],
                        default="idle",
                        max_length=32,
                    ),
                ),
                ("holder", models.CharField(blank=True, default="", max_length=255)),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "teatree_mr_review_lock",
            },
        ),
        migrations.AddConstraint(
            model_name="mrreviewlock",
            constraint=models.UniqueConstraint(fields=("slug", "pr_id"), name="uniq_mrreviewlock_slug_pr"),
        ),
    ]
