# Generated by Django 6.0.5 on 2026-05-19 08:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_pendingchatinjection"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewRequestPost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mr_url", models.URLField(max_length=512, unique=True)),
                ("slack_channel_id", models.CharField(max_length=64)),
                ("slack_thread_ts", models.CharField(max_length=64)),
                ("bot_id", models.CharField(blank=True, max_length=64)),
                ("last_nag_step", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("done_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "teatree_review_request_post",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["last_nag_step", "created_at"], name="teatree_rev_last_na_c5c9dd_idx"),
                    models.Index(fields=["done_at"], name="teatree_rev_done_at_59cc46_idx"),
                ],
            },
        ),
    ]
