# Generated by Django 6.0.6 on 2026-07-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_mrreviewlock"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="expedited",
            field=models.BooleanField(default=False),
        ),
    ]
