# Generated by Django 6.0.7 on 2026-07-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_mergeaudit_standing_delegation_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="configsetting",
            name="seed_value",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="configsetting",
            name="seeded_by",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
