# Generated by Django 6.0.6 on 2026-07-04 12:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_ticket_expedited"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewEvidence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[("cold_review", "Cold review"), ("integration_review", "Integration review")],
                        max_length=32,
                    ),
                ),
                ("reviewer_identity", models.CharField(max_length=255)),
                ("verdict", models.CharField(max_length=32)),
                ("head_sha", models.CharField(max_length=64)),
                ("repos", models.JSONField(blank=True, default=list)),
                ("recorded_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="review_evidences", to="core.ticket"
                    ),
                ),
            ],
            options={
                "db_table": "teatree_review_evidence",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(fields=["ticket", "kind", "recorded_at"], name="teatree_rev_ticket__b2571d_idx")
                ],
            },
        ),
    ]
