# Generated by Django 6.0.7 on 2026-07-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_configsetting_seed_provenance"),
    ]

    operations = [
        migrations.AddField(
            model_name="deferredquestion",
            name="audience",
            field=models.CharField(
                choices=[("owner_question", "Owner question"), ("internal", "Internal")],
                db_index=True,
                default="owner_question",
                max_length=16,
            ),
        ),
    ]
