# Generated by Django 6.0.6 on 2026-07-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_review_evidence"),
    ]

    operations = [
        migrations.AddField(
            model_name="incomingevent",
            name="attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="incomingevent",
            name="dead_lettered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incomingevent",
            name="last_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="incomingevent",
            name="next_retry_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pullrequest",
            name="create_verification",
            field=models.CharField(
                choices=[("pending", "Pending"), ("confirmed", "Confirmed")], default="pending", max_length=16
            ),
        ),
        migrations.AddField(
            model_name="pullrequest",
            name="create_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="incomingevent",
            index=models.Index(fields=["dead_lettered_at"], name="teatree_inc_dead_le_72e0f8_idx"),
        ),
    ]
