# Generated by Django 6.0.5 on 2026-05-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_outbound_claim"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingchatinjection",
            name="answer_kind",
            field=models.CharField(
                blank=True,
                choices=[("", "Unanswered"), ("ack", "Ack"), ("simple", "Simple"), ("delegated", "Delegated")],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="pendingchatinjection",
            name="answered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pendingchatinjection",
            name="eyes_reacted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
