# Generated by Django 6.0.7 on 2026-07-20 (#61 availability+preset merge, phase 1).

from django.db import migrations, models

# The recommended intrinsic posture per seeded mode (design §7-A, owner decision A):
# (defers_questions, pauses_self_pump, presence_sensitive). ``maintenance`` and
# ``low-power`` run at night / under token pressure — the owner is typically
# unreachable, so they defer; ``off`` is the reversible "calendar says nothing runs"
# (the owner may still be present) so it does not defer; ``offline`` is the NEW
# holiday-away mode that also pauses the pump (what no preset could express before).
_RECOMMENDED_POSTURE = {
    "engaged": (False, False, True),
    "heads-down": (False, False, True),
    "maintenance": (True, False, True),
    "unattended": (True, False, True),
    "low-power": (True, False, True),
    "off": (False, False, True),
    "offline": (True, True, False),
}

# The new holiday-away mode: every Loop-table loop off, defers + pauses the pump.
# It reproduces the old ``off`` preset + ``away`` availability combination that
# previously required setting BOTH handles — the two-handle friction the merge removes.
_OFFLINE_DESCRIPTION = "Holiday: every loop off, questions defer AND the self-pump pauses (was 'off' preset + 'away')."

# availability_mode string → (defers_questions, pauses_self_pump) for any row whose
# name is not in the recommended table (a custom operator preset). A blank pin means
# "no availability opinion" → present-class (F, F). Mirrors design §4.1.
_PIN_TO_BOOLEANS = {
    "autonomous_away": (True, False),
    "away": (True, True),
    "present": (False, False),
    "": (False, False),
}


def _backfill_mode_booleans(apps, schema_editor):
    """Back-fill the three intrinsic booleans on every existing LoopPreset (fail-open, idempotent)."""
    LoopPreset = apps.get_model("core", "LoopPreset")
    for preset in LoopPreset.objects.all():
        recommended = _RECOMMENDED_POSTURE.get(preset.name)
        if recommended is not None:
            defers, pauses, sensitive = recommended
        else:
            defers, pauses = _PIN_TO_BOOLEANS.get((preset.availability_mode or "").strip(), (False, False))
            sensitive = True
        preset.defers_questions = defers
        preset.pauses_self_pump = pauses
        preset.presence_sensitive = sensitive
        preset.save(update_fields=["defers_questions", "pauses_self_pump", "presence_sensitive"])


def _seed_offline_mode(apps, schema_editor):
    """Create the NEW ``offline`` holiday-away mode if absent (idempotent)."""
    LoopPreset = apps.get_model("core", "LoopPreset")
    Loop = apps.get_model("core", "Loop")
    if LoopPreset.objects.filter(name="offline").exists():
        return
    all_off = dict.fromkeys(Loop.objects.values_list("name", flat=True), False)
    LoopPreset.objects.create(
        name="offline",
        description=_OFFLINE_DESCRIPTION,
        entries=all_off,
        availability_mode="away",
        defers_questions=True,
        pauses_self_pump=True,
        presence_sensitive=False,
        overlay_scope=[],
    )


def _noop_reverse(apps, schema_editor):
    """The backfill/seed is data-only; reversing the schema drop is the reverse."""


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_deferredquestion_audience"),
    ]

    operations = [
        migrations.AddField(
            model_name="looppreset",
            name="defers_questions",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="looppreset",
            name="pauses_self_pump",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="looppreset",
            name="presence_sensitive",
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(_backfill_mode_booleans, _noop_reverse),
        migrations.RunPython(_seed_offline_mode, _noop_reverse),
    ]
