# Generated by Django 6.0.6 on 2026-07-04 19:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_transport_verify_and_dead_letter"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttachmentManifest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("entries", models.JSONField(default=list)),
                ("recorded_by", models.CharField(blank=True, default="", max_length=255)),
                ("recorded_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachment_manifests",
                        to="core.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "teatree_attachment_manifest",
                "ordering": ["-recorded_at"],
            },
        ),
    ]
