# Generated by Django 6.0.7 on 2026-07-21 05:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_mode_booleans"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LoopPreset",
            new_name="Mode",
        ),
        migrations.RenameModel(
            old_name="LoopPresetOverride",
            new_name="ModeOverride",
        ),
        migrations.RenameModel(
            old_name="LoopSchedule",
            new_name="ModeSchedule",
        ),
        migrations.RenameModel(
            old_name="LoopScheduleSlot",
            new_name="ModeScheduleSlot",
        ),
    ]
