# Generated by Django 6.0.7 on 2026-07-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_rename_preset_to_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configsetting",
            name="value",
            field=models.JSONField(blank=True),
        ),
    ]
