# Generated by Django 6.0.6 on 2026-07-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_attachment_manifest"),
    ]

    operations = [
        migrations.AddField(
            model_name="mergeaudit",
            name="expedited_by",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="mergeclear",
            name="expedite_authorizer",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="mergeclear",
            name="local_ci_green_sha",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
