# Generated by Django 6.0.7 on 2026-07-22 09:10

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_alter_configsetting_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("not_started", "Not started"),
                    ("scoped", "Scoped"),
                    ("started", "Started"),
                    ("planned", "Planned"),
                    ("coded", "Coded"),
                    ("tested", "Tested"),
                    ("reviewed", "Reviewed"),
                    ("shipped", "Shipped"),
                    ("in_review", "In review"),
                    ("merged", "Merged"),
                    ("retrospected", "Retrospected"),
                    ("delivered", "Delivered"),
                    ("review_posted", "Review posted"),
                    ("ignored", "Ignored"),
                ],
                default="not_started",
                max_length=32,
            ),
        ),
    ]
