# Generated by Django 6.0.6 on 2026-07-05 00:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_merge_expedite_waiver"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnownIssue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fingerprint", models.CharField(max_length=255, unique=True)),
                ("overlay", models.CharField(blank=True, default="", max_length=100)),
                ("kind", models.CharField(blank=True, default="", max_length=64)),
                (
                    "severity",
                    models.CharField(
                        choices=[("critical", "Critical"), ("warning", "Warning")], default="warning", max_length=16
                    ),
                ),
                ("summary", models.CharField(max_length=500)),
                ("evidence_url", models.CharField(blank=True, default="", max_length=1000)),
                (
                    "source",
                    models.CharField(
                        choices=[("auto", "Auto-derived"), ("manual", "Manual")], default="auto", max_length=8
                    ),
                ),
                ("auto_resolve", models.BooleanField(default=True)),
                ("first_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "teatree_known_issue",
                "ordering": ["severity", "first_seen"],
            },
        ),
    ]
