# Generated by Django 6.0.5 on 2026-05-19 11:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_reviewassignment"),
    ]

    operations = [
        migrations.RenameIndex(  # ty: ignore[unresolved-attribute]
            model_name="outboundclaim",
            new_name="teatree_out_kind_5e3ffc_idx",
            old_name="teatree_out_kind_cl_idx",
        ),
        migrations.RenameIndex(  # ty: ignore[unresolved-attribute]
            model_name="outboundclaim",
            new_name="teatree_out_verifie_95715a_idx",
            old_name="teatree_out_verify_idx",
        ),
        migrations.RenameIndex(  # ty: ignore[unresolved-attribute]
            model_name="outboundclaim",
            new_name="teatree_out_drift_d_1de770_idx",
            old_name="teatree_out_drift_idx",
        ),
    ]
