# Generated by Django 6.0.6 on 2026-07-05 03:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_knownissue"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaitingItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "teatree_waiting_item",
                "ordering": ["created_at"],
            },
        ),
    ]
