# Generated by Django 6.0.6 on 2026-07-05 05:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_waitingitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="StandingGoal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, unique=True)),
                ("check_command", models.TextField()),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "teatree_standing_goal",
                "ordering": ["created_at"],
            },
        ),
    ]
