# Generated by Django 6.0.6 on 2026-07-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_standinggoal"),
    ]

    operations = [
        migrations.AddField(
            model_name="mergeaudit",
            name="repo_slug",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
