# Generated by Django 6.0.6 on 2026-07-05 14:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_standinggoal"),
    ]

    operations = [
        migrations.CreateModel(
            name="FactoryScoreSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("overlay", models.CharField(blank=True, default="", max_length=64)),
                ("window_days", models.IntegerField(default=0)),
                ("recipe_sha", models.CharField(max_length=64)),
                ("tree_sha", models.CharField(blank=True, default="", max_length=64)),
                ("aggregate", models.FloatField(blank=True, default=None, null=True)),
                ("verdict", models.CharField(max_length=16)),
                ("coverage", models.FloatField(default=0.0)),
                ("coverage_floor", models.FloatField(default=0.0)),
                ("recipe_approved", models.BooleanField(default=False)),
                ("signals", models.JSONField(blank=True, default=list)),
                ("delta_vs_previous", models.FloatField(blank=True, default=None, null=True)),
                ("delta_vs_last_different_recipe_sha", models.FloatField(blank=True, default=None, null=True)),
            ],
            options={
                "db_table": "teatree_factory_score_snapshot",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["overlay", "created_at"], name="fss_overlay_created_idx"),
                    models.Index(fields=["recipe_sha", "created_at"], name="fss_recipe_created_idx"),
                ],
            },
        ),
    ]
