# Generated by Django 6.0.7 on 2026-07-23 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_generic_openai_compatible_backend"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionTodo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("in_progress", "In progress"), ("done", "Done")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="todos", to="core.session"
                    ),
                ),
            ],
            options={
                "db_table": "teatree_session_todo",
                "ordering": ["order", "pk"],
            },
        ),
    ]
