# Generated by Django 6.0.6 on 2026-07-05 16:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_factoryscoresnapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="CriticDispatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("transition", models.CharField(max_length=64)),
                ("head_sha", models.CharField(blank=True, default="", max_length=64)),
                ("dispatched_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="critic_dispatches",
                        to="core.task",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="critic_dispatches", to="core.ticket"
                    ),
                ),
            ],
            options={
                "db_table": "teatree_critic_dispatch",
                "ordering": ["-dispatched_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ticket", "transition", "head_sha"), name="uniq_critic_dispatch_ticket_transition_head"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CriticFinding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("transition", models.CharField(max_length=64)),
                ("rubric_item", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[("fail", "Fail"), ("instrumentation_gap", "Instrumentation gap")],
                        default="fail",
                        max_length=32,
                    ),
                ),
                ("adversarial_question", models.CharField(blank=True, default="", max_length=255)),
                ("detail", models.TextField(blank=True, default="")),
                ("head_sha", models.CharField(blank=True, default="", max_length=64)),
                ("recorded_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="critic_findings", to="core.ticket"
                    ),
                ),
            ],
            options={
                "db_table": "teatree_critic_finding",
                "ordering": ["-recorded_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ticket", "transition", "rubric_item"),
                        name="uniq_critic_finding_ticket_transition_item",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CriticVerdict",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("transition", models.CharField(max_length=64)),
                ("head_sha", models.CharField(blank=True, default="", max_length=64)),
                ("grader_identity", models.CharField(max_length=255)),
                ("items", models.JSONField(blank=True, default=list)),
                ("recorded_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="critic_verdicts", to="core.ticket"
                    ),
                ),
            ],
            options={
                "db_table": "teatree_critic_verdict",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(fields=["ticket", "transition", "head_sha"], name="teatree_cri_ticket__0ff4f3_idx")
                ],
            },
        ),
    ]
