# Generated by Django 6.0.7 on 2026-07-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_review_verdict_reviewer_identity_normalized"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskattempt",
            name="reasoning_effort",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="taskattempt",
            name="skills_loaded",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
