# Generated by Django 6.0.7 on 2026-07-27 09:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_taskattempt_reasoning_effort_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutOfBandWorkApproval",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("head_sha", models.CharField(max_length=64)),
                ("approver_id", models.CharField(max_length=255)),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="out_of_band_approvals",
                        to="core.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "teatree_out_of_band_approval",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OutOfBandWorkAudit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("head_sha", models.CharField(max_length=64)),
                ("approver_id", models.CharField(max_length=255)),
                ("reason", models.TextField()),
                ("executed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "approval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audits",
                        to="core.outofbandworkapproval",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="out_of_band_audits", to="core.ticket"
                    ),
                ),
            ],
            options={
                "db_table": "teatree_out_of_band_audit",
                "ordering": ["-executed_at"],
            },
        ),
    ]
