# Generated by Django 6.0.6 on 2026-07-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_outer_loop_experiment"),
    ]

    operations = [
        migrations.AddField(
            model_name="looplease",
            name="driver",
            field=models.CharField(
                blank=True,
                choices=[("self_pump", "Self Pump"), ("loop_runner", "Loop Runner"), ("external", "External")],
                default="",
                max_length=16,
            ),
        ),
    ]
