# Generated by Django 6.0.6 on 2026-07-05 22:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_looplease_driver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intentclassification",
            name="intent",
            field=models.CharField(
                choices=[
                    ("task", "Task"),
                    ("question", "Question"),
                    ("approval", "Approval"),
                    ("status_update", "Status update"),
                    ("escalation", "Escalation"),
                    ("directive", "Directive"),
                    ("noise", "Noise"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="Directive",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("raw_text", models.TextField()),
                (
                    "source",
                    models.CharField(
                        choices=[("cli", "CLI"), ("incoming_event", "Incoming event"), ("dream_ask", "Dream ask")],
                        max_length=32,
                    ),
                ),
                ("scope_overlay", models.CharField(blank=True, default="", max_length=64)),
                ("constraint_statement", models.TextField(blank=True, default="")),
                ("mechanism_sketch", models.JSONField(blank=True, null=True)),
                ("generation", models.PositiveIntegerField(default=0)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("captured", "Captured"),
                            ("clarifying", "Clarifying"),
                            ("interpreted", "Interpreted"),
                            ("ratify_pending", "Ratify pending"),
                            ("admitted", "Admitted"),
                            ("implementing", "Implementing"),
                            ("configuring", "Configuring"),
                            ("verifying", "Verifying"),
                            ("fulfilled", "Fulfilled"),
                            ("rejected", "Rejected"),
                            ("revert_pending", "Revert pending"),
                            ("reverted", "Reverted"),
                        ],
                        default="captured",
                        max_length=16,
                    ),
                ),
                ("activation_applied_at", models.DateTimeField(blank=True, null=True)),
                ("verify_started_at", models.DateTimeField(blank=True, null=True)),
                ("decision_reason", models.TextField(blank=True, default="")),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "baseline_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="baseline_of_directives",
                        to="core.factoryscoresnapshot",
                    ),
                ),
                (
                    "post_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="post_of_directives",
                        to="core.factoryscoresnapshot",
                    ),
                ),
                (
                    "ratify_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ratified_directives",
                        to="core.deferredquestion",
                    ),
                ),
                (
                    "revert_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reverted_directives",
                        to="core.deferredquestion",
                    ),
                ),
                (
                    "source_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="directives",
                        to="core.incomingevent",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="directives",
                        to="core.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "teatree_directive",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DirectiveDispatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("purpose", models.CharField(choices=[("interpret", "Interpret")], default="interpret", max_length=32)),
                ("generation", models.PositiveIntegerField(default=0)),
                ("dispatched_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "directive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="dispatches", to="core.directive"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="directive_dispatches",
                        to="core.task",
                    ),
                ),
            ],
            options={
                "db_table": "teatree_directive_dispatch",
                "ordering": ["-dispatched_at"],
            },
        ),
        migrations.AddIndex(
            model_name="directive",
            index=models.Index(fields=["state", "created_at"], name="directive_state_created_idx"),
        ),
        migrations.AddIndex(
            model_name="directive",
            index=models.Index(fields=["scope_overlay", "state"], name="directive_scope_state_idx"),
        ),
        migrations.AddConstraint(
            model_name="directivedispatch",
            constraint=models.UniqueConstraint(
                fields=("directive", "purpose", "generation"),
                name="uniq_directive_dispatch_directive_purpose_generation",
            ),
        ),
    ]
