# Generated by Django 6.0.7 on 2026-07-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_retire_pane_reaper_loop"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskattempt",
            name="park_repeats",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
