# Generated by Django 6.0.6 on 2026-07-06 19:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_seed_directive_loop"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReproWaiver",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("approver_id", models.CharField(max_length=255)),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="repro_waivers", to="core.ticket"
                    ),
                ),
            ],
            options={
                "db_table": "teatree_repro_waiver",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReproEvidence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("command", models.TextField()),
                ("command_fingerprint", models.CharField(db_index=True, max_length=64)),
                ("red_head_sha", models.CharField(max_length=64)),
                ("red_exit_code", models.IntegerField()),
                ("red_output_digest", models.CharField(max_length=64)),
                ("red_output_tail", models.TextField(blank=True, default="")),
                ("red_recorded_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("green_head_sha", models.CharField(blank=True, default="", max_length=64)),
                ("green_exit_code", models.IntegerField(blank=True, null=True)),
                ("green_output_digest", models.CharField(blank=True, default="", max_length=64)),
                ("green_output_tail", models.TextField(blank=True, default="")),
                ("green_recorded_at", models.DateTimeField(blank=True, null=True)),
                ("provenance_ok", models.BooleanField(default=False)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="repro_evidences", to="core.ticket"
                    ),
                ),
            ],
            options={
                "db_table": "teatree_repro_evidence",
                "ordering": ["-red_recorded_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ticket", "command_fingerprint"), name="uniq_repro_evidence_ticket_cmd"
                    )
                ],
            },
        ),
    ]
