# Generated by Django 6.0.7 on 2026-07-28 17:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_merge_upstream_vendor_sync"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewBackendCooldown",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("backend", models.CharField(max_length=32)),
                ("overlay", models.CharField(blank=True, default="", max_length=64)),
                ("signature", models.CharField(blank=True, default="", max_length=128)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "db_table": "teatree_review_backend_cooldown",
                "ordering": ["-expires_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("backend", "overlay"), name="uniq_reviewbackendcooldown_backend_overlay"
                    )
                ],
            },
        ),
    ]
