# Generated by Django 6.0.6 on 2026-07-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_reprowaiver_reproevidence"),
    ]

    operations = [
        migrations.AddField(
            model_name="directive",
            name="taint",
            field=models.CharField(default="public", max_length=32),
        ),
        migrations.AddField(
            model_name="incomingevent",
            name="provenance",
            field=models.CharField(default="public", max_length=32),
        ),
    ]
