# Generated by Django 6.0.7 on 2026-07-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_merge_squashed_migration_leaf"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="taskattempt",
            index=models.Index(
                fields=[
                    "execution_target",
                    "started_at",
                    "model",
                    "lane",
                    "cost_is_estimated",
                    "cost_usd",
                    "input_tokens",
                    "output_tokens",
                    "cache_read_tokens",
                    "cache_write_tokens",
                    "task",
                ],
                name="taskattempt_cost_cover",
            ),
        ),
    ]
