# Generated by Django 6.0.5 on 2026-05-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_codexreviewmarker"),
    ]

    operations = [
        migrations.AddField(
            model_name="botping",
            name="transport",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Unset (direct notify_user)"),
                    ("primary", "Primary (notify_user)"),
                    ("fallback", "Fallback (direct verified send)"),
                ],
                default="",
                max_length=16,
            ),
        ),
    ]
