# Generated by Django 6.0.7 on 2026-07-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_taskattempt_taskattempt_cost_cover"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="tickettransition",
            index=models.Index(fields=["ticket", "created_at"], name="teatree_tic_ticket__04a0bd_idx"),
        ),
        migrations.AddIndex(
            model_name="tickettransition",
            index=models.Index(fields=["created_at"], name="teatree_tic_created_e0a381_idx"),
        ),
    ]
