# Generated by Django 6.0.5 on 2026-05-27 20:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_botping_transport"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingArticleSuggestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("overlay", models.CharField(blank=True, default="", max_length=64)),
                ("url", models.URLField(max_length=1024)),
                ("url_hash", models.CharField(max_length=64, unique=True)),
                ("title", models.CharField(blank=True, default="", max_length=512)),
                ("summary", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("issue_url", models.URLField(blank=True, default="", max_length=1024)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "teatree_pending_article_suggestion",
                "ordering": ["-created_at"],
            },
        ),
    ]
