# Generated by Django 6.0.6 on 2026-07-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_directive_taint_incomingevent_provenance"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsageWindowState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("lane", models.CharField(blank=True, default="", max_length=16)),
                ("cause", models.CharField(blank=True, default="", max_length=32)),
                ("detected_at", models.DateTimeField()),
                ("resets_at", models.DateTimeField(blank=True, null=True)),
                ("cleared_at", models.DateTimeField(blank=True, null=True)),
                ("probe_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "teatree_usagewindowstate",
            },
        ),
        migrations.AddField(
            model_name="task",
            name="not_before",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
