# Generated by Django 6.0.7 on 2026-07-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_ticket_transition_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnshippedWorkRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("checkout_path", models.CharField(max_length=1024, unique=True)),
                ("branch", models.CharField(blank=True, max_length=255)),
                ("overlay", models.CharField(blank=True, max_length=100)),
                ("dirty_paths", models.JSONField(default=list)),
                ("unpushed_commits", models.JSONField(default=list)),
                ("artifact_prefix", models.CharField(blank=True, max_length=1024)),
                ("unreadable", models.TextField(blank=True)),
                ("captured_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "teatree_unshipped_work_record",
                "ordering": ["-captured_at"],
            },
        ),
    ]
