# Generated by Django 6.0.5 on 2026-05-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_pullmainclonemarker"),
    ]

    operations = [
        migrations.CreateModel(
            name="MiniLoopMarker",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, unique=True)),
                ("last_fired_at", models.DateTimeField()),
            ],
            options={
                "db_table": "teatree_mini_loop_marker",
                "ordering": ["-last_fired_at"],
            },
        ),
    ]
