# Generated by Django 6.0.7 on 2026-07-29 16:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_unshippedworkrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingPullRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("repo_path", models.CharField(max_length=1024)),
                ("branch", models.CharField(max_length=255)),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("spec", models.JSONField(blank=True, default=dict)),
                ("deferred_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("drain_attempts", models.PositiveIntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "teatree_pending_pull_request",
                "ordering": ["-deferred_at"],
                "constraints": [
                    models.UniqueConstraint(fields=("repo_path", "branch"), name="uniq_pending_pr_repo_branch")
                ],
            },
        ),
    ]
