# Generated by Django 6.0.7 on 2026-07-29 16:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_pending_pull_request"),
    ]

    operations = [
        migrations.CreateModel(
            name="SweepSkipStreak",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("overlay", models.CharField(blank=True, default="", max_length=64)),
                ("slug", models.CharField(max_length=255)),
                ("pr_id", models.IntegerField()),
                ("reason", models.CharField(max_length=128)),
                ("url", models.URLField(blank=True, default="", max_length=512)),
                ("first_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("tick_count", models.PositiveIntegerField(default=1)),
                ("surfaced_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "teatree_sweep_skip_streak",
                "ordering": ["-last_seen_at"],
                "constraints": [
                    models.UniqueConstraint(fields=("slug", "pr_id"), name="uniq_sweep_skip_streak_slug_pr")
                ],
            },
        ),
    ]
