# Generated by Django 6.0.5 on 2026-05-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_miniloopmarker"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourcePressureMarker",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("singleton", models.BooleanField(default=True, unique=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_disk_free_gb", models.FloatField(blank=True, null=True)),
                ("last_ram_avail_gb", models.FloatField(blank=True, null=True)),
                ("last_freed_at", models.DateTimeField(blank=True, null=True)),
                ("consecutive_critical", models.IntegerField(default=0)),
                ("last_warn_dm_at", models.DateTimeField(blank=True, null=True)),
                ("last_plan", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "teatree_resource_pressure_marker",
                "ordering": ["-last_run_at"],
            },
        ),
    ]
