# Generated by Django 6.0.5 on 2026-05-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_resource_pressure_marker"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="last_sweep_check_ts",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
