# Generated by Django 6.0.5 on 2026-05-30 16:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_task_last_sweep_check_ts"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImplementedIssueMarker",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("issue_url", models.URLField(max_length=512)),
                ("overlay", models.CharField(blank=True, default="", max_length=64)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("dispatched", "Dispatched"),
                            ("ticket_created", "Ticket created"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="dispatched",
                        max_length=16,
                    ),
                ),
                ("dispatched_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("head_sha", models.CharField(blank=True, default="", max_length=64)),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="implemented_issue_markers",
                        to="core.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "teatree_implemented_issue_marker",
                "ordering": ["-dispatched_at"],
                "constraints": [
                    models.UniqueConstraint(fields=("issue_url", "overlay"), name="uniq_impl_issue_url_overlay")
                ],
            },
        ),
    ]
