# Generated by Django 6.0.7 on 2026-07-30 15:57

from datetime import timedelta

from django.db import migrations, models


def backfill_deadlines(apps, schema_editor):
    """Give every pre-existing claim the deadline it never had.

    Rows written before this migration carry ``deadline = NULL``, which the
    acquirability predicate reads as "no bound" and therefore never reclaims.
    Those are exactly the stranded claims #3920 is about — heads armed by a
    reviewer that died, unmergeable until someone force-pushes. Deriving the
    deadline from ``dispatched_at`` makes each of them expired-and-reclaimable
    on the next sweep, so the fix heals the live backlog instead of only
    preventing the next one.
    """
    for model_name in ("CriticDispatch",):
        model = apps.get_model("core", model_name)
        for row in model.objects.filter(deadline__isnull=True).iterator():
            row.deadline = row.dispatched_at + timedelta(hours=2)
            row.save(update_fields=["deadline"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_dispatch_deadline_and_retry_bound"),
    ]

    operations = [
        migrations.AddField(
            model_name="criticdispatch",
            name="attempts",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="criticdispatch",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="criticdispatch",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="criticdispatch",
            name="state",
            field=models.CharField(
                choices=[("dispatched", "Dispatched"), ("resolved", "Resolved")], default="dispatched", max_length=32
            ),
        ),
        migrations.RunPython(backfill_deadlines, migrations.RunPython.noop),
    ]
