# Generated by Django 6.0.5 on 2026-05-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_implementedissuemarker"),
    ]

    operations = [
        migrations.AddField(
            model_name="looplease",
            name="owner_pid",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
