# Generated by Django 6.0.7 on 2026-07-30 17:55

from django.db import migrations, models


def _hold_legacy_verdict_pending_locks(apps, schema_editor):
    """Keep a legacy ``verdict_pending`` lock HELD rather than silently unblocking its merge.

    ``verdict_pending`` was unreachable in production — its only transition,
    ``mark_verdict_pending``, never had a caller — so this is expected to touch
    zero rows. It exists because the alternative failure is one-directional: a
    surviving row dropping out of the merge gate's active set would let a merge
    proceed past a lock that used to refuse it.
    """
    apps.get_model("core", "MRReviewLock").objects.filter(state="verdict_pending").update(state="review_dispatched")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_critic_dispatch_deadline"),
    ]

    operations = [
        migrations.RunPython(_hold_legacy_verdict_pending_locks, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="reviewloop",
            name="current_task",
        ),
        migrations.RemoveField(
            model_name="reviewloop",
            name="latest_verdict",
        ),
        migrations.RemoveField(
            model_name="reviewloop",
            name="ticket",
        ),
        migrations.RemoveConstraint(
            model_name="reviewloopround",
            name="uniq_review_loop_round_leg",
        ),
        migrations.RemoveIndex(
            model_name="reviewrequestpost",
            name="teatree_rev_last_na_c5c9dd_idx",
        ),
        migrations.AlterField(
            model_name="mrreviewlock",
            name="state",
            field=models.CharField(
                choices=[("idle", "Idle"), ("review_dispatched", "Review dispatched"), ("resolved", "Resolved")],
                default="idle",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="reviewassignment",
            name="state",
            field=models.CharField(
                choices=[("pending", "Pending"), ("approved", "Approved")], default="pending", max_length=16
            ),
        ),
        migrations.AddIndex(
            model_name="reviewrequestpost",
            index=models.Index(fields=["created_at"], name="teatree_rev_created_579285_idx"),
        ),
        migrations.RemoveField(
            model_name="reviewloopround",
            name="review_loop",
        ),
        migrations.RemoveField(
            model_name="reviewloopround",
            name="task",
        ),
        migrations.RemoveField(
            model_name="reviewrequestpost",
            name="last_nag_step",
        ),
        migrations.DeleteModel(
            name="ReviewLoop",
        ),
        migrations.DeleteModel(
            name="ReviewLoopRound",
        ),
    ]
