# Generated by Django 6.0.5 on 2026-06-01 12:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0044_looplease_owner_pid"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvalRunRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("model", models.CharField(max_length=64)),
                ("suite", models.CharField(blank=True, default="", max_length=128)),
                ("overlay", models.CharField(blank=True, default="", max_length=64)),
                ("max_turns_override", models.IntegerField(blank=True, default=None, null=True)),
                ("is_baseline", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "teatree_eval_run",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(fields=["model", "started_at"], name="eval_run_model_started_idx"),
                    models.Index(fields=["is_baseline", "started_at"], name="eval_run_baseline_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="EvalScenarioResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scenario_name", models.CharField(max_length=128)),
                ("trial", models.IntegerField(default=0)),
                (
                    "verdict",
                    models.CharField(choices=[("pass", "Pass"), ("fail", "Fail"), ("skip", "Skip")], max_length=8),
                ),
                ("terminal_reason", models.CharField(blank=True, default="", max_length=128)),
                ("is_error", models.BooleanField(default=False)),
                ("tool_calls", models.JSONField(blank=True, default=list)),
                ("matcher_details", models.JSONField(blank=True, default=list)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenario_results",
                        to="core.evalrunrecord",
                    ),
                ),
            ],
            options={
                "db_table": "teatree_eval_scenario_result",
                "ordering": ["scenario_name", "trial"],
                "indexes": [models.Index(fields=["run", "scenario_name"], name="eval_sr_run_scenario_idx")],
            },
        ),
    ]
