# Generated by Django 6.0.5 on 2026-06-01 17:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0044_looplease_owner_pid"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvalRunRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("run_id", models.CharField(max_length=64)),
                ("scenario", models.CharField(max_length=128)),
                ("model", models.CharField(max_length=64)),
                ("passed", models.BooleanField(default=False)),
                ("skipped", models.BooleanField(default=False)),
                ("score", models.FloatField(default=0.0)),
                ("trials", models.PositiveSmallIntegerField(default=1)),
                ("git_sha", models.CharField(blank=True, default="", max_length=64)),
                ("recorded_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "teatree_eval_run_record",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(fields=["model", "-recorded_at"], name="eval_rec_model_recorded"),
                    models.Index(fields=["run_id"], name="eval_rec_run_id"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("run_id", "scenario", "model"), name="uniq_eval_run_scenario_model")
                ],
            },
        ),
    ]
