# Generated by Django 6.0.5 on 2026-06-01 13:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0045_evalrunrecord_evalscenarioresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewVerdict",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pr_id", models.IntegerField()),
                ("slug", models.CharField(max_length=255)),
                ("reviewed_sha", models.CharField(max_length=64)),
                ("verdict", models.CharField(choices=[("merge_safe", "Merge-safe"), ("hold", "Hold")], max_length=16)),
                ("reviewer_identity", models.CharField(max_length=255)),
                (
                    "blast_class",
                    models.CharField(
                        choices=[
                            ("substrate", "Substrate (healing/gate substrate)"),
                            ("logic", "Logic (non-substrate business logic)"),
                            ("docs", "Docs (documentation/spec only)"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "gh_verify_result",
                    models.CharField(
                        choices=[("green", "Green"), ("pending", "Pending"), ("failed", "Failed")], max_length=32
                    ),
                ),
                ("findings", models.JSONField(blank=True, default=list)),
                ("recorded_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_verdicts",
                        to="core.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "teatree_review_verdict",
                "ordering": ["-recorded_at"],
                "indexes": [models.Index(fields=["slug", "pr_id", "reviewed_sha"], name="teatree_rev_slug_c3ee61_idx")],
            },
        ),
    ]
