# Generated by Django 6.0.5 on 2026-06-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0045_evalrunrecord_evalscenarioresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="kind",
            field=models.CharField(choices=[("feature", "Feature"), ("fix", "Fix")], default="feature", max_length=16),
        ),
    ]
