# Generated by Django 6.0.7 on 2026-07-31 06:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_merge_review_cooldown_and_transition_indexes"),
        ("core", "0046_codex_review_marker_expiring_claim"),
    ]

    operations = []
