# Generated by Django 6.0.5 on 2026-06-01 18:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_reviewverdict"),
        ("core", "0046_ticket_kind"),
    ]

    operations = []
