# Generated by Django 6.0.7 on 2026-07-31 04:18

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_codex_review_marker_expiring_claim"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pullrequest",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("open", "Open"),
                    ("review_requested", "Review requested"),
                    ("approved", "Approved"),
                    ("merged", "Merged"),
                    ("closed", "Closed"),
                ],
                default="open",
                max_length=32,
            ),
        ),
    ]
