# Generated by Django 6.0.5 on 2026-06-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0047_merge_0046_reviewverdict_0046_ticket_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskattempt",
            name="cache_read_tokens",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskattempt",
            name="cache_write_tokens",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskattempt",
            name="model",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
