# Generated by Django 6.0.7 on 2026-07-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0048_park_self_addressed_handovers"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="failure_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("unrecorded", "No reason recorded"),
                    ("unclassified", "Unclassified"),
                    ("lease_lost", "Lease lost to another worker"),
                    ("lease_expired", "Lease expired and was reaped"),
                    ("runtime_ceiling", "Runtime ceiling exceeded"),
                    ("usage_limit_parked", "Parked on a usage window"),
                    ("credential_exhausted", "Credentials exhausted"),
                    ("harness_config_invalid", "Invalid harness configuration"),
                    ("harness_crash", "Harness crashed"),
                    ("outage", "Network or API outage"),
                    ("result_error", "Run ended without a clean result"),
                    ("provision_failed", "Worktree provisioning failed"),
                    ("landing_unverified", "Work never landed"),
                    ("no_result_envelope", "No result envelope produced"),
                    ("evidence_missing", "Required evidence missing"),
                    ("recording_refused", "Recording refused by a gate"),
                    ("cancelled", "Cancelled by an operator"),
                    ("superseded", "Superseded by rework"),
                    ("agent_abandoned", "Agent failed the task without a reason"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="failure_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="taskattempt",
            name="failure_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("unrecorded", "No reason recorded"),
                    ("unclassified", "Unclassified"),
                    ("lease_lost", "Lease lost to another worker"),
                    ("lease_expired", "Lease expired and was reaped"),
                    ("runtime_ceiling", "Runtime ceiling exceeded"),
                    ("usage_limit_parked", "Parked on a usage window"),
                    ("credential_exhausted", "Credentials exhausted"),
                    ("harness_config_invalid", "Invalid harness configuration"),
                    ("harness_crash", "Harness crashed"),
                    ("outage", "Network or API outage"),
                    ("result_error", "Run ended without a clean result"),
                    ("provision_failed", "Worktree provisioning failed"),
                    ("landing_unverified", "Work never landed"),
                    ("no_result_envelope", "No result envelope produced"),
                    ("evidence_missing", "Required evidence missing"),
                    ("recording_refused", "Recording refused by a gate"),
                    ("cancelled", "Cancelled by an operator"),
                    ("superseded", "Superseded by rework"),
                    ("agent_abandoned", "Agent failed the task without a reason"),
                ],
                default="",
                max_length=32,
            ),
        ),
    ]
