# Generated by Django 6.0.5 on 2026-06-01 16:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0049_eval_scenario_model_score_trials"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionHandover",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("from_session", models.CharField(max_length=255)),
                ("to_session", models.CharField(blank=True, default="", max_length=255)),
                ("payload", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("claimed_by", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "db_table": "teatree_session_handover",
                "indexes": [models.Index(fields=["to_session", "claimed_at"], name="teatree_ses_to_sess_aafffd_idx")],
            },
        ),
    ]
