# Generated by Django 6.0.7 on 2026-08-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0049_task_failure_kind_task_failure_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcepressuremarker",
            name="adaptive_intake_concurrency",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resourcepressuremarker",
            name="adaptive_intake_recorded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
