# Generated by Django 6.0.7 on 2026-07-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0049_task_failure_kind_task_failure_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewrequestpost",
            name="nag_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="reviewrequestpost",
            name="resumed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
