# Generated by Django 6.0.7 on 2026-08-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0050_review_request_post_nag_backoff_and_resume"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="redmrfixattempt",
            name="uniq_redmrfix_url_sha",
        ),
        migrations.AddField(
            model_name="redmrfixattempt",
            name="kind",
            field=models.CharField(
                choices=[("ci_red", "CI red"), ("merge_conflict", "Merge conflict")], default="ci_red", max_length=32
            ),
        ),
        migrations.AddConstraint(
            model_name="redmrfixattempt",
            constraint=models.UniqueConstraint(
                fields=("pr_url", "head_sha", "kind"), name="uniq_redmrfix_url_sha_kind"
            ),
        ),
    ]
