# Generated by Django 6.0.5 on 2026-06-02 10:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0050_sessionhandover"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingReinstall",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("repo_label", models.CharField(max_length=64, unique=True)),
                ("target_sha", models.CharField(blank=True, default="", max_length=64)),
                (
                    "state",
                    models.CharField(
                        choices=[("pending", "Pending"), ("done", "Done"), ("failed", "Failed")],
                        default="pending",
                        max_length=8,
                    ),
                ),
                ("requested_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.CharField(blank=True, default="", max_length=200)),
            ],
            options={
                "db_table": "teatree_pending_reinstall",
                "ordering": ["requested_at"],
            },
        ),
    ]
