# Generated by Django 6.0.5 on 2026-06-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0051_pendingreinstall"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botping",
            name="status",
            field=models.CharField(
                choices=[
                    ("sending", "Sending (delivery claimed, in flight)"),
                    ("sent", "Sent"),
                    ("noop", "Noop (no backend)"),
                    ("failed", "Failed"),
                ],
                max_length=16,
            ),
        ),
    ]
