# Generated by Django 6.0.7 on 2026-08-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0051_red_mr_fix_attempt_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="dreamrunmarker",
            name="distill_cursor",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
