# Generated by Django 6.0.7 on 2026-08-03 12:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0054_backfill_task_failure_reason"),
    ]

    operations = [
        migrations.CreateModel(
            name="BranchUpdateAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("overlay", models.CharField(blank=True, default="", max_length=64)),
                ("slug", models.CharField(max_length=255)),
                ("pr_id", models.IntegerField()),
                ("head_sha", models.CharField(max_length=64)),
                ("pr_url", models.URLField(blank=True, default="", max_length=512)),
                ("attempted_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "teatree_branch_update_attempt",
                "ordering": ["-attempted_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("slug", "pr_id", "head_sha"), name="uniq_branch_update_attempt_slug_pr_head"
                    )
                ],
            },
        ),
    ]
