# Generated by Django 6.0.5 on 2026-06-05 13:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0054_canonicalize_legacy_overlay_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="E2EBypassApproval",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("head_sha", models.CharField(max_length=64)),
                ("approver_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="e2e_bypass_approvals",
                        to="core.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "teatree_e2e_bypass_approval",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="E2EBypassAudit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("head_sha", models.CharField(max_length=64)),
                ("approver_id", models.CharField(max_length=255)),
                ("executed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "approval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="audits", to="core.e2ebypassapproval"
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="e2e_bypass_audits", to="core.ticket"
                    ),
                ),
            ],
            options={
                "db_table": "teatree_e2e_bypass_audit",
                "ordering": ["-executed_at"],
            },
        ),
        migrations.CreateModel(
            name="E2eMandatoryRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("head_sha", models.CharField(max_length=64)),
                ("spec", models.CharField(max_length=512)),
                ("result", models.CharField(choices=[("green", "Green"), ("red", "Red")], max_length=16)),
                ("posted_url", models.CharField(blank=True, default="", max_length=512)),
                ("recorded_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="e2e_mandatory_runs", to="core.ticket"
                    ),
                ),
            ],
            options={
                "db_table": "teatree_e2e_mandatory_run",
                "ordering": ["-recorded_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ticket", "head_sha", "spec"), name="uniq_e2e_mandatory_run_ticket_sha_spec"
                    )
                ],
            },
        ),
    ]
