# Generated by Django 6.0.5 on 2026-06-06 05:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0055_e2ebypassapproval_e2ebypassaudit_e2emandatoryrun"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoReviewDispatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.CharField(max_length=255)),
                ("pr_id", models.IntegerField()),
                ("head_sha", models.CharField(max_length=64)),
                ("pr_url", models.URLField(blank=True, default="", max_length=512)),
                ("overlay", models.CharField(blank=True, default="", max_length=64)),
                ("dispatched_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auto_review_dispatches",
                        to="core.task",
                    ),
                ),
            ],
            options={
                "db_table": "teatree_auto_review_dispatch",
                "ordering": ["-dispatched_at"],
                "constraints": [
                    models.UniqueConstraint(fields=("slug", "pr_id", "head_sha"), name="uniq_auto_review_slug_pr_head")
                ],
            },
        ),
    ]
