# Generated by Django 6.0.7 on 2026-08-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0055_branchupdateattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="admitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
