# Generated by Django 6.0.5 on 2026-06-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0056_autoreviewdispatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="deferredquestion",
            name="applied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deferredquestion",
            name="generation",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="deferredquestion",
            name="options_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="deferredquestion",
            name="resolved_via",
            field=models.CharField(
                blank=True,
                choices=[("", "Unresolved"), ("slack", "Slack reply"), ("local", "Local CLI"), ("stale", "Stale")],
                default="",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="deferredquestion",
            name="run_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="deferredquestion",
            name="slack_channel",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="deferredquestion",
            name="slack_ts",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="pendingchatinjection",
            name="answer_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Unanswered"),
                    ("ack", "Ack"),
                    ("simple", "Simple"),
                    ("delegated", "Delegated"),
                    ("question_reply", "Question reply"),
                ],
                default="",
                max_length=16,
            ),
        ),
    ]
