# Generated by Django 6.0.6 on 2026-06-07 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0058_botping_attempts_alter_botping_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="DreamQaProbe",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("probe_key", models.CharField(max_length=64, unique=True)),
                ("question", models.TextField()),
                ("expected_answer", models.TextField()),
                ("source_memory_path", models.CharField(blank=True, default="", max_length=512)),
                ("overlay", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_pass_rate", models.FloatField(default=0.0)),
                ("pass_count", models.PositiveIntegerField(default=0)),
                ("run_count", models.PositiveIntegerField(default=0)),
                ("is_prior_session", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "teatree_dream_qa_probe",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DreamRunMarker",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="dream", max_length=64, unique=True)),
                ("last_succeeded_at", models.DateTimeField(blank=True, null=True)),
                ("last_attempted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "teatree_dream_run_marker",
            },
        ),
        migrations.CreateModel(
            name="ConsolidatedMemory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cluster_key", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("candidate", "Candidate"),
                            ("verified", "Verified"),
                            ("promoted", "Promoted"),
                            ("superseded", "Superseded"),
                            ("expired", "Expired"),
                        ],
                        default="candidate",
                        max_length=16,
                    ),
                ),
                ("rule", models.TextField()),
                ("source_files", models.JSONField(default=list)),
                ("durable_destination", models.CharField(blank=True, default="", max_length=512)),
                ("is_binding", models.BooleanField(default=False)),
                ("member_count", models.PositiveIntegerField()),
                ("max_member_weight", models.PositiveIntegerField()),
                ("verified_citation", models.TextField(blank=True, default="")),
                ("archive_path", models.CharField(blank=True, default="", max_length=512)),
                ("overlay", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("promoted_at", models.DateTimeField(blank=True, null=True)),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supersedes",
                        to="core.consolidatedmemory",
                    ),
                ),
            ],
            options={
                "db_table": "teatree_consolidated_memory",
                "ordering": ["-created_at"],
            },
        ),
    ]
