# Generated by Django 6.0.3 on 2026-06-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0059_dreamqaprobe_dreamrunmarker_consolidatedmemory"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="remote_missing",
            field=models.BooleanField(
                default=False,
                help_text="True when the remote forge returned HTTP 404 for this ticket's issue_url. The disposition scanner skips remote_missing tickets to avoid refetching permanently deleted issues every tick (#1875).",
            ),
        ),
    ]
