# Generated by Django 6.0.6 on 2026-06-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0059_dreamqaprobe_dreamrunmarker_consolidatedmemory"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="remote_missing",
            field=models.BooleanField(default=False),
        ),
    ]
