# Generated by Django 6.0.6 on 2026-06-09 03:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0060_ticket_remote_missing"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalStackQueueItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("overlay", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("retrying", "Retrying"),
                            ("ready", "Ready"),
                            ("done", "Done"),
                            ("dead", "Dead"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "worktree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stack_queue_items",
                        to="core.worktree",
                    ),
                ),
            ],
            options={
                "db_table": "teatree_local_stack_queue_item",
                "ordering": ["next_attempt_at", "pk"],
                "indexes": [models.Index(fields=["status", "next_attempt_at"], name="teatree_loc_status_7e9cb8_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["queued", "retrying"])),
                        fields=("worktree",),
                        name="uniq_active_stack_queue_item_per_worktree",
                    )
                ],
            },
        ),
    ]
