# Generated by Django 6.0.7 on 2026-08-06 00:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0061_prompt_body_blank"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnclaimedIntakeCandidate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("overlay", models.CharField(blank=True, default="", max_length=64)),
                ("issue_url", models.URLField(max_length=512)),
                ("title", models.CharField(blank=True, default="", max_length=512)),
                ("issue_created_at", models.DateTimeField(blank=True, null=True)),
                ("first_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "teatree_unclaimed_intake_candidate",
                "ordering": ["first_seen_at"],
                "constraints": [
                    models.UniqueConstraint(fields=("overlay", "issue_url"), name="uniq_unclaimed_intake_candidate")
                ],
            },
        ),
    ]
