# Generated by Django 6.0.7 on 2026-08-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0061_prompt_body_blank"),
    ]

    operations = [
        migrations.AddField(
            model_name="looplease",
            name="owner_pid_namespace",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
