# Generated by Django 6.0.6 on 2026-06-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0061_localstackqueueitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="worktree",
            name="last_used_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
