# Generated by Django 6.0.6 on 2026-06-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0062_worktree_last_used_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalStackReaperMarker",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("singleton", models.BooleanField(default=True, unique=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "teatree_local_stack_reaper_marker",
                "ordering": ["-last_run_at"],
            },
        ),
    ]
