# Generated by Django 6.0.6 on 2026-06-09 17:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0063_localstackreapermarker"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionAuditRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("audited_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("session_id", models.CharField(max_length=128)),
                ("corpus_entry_id", models.CharField(max_length=128)),
                ("outcome_axis", models.CharField(max_length=64)),
                ("expected_outcome", models.CharField(max_length=64)),
                ("predicted_outcome", models.CharField(max_length=64)),
                (
                    "verdict",
                    models.CharField(choices=[("pass", "Pass"), ("fail", "Fail"), ("skip", "Skip")], max_length=8),
                ),
                ("oracle", models.CharField(max_length=16)),
                ("judge_rationale", models.CharField(blank=True, default="", max_length=512)),
                ("invariant_results", models.JSONField(blank=True, default=list)),
                ("gate_failure_slugs", models.JSONField(blank=True, default=list)),
                ("nominated_for_label", models.BooleanField(default=False)),
                ("git_sha", models.CharField(blank=True, default="", max_length=64)),
                (
                    "eval_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="session_audits",
                        to="core.evalrunrecord",
                    ),
                ),
            ],
            options={
                "db_table": "teatree_session_audit",
                "ordering": ["-audited_at"],
                "indexes": [
                    models.Index(fields=["session_id", "audited_at"], name="session_audit_session_idx"),
                    models.Index(fields=["nominated_for_label", "audited_at"], name="session_audit_nominated_idx"),
                ],
            },
        ),
    ]
