# Generated by Django 6.0.7 on 2026-08-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0063_loop_lease_owner_pid_namespace"),
    ]

    operations = [
        migrations.AlterField(
            model_name="implementedissuemarker",
            name="state",
            field=models.CharField(
                choices=[
                    ("dispatched", "Dispatched"),
                    ("ticket_created", "Ticket created"),
                    ("completed", "Completed"),
                    ("abandoned", "Abandoned"),
                    ("declined", "Declined by an operator"),
                ],
                default="dispatched",
                max_length=16,
            ),
        ),
    ]
