# Generated by Django 6.0.6 on 2026-06-10 23:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0063_localstackreapermarker"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rubric",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="rubrics", to="core.ticket"
                    ),
                ),
            ],
            options={
                "db_table": "teatree_rubric",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RubricCriterion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ordinal", models.IntegerField()),
                ("text", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("pass", "Pass"), ("fail", "Fail")],
                        default="pending",
                        max_length=8,
                    ),
                ),
                ("grader_identity", models.CharField(default="", max_length=255)),
                ("reviewed_sha", models.CharField(default="", max_length=64)),
                ("rationale", models.TextField(blank=True, default="")),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rubric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="criteria_set", to="core.rubric"
                    ),
                ),
            ],
            options={
                "db_table": "teatree_rubric_criterion",
                "ordering": ["rubric", "ordinal"],
            },
        ),
        migrations.AddIndex(
            model_name="rubric",
            index=models.Index(fields=["ticket", "-created_at"], name="teatree_rub_ticket__3fafb6_idx"),
        ),
        migrations.AddConstraint(
            model_name="rubriccriterion",
            constraint=models.UniqueConstraint(fields=("rubric", "ordinal"), name="uniq_rubric_criterion_ordinal"),
        ),
    ]
