# Generated by Django 6.0.6 on 2026-06-11 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0064_rubric_rubriccriterion"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=255, unique=True)),
                ("value", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "teatree_config_setting",
                "ordering": ["key"],
            },
        ),
    ]
