# Generated by Django 6.0.7 on 2026-08-06 15:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0064_implementedissuemarker_declined"),
    ]

    operations = [
        migrations.CreateModel(
            name="InteractiveDispatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("session_id", models.CharField(blank=True, default="", max_length=200)),
                ("agent_id", models.CharField(blank=True, default="", max_length=200)),
                ("admitted_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "teatree_interactive_dispatch",
                "ordering": ["admitted_at"],
                "indexes": [models.Index(fields=["released_at", "admitted_at"], name="idx_dispatch_seat_live")],
            },
        ),
    ]
