# Generated by Django 6.0.6 on 2026-06-11 06:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0064_rubric_rubriccriterion"),
    ]

    operations = [
        migrations.CreateModel(
            name="HonestyEscalation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("session_id", models.CharField(max_length=255)),
                ("task_id", models.IntegerField(blank=True, null=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("user_asked", "User explicitly asked for honesty"),
                            ("self_assessed_dishonest", "Agent judges it was dishonest"),
                            ("accused_of_lying", "User accused the agent of lying"),
                            ("shipped_incomplete", "Shipped a job not verified complete"),
                        ],
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                ("cleared_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "teatree_honesty_escalation",
                "ordering": ["created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session_id", "task_id", "reason"), name="uniq_honestyescalation_session_task_reason"
                    )
                ],
            },
        ),
    ]
