# Generated by Django 6.0.6 on 2026-06-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0065_sessionauditrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="evalscenarioresult",
            name="cost_usd",
            field=models.FloatField(default=0.0),
        ),
    ]
