# Generated by Django 6.0.6 on 2026-06-09 17:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import ProjectState

# db_table this migration owns — kept as one constant so the existence guard and
# the CreateModel option below cannot drift apart.
_AUDIT_TABLE = "teatree_session_audit"


class CreateModelIfTableAbsent(migrations.CreateModel):
    """``CreateModel`` that no-ops the DB create when the table already exists.

    The ``teatree_session_audit`` table was renamed-then-renumbered while two
    migration forks were healed (``0064_`` -> ``0065_`` -> ``0066_sessionauditrecord``,
    #2192). A persistent DB that applied an earlier name recorded that old label
    AND already holds the table, so the renamed migration looks pending and a
    plain ``CreateModel`` re-run raises ``table "teatree_session_audit" already
    exists``. This subclass keeps the model in migration STATE (so the
    autodetector and ``makemigrations --check`` stay clean and the model is
    registered) while skipping the DATABASE create when the table is present —
    idempotent for a fresh DB, a recorder-only no-op for any old-name DB. Reuses
    Django's own ``CreateModel.database_forwards`` for the create path, so there
    is no hand-written SQL to drift from the model definition.
    """

    def database_forwards(
        self,
        app_label: str,
        schema_editor: BaseDatabaseSchemaEditor,
        from_state: ProjectState,
        to_state: ProjectState,
    ) -> None:
        # ``table_names()`` opens and closes its own cursor in a context manager
        # when none is passed -- do not hand it a cursor we would leak (#2279).
        existing = set(schema_editor.connection.introspection.table_names())
        if _AUDIT_TABLE in existing:
            return
        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0065_honestyescalation"),
    ]

    operations = [
        CreateModelIfTableAbsent(
            name="SessionAuditRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("audited_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("session_id", models.CharField(max_length=128)),
                ("corpus_entry_id", models.CharField(max_length=128)),
                ("outcome_axis", models.CharField(max_length=64)),
                ("expected_outcome", models.CharField(max_length=64)),
                ("predicted_outcome", models.CharField(max_length=64)),
                (
                    "verdict",
                    models.CharField(choices=[("pass", "Pass"), ("fail", "Fail"), ("skip", "Skip")], max_length=8),
                ),
                ("oracle", models.CharField(max_length=16)),
                ("judge_rationale", models.CharField(blank=True, default="", max_length=512)),
                ("invariant_results", models.JSONField(blank=True, default=list)),
                ("gate_failure_slugs", models.JSONField(blank=True, default=list)),
                ("nominated_for_label", models.BooleanField(default=False)),
                ("git_sha", models.CharField(blank=True, default="", max_length=64)),
                (
                    "eval_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="session_audits",
                        to="core.evalrunrecord",
                    ),
                ),
            ],
            options={
                "db_table": _AUDIT_TABLE,
                "ordering": ["-audited_at"],
                "indexes": [
                    models.Index(fields=["session_id", "audited_at"], name="session_audit_session_idx"),
                    models.Index(fields=["nominated_for_label", "audited_at"], name="session_audit_nominated_idx"),
                ],
            },
        ),
    ]
