# Generated by Django 6.0.7 on 2026-08-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0065_interactivedispatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="owner_pid",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="owner_pid_namespace",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
