# Generated by Django 6.0.6 on 2026-06-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0066_evalscenarioresult_cost_usd"),
    ]

    operations = [
        migrations.AddField(
            model_name="evalscenarioresult",
            name="cache_creation_tokens",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="evalscenarioresult",
            name="cache_read_tokens",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="evalscenarioresult",
            name="input_tokens",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="evalscenarioresult",
            name="output_tokens",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
