# Generated by Django 6.0.6 on 2026-06-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0068_evalscenarioresult_cache_creation_tokens_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evalscenarioresult",
            name="aux_cost_usd",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="evalscenarioresult",
            name="main_cost_usd",
            field=models.FloatField(default=0.0),
        ),
    ]
