# Generated by Django 6.0.6 on 2026-06-11 09:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0066_configsetting"),
        ("core", "0069_evalscenarioresult_aux_cost_usd_and_more"),
    ]

    operations = []
