# Generated by Django 6.0.7 on 2026-08-07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0069_task_owner_process"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="owner_driving_since",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
