# Generated by Django 6.0.7 on 2026-08-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0071_collapse_modes_to_five_presets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="looplease",
            name="owner_pid_namespace",
            field=models.CharField(blank=True, db_default="", default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="task",
            name="owner_pid_namespace",
            field=models.CharField(blank=True, db_default="", default="", max_length=64),
        ),
    ]
