# Generated by Django 6.0.6 on 2026-06-12 13:26

import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0071_task_claimed_by_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewLoop",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("variant", models.CharField(choices=[("external", "External"), ("self", "Self")], max_length=16)),
                ("author_phase", models.CharField(max_length=64)),
                ("reviewer_phase", models.CharField(max_length=64)),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("authoring", "Authoring"),
                            ("reviewing", "Reviewing"),
                            ("passed", "Passed"),
                            ("exhausted", "Exhausted"),
                        ],
                        default="authoring",
                        max_length=16,
                    ),
                ),
                ("round", models.IntegerField(default=0)),
                ("max_rounds", models.IntegerField(default=3)),
                (
                    "latest_verdict_kind",
                    models.CharField(
                        blank=True, choices=[("merge_safe", "Merge-safe"), ("hold", "Hold")], default="", max_length=16
                    ),
                ),
                ("latest_findings", models.JSONField(blank=True, default=list)),
                ("passed", models.BooleanField(default=False)),
                ("needs_user_input", models.BooleanField(default=False)),
                ("user_input_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.task",
                    ),
                ),
                (
                    "latest_verdict",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.reviewverdict",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="review_loops", to="core.ticket"
                    ),
                ),
            ],
            options={
                "db_table": "teatree_review_loop",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewLoopRound",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("round", models.IntegerField()),
                ("leg", models.CharField(max_length=16)),
                (
                    "review_loop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="round_slots", to="core.reviewloop"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.task",
                    ),
                ),
            ],
            options={
                "db_table": "teatree_review_loop_round",
                "constraints": [
                    models.UniqueConstraint(fields=("review_loop", "round", "leg"), name="uniq_review_loop_round_leg")
                ],
            },
        ),
    ]
