# Generated by Django 6.0.6 on 2026-06-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0072_reviewloop_reviewloopround"),
    ]

    operations = [
        migrations.AddField(
            model_name="incomingevent",
            name="parent_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="incomingevent",
            name="parent_ts",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
