# Generated by Django 6.0.7 on 2026-08-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0072_owner_pid_namespace_db_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="deferredquestion",
            name="escalated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deferredquestion",
            name="escalation_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="deferredquestionaudit",
            name="note",
            field=models.TextField(blank=True, default=""),
        ),
    ]
