# Generated by Django 6.0.6 on 2026-06-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0073_incomingevent_parent_text_incomingevent_parent_ts"),
    ]

    operations = [
        migrations.AddField(
            model_name="worktree",
            name="last_e2e_run",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
