# Generated by Django 6.0.7 on 2026-08-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0073_deferred_question_escalation"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntakeScanCursor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("overlay", models.CharField(blank=True, default="", max_length=64, unique=True)),
                ("last_issue_url", models.URLField(blank=True, default="", max_length=512)),
                ("last_issue_created_at", models.DateTimeField(blank=True, null=True)),
                ("consecutive_incomplete_passes", models.PositiveIntegerField(default=0)),
                ("last_incomplete_at", models.DateTimeField(blank=True, null=True)),
                ("last_complete_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "intake scan cursor",
            },
        ),
    ]
