# Generated by Django 6.0.6 on 2026-06-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0074_worktree_last_e2e_run"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="configsetting",
            options={"ordering": ["scope", "key"]},
        ),
        migrations.AddField(
            model_name="configsetting",
            name="scope",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="configsetting",
            name="key",
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name="configsetting",
            constraint=models.UniqueConstraint(fields=("scope", "key"), name="uniq_config_setting_scope_key"),
        ),
    ]
