# Generated by Django 6.0.7 on 2026-08-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0074_intake_scan_cursor"),
    ]

    operations = [
        migrations.AddField(
            model_name="loop",
            name="last_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
