# Generated by Django 6.0.6 on 2026-06-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0075_configsetting_scope"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoopState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("enabled", "Enabled"), ("paused", "Paused"), ("disabled", "Disabled")],
                        default="enabled",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "teatree_loop_state",
                "ordering": ["name"],
            },
        ),
    ]
