# Generated by Django 6.0.6 on 2026-06-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0076_loop_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="Loop",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, unique=True)),
                ("prompt", models.TextField(blank=True, default="")),
                ("delay_seconds", models.PositiveIntegerField()),
                ("daily_at", models.TimeField(blank=True, null=True)),
                ("enabled", models.BooleanField(default=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "teatree_loop",
                "ordering": ["name"],
            },
        ),
    ]
