# Generated by Django 6.0.7 on 2026-08-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0077_pending_chat_injection_thread_ts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autoreviewdispatch",
            name="state",
            field=models.CharField(
                choices=[("dispatched", "Dispatched"), ("resolved", "Resolved"), ("refused", "Refused")],
                default="dispatched",
                max_length=32,
            ),
        ),
    ]
