# Generated by Django 6.0.6 on 2026-06-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0078_seed_loops"),
    ]

    operations = [
        migrations.AddField(
            model_name="consolidatedmemory",
            name="disposition",
            field=models.CharField(
                choices=[
                    ("untriaged", "Untriaged"),
                    ("user_specific_keep", "User-specific (keep as memory)"),
                    ("core_gap_needs_ticket", "Core gap (needs ticket)"),
                    ("ticketed", "Ticketed"),
                    ("resolved_retired", "Resolved (retired)"),
                ],
                default="untriaged",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="consolidatedmemory",
            name="ticket_url",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
    ]
