# Generated by Django 6.0.7 on 2026-08-18 01:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0078_auto_review_dispatch_refused"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalOutcomeSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("generated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("overlay", models.CharField(blank=True, default="", max_length=64)),
                ("window_days", models.IntegerField(default=0)),
                ("status", models.CharField(default="ok", max_length=16)),
                ("repo_slugs", models.JSONField(blank=True, default=list)),
                ("merged_pr_count", models.IntegerField(default=0)),
                ("merged_pr_refs", models.JSONField(blank=True, default=list)),
            ],
            options={
                "db_table": "teatree_external_outcome_snapshot",
                "ordering": ["-generated_at"],
                "indexes": [models.Index(fields=["overlay", "generated_at"], name="eos_overlay_generated_idx")],
            },
        ),
    ]
