# Generated by Django 6.0.7 on 2026-08-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0079_external_outcome_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="worktree",
            name="occupancy_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="worktree",
            name="occupied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="worktree",
            name="occupied_by",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="worktree",
            name="occupied_by_session",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
