# Generated by Django 6.0.8 on 2026-08-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0081_plan_missing_failure_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcepressuremarker",
            name="zero_yield_passes",
            field=models.IntegerField(default=0),
        ),
    ]
