# Generated by Django 6.0.8 on 2026-09-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0084_merge_reclaim_pressure"),
    ]

    operations = [
        migrations.AddField(
            model_name="dreamrunmarker",
            name="last_failure_detail",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="dreamrunmarker",
            name="last_outcome",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
