"""Convert ``Loop.prompt`` TextField → nullable FK → :class:`Prompt` (#2513).

Staged + data-preserving. Django's autogenerated single ``AlterField`` would
DROP the text column and re-create it as an FK, losing every existing prompt
string. Instead this migration:

1. drops the old empty-string XOR constraint (it references the text column),
2. renames the text column to a temporary ``prompt_text`` so its data survives,
3. adds the nullable FK ``prompt``,
4. for every loop holding prompt text, ``get_or_create``-s a :class:`Prompt`
    (named for the loop) and points the FK at it — so the instruction text moves
    into a first-class reusable row,
5. drops the temporary ``prompt_text`` column,
6. re-adds the XOR constraint in its FK form (``prompt`` null XOR ``script``).

Reversible: the reverse rebuilds the text column from each linked prompt's body
and tears the FK back down, so a downgrade restores the prior shape exactly.
"""

import django.db.models.deletion
from django.db import migrations, models


def _text_to_prompt_fk(apps, schema_editor) -> None:
    """Move each loop's prompt text into a :class:`Prompt` row and link the FK."""
    Loop = apps.get_model("core", "Loop")
    Prompt = apps.get_model("core", "Prompt")
    for loop in Loop.objects.exclude(prompt_text="").exclude(prompt_text__isnull=True):
        prompt, _ = Prompt.objects.get_or_create(
            name=loop.name,
            defaults={"body": loop.prompt_text, "description": f"Seeded from loop {loop.name!r} (#2513)."},
        )
        loop.prompt = prompt
        loop.save(update_fields=["prompt"])


def _prompt_fk_to_text(apps, schema_editor) -> None:
    """Reverse: copy each linked prompt's body back into the text column."""
    Loop = apps.get_model("core", "Loop")
    for loop in Loop.objects.exclude(prompt__isnull=True):
        loop.prompt_text = loop.prompt.body
        loop.save(update_fields=["prompt_text"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0084_prompt"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="loop",
            name="loop_prompt_xor_script",
        ),
        migrations.RenameField(
            model_name="loop",
            old_name="prompt",
            new_name="prompt_text",
        ),
        migrations.AddField(
            model_name="loop",
            name="prompt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="loops",
                to="core.prompt",
            ),
        ),
        migrations.RunPython(_text_to_prompt_fk, _prompt_fk_to_text),
        migrations.RemoveField(
            model_name="loop",
            name="prompt_text",
        ),
        migrations.AddConstraint(
            model_name="loop",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("prompt__isnull", True), ("script__gt", ""))
                    | models.Q(("prompt__isnull", False), ("script", ""))
                ),
                name="loop_prompt_xor_script",
            ),
        ),
    ]
