# Generated by Django 6.0.8 on 2026-09-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0085_dream_marker_terminal_outcome"),
    ]

    operations = [
        migrations.AddField(
            model_name="anthropictokenusage",
            name="token_fingerprint",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
