# Generated by Django 6.0.8 on 2026-09-10 11:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0086_anthropictokenusage_token_fingerprint"),
    ]

    operations = [
        migrations.CreateModel(
            name="MergeClearDisposal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reason", models.CharField(choices=[("phantom_pr", "PR absent from the forge")], max_length=32)),
                ("evidence", models.CharField(max_length=255)),
                ("disposed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "clear",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="disposal", to="core.mergeclear"
                    ),
                ),
            ],
            options={
                "ordering": ["-disposed_at"],
            },
        ),
    ]
