# Generated by Django 6.0.6 on 2026-06-19 19:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0088_backfill_worktree_overlay_from_ticket"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandscapeArtifact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("survey", models.JSONField(default=dict)),
                ("recorded_by", models.CharField(blank=True, default="", max_length=255)),
                ("recorded_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="landscape_artifacts",
                        to="core.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "teatree_landscape_artifact",
                "ordering": ["-recorded_at"],
            },
        ),
    ]
