# Generated by Django 6.0.6 on 2026-06-19 18:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0088_backfill_worktree_overlay_from_ticket"),
    ]

    operations = [
        migrations.CreateModel(
            name="MergeableNotified",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("overlay", models.CharField(blank=True, default="", max_length=64)),
                ("slug", models.CharField(max_length=255)),
                ("pr_id", models.IntegerField()),
                ("head_sha", models.CharField(max_length=64)),
                ("pr_url", models.URLField(blank=True, default="", max_length=512)),
                ("notified_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "teatree_mergeable_notified",
                "ordering": ["-notified_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("slug", "pr_id", "head_sha"), name="uniq_mergeable_notified_slug_pr_head"
                    )
                ],
            },
        ),
    ]
