# Generated by Django 6.0.8 on 2026-09-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0089_issue_closed_failure_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskattempt",
            name="usage_unknown",
            field=models.BooleanField(default=False),
        ),
    ]
