# Generated by Django 6.0.8 on 2026-09-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0090_taskattempt_usage_unknown"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="taskattempt",
            index=models.Index(fields=["lane", "ended_at"], name="taskattempt_lane_ended"),
        ),
    ]
