# Generated by Django 6.0.6 on 2026-06-20 07:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0091_remove_orphan_slack_answer_loop"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="redis_db_index",
        ),
    ]
