# Generated by Django 6.1.1 on 2026-09-23 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0091_taskattempt_taskattempt_lane_ended"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="taskattempt",
            index=models.Index(
                condition=models.Q(("ended_at__isnull", False)),
                fields=["-ended_at", "-id"],
                name="taskattempt_recent_ended",
            ),
        ),
    ]
