# Generated by Django 6.1.1 on 2026-09-25 18:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0092_taskattempt_taskattempt_recent_ended"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitHubAppInstallation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("installation_id", models.BigIntegerField(unique=True)),
                ("app_id", models.BigIntegerField()),
                ("account_login", models.CharField(max_length=255)),
                ("account_type", models.CharField(blank=True, default="", max_length=32)),
                (
                    "repository_selection",
                    models.CharField(
                        choices=[("all", "All repositories"), ("selected", "Selected repositories")],
                        default="selected",
                        max_length=16,
                    ),
                ),
                ("active_repositories", models.JSONField(blank=True, default=list)),
                ("pending_repositories", models.JSONField(blank=True, default=list)),
                ("permissions", models.JSONField(blank=True, default=dict)),
                ("events", models.JSONField(blank=True, default=list)),
                ("overlay", models.CharField(blank=True, default="", max_length=255)),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                ("last_verified_delivery_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "teatree_github_app_installation",
                "ordering": ["account_login"],
            },
        ),
        migrations.CreateModel(
            name="WebhookRejection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("slack", "Slack"),
                            ("gitlab", "GitLab"),
                            ("github", "GitHub"),
                            ("notion", "Notion"),
                            ("ci", "CI"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("signature_invalid", "Signature invalid"),
                            ("oversized", "Payload too large"),
                            ("no_secret", "No secret configured"),
                            ("rate_limited", "Rate limited"),
                            ("stale_replay", "Stale replay"),
                            ("duplicate_suppressed", "Duplicate suppressed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("delivery_id", models.CharField(blank=True, default="", max_length=255)),
                ("detail", models.TextField(blank=True, default="")),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "teatree_webhook_rejection",
                "ordering": ["-occurred_at"],
                "indexes": [models.Index(fields=["source", "occurred_at"], name="teatree_web_source_b96c76_idx")],
            },
        ),
        migrations.CreateModel(
            name="GitHubPollCursor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("repo_full_name", models.CharField(max_length=255)),
                ("event_family", models.CharField(max_length=64)),
                ("cursor_value", models.CharField(blank=True, default="", max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poll_cursors",
                        to="core.githubappinstallation",
                    ),
                ),
            ],
            options={
                "db_table": "teatree_github_poll_cursor",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("installation", "repo_full_name", "event_family"),
                        name="uniq_githubpollcursor_installation_repo_family",
                    )
                ],
            },
        ),
    ]
