# Generated by Django 6.0.8 on 2026-08-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0092_the_eval_and_triage_rows_are_the_cadence"),
    ]

    operations = [
        migrations.AddField(
            model_name="configsetting",
            name="written_by",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
