# Generated by Django 6.1.1 on 2026-09-24 22:52

import django_fsm
from django.db import migrations

_STATE_RENAMES = {
    "started": "work_started",
    "planned": "plan_recorded",
    "reviewed": "self_reviewed",
    "shipped": "pr_opened",
    "in_review": "review_requested",
    "review_posted": "review_delivered",
    "retrospected": "retro_recorded",
}
_REVERSE_STATE_RENAMES = {new: old for old, new in _STATE_RENAMES.items()}


def _rewrite_states(apps, schema_editor, *, mapping):
    """Rewrite ``Ticket.state`` plus the ``ignored_from``/``reopened_from`` snapshots in ``extra``.

    ``unignore()`` reads ``extra['ignored_from']`` and assigns it straight to
    ``self.state``, bypassing FSM validation — a stale pre-rename value there
    would land a future unignore on an invalid state, so it is rewritten
    alongside the column itself. ``reopened_from`` is write-only today but
    rewritten too so the audit trail never reads a retired name.
    """
    ticket_model = apps.get_model("core", "Ticket")
    for old, new in mapping.items():
        ticket_model.objects.filter(state=old).update(state=new)
    for ticket in ticket_model.objects.all().iterator():
        extra = ticket.extra if isinstance(ticket.extra, dict) else None
        if not extra:
            continue
        changed = False
        for key in ("ignored_from", "reopened_from"):
            value = extra.get(key)
            if value in mapping:
                extra[key] = mapping[value]
                changed = True
        if changed:
            ticket.extra = extra
            ticket.save(update_fields=["extra"])


def _rename_forward(apps, schema_editor):
    _rewrite_states(apps, schema_editor, mapping=_STATE_RENAMES)


def _rename_reverse(apps, schema_editor):
    _rewrite_states(apps, schema_editor, mapping=_REVERSE_STATE_RENAMES)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0092_taskattempt_taskattempt_recent_ended"),
    ]

    operations = [
        migrations.RunPython(_rename_forward, _rename_reverse),
        migrations.AlterField(
            model_name="ticket",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("not_started", "Not started"),
                    ("scoped", "Scoped"),
                    ("work_started", "Work started"),
                    ("plan_recorded", "Plan recorded"),
                    ("coded", "Coded"),
                    ("tested", "Tested"),
                    ("self_reviewed", "Self-reviewed"),
                    ("pr_opened", "Shipped"),
                    ("review_requested", "In peer review"),
                    ("merged", "Merged"),
                    ("retro_recorded", "Retrospected"),
                    ("delivered", "Delivered"),
                    ("review_delivered", "Review posted"),
                    ("ignored", "Ignored"),
                ],
                default="not_started",
                max_length=32,
            ),
        ),
    ]
