# Generated by Django 6.0.8 on 2026-09-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0096_the_sweep_dogfood_and_housekeeping_rows_are_the_cadence"),
    ]

    operations = [
        migrations.AddField(
            model_name="looplease",
            name="last_acquired_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
