# Generated by Django 6.0.8 on 2026-09-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0109_clear_the_retired_on_behalf_dial_rows"),
    ]

    operations = [
        migrations.AddField(
            model_name="mergeclear",
            name="merged_without_squash",
            field=models.BooleanField(default=False),
        ),
    ]
