# Generated by Django 6.0.8 on 2026-09-24 14:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0116_merge_vendor_core_leaves"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketSweepRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("run_id", models.CharField(max_length=64, unique=True)),
                ("source", models.CharField(default="interactive", max_length=16)),
                ("overlay", models.CharField(blank=True, default="", max_length=64)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("examined_count", models.PositiveIntegerField(default=0)),
                ("external_skipped_count", models.PositiveIntegerField(default=0)),
                ("changed_urls", models.JSONField(default=list)),
            ],
            options={
                "db_table": "teatree_ticket_sweep_run",
                "ordering": ["-started_at"],
            },
        ),
    ]
