# Generated by Django 6.1.1 on 2026-09-24 22:52

import django_fsm
from django.db import migrations

_STATE_RENAMES = {
    "started": "work_started",
    "planned": "plan_recorded",
    "reviewed": "self_reviewed",
    "shipped": "pr_opened",
    "in_review": "review_requested",
    "review_posted": "review_delivered",
    "retrospected": "retro_recorded",
}
_REVERSE_STATE_RENAMES = {new: old for old, new in _STATE_RENAMES.items()}


def _rewrite_states(apps, schema_editor, *, mapping):
    """Rewrite ``Ticket.state``, the ``ignored_from``/``reopened_from`` snapshots in ``extra``, and the transition history.

    ``unignore()`` assigns ``extra['ignored_from']`` straight to ``self.state``, bypassing
    FSM validation, so a stale pre-rename snapshot would land a future unignore on an
    invalid state.
    """
    db_alias = schema_editor.connection.alias
    tickets = apps.get_model("core", "Ticket").objects.using(db_alias)
    for old, new in mapping.items():
        tickets.filter(state=old).update(state=new)
    for ticket in tickets.filter(extra__has_any_keys=["ignored_from", "reopened_from"]).iterator():
        extra = ticket.extra
        renamed = {key: mapping[extra[key]] for key in ("ignored_from", "reopened_from") if extra.get(key) in mapping}
        if renamed:
            tickets.filter(pk=ticket.pk).update(extra={**extra, **renamed})
    transitions = apps.get_model("core", "TicketTransition").objects.using(db_alias)
    for old, new in mapping.items():
        transitions.filter(from_state=old).update(from_state=new)
        transitions.filter(to_state=old).update(to_state=new)


def _rename_forward(apps, schema_editor):
    _rewrite_states(apps, schema_editor, mapping=_STATE_RENAMES)


def _rename_reverse(apps, schema_editor):
    _rewrite_states(apps, schema_editor, mapping=_REVERSE_STATE_RENAMES)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0118_carry_the_dream_toggles_onto_their_settings"),
    ]

    operations = [
        migrations.RunPython(_rename_forward, _rename_reverse),
        migrations.AlterField(
            model_name="ticket",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("not_started", "Not started"),
                    ("scoped", "Scoped"),
                    ("work_started", "Work started"),
                    ("plan_recorded", "Plan recorded"),
                    ("coded", "Coded"),
                    ("tested", "Tested"),
                    ("self_reviewed", "Self-reviewed"),
                    ("pr_opened", "PR opened"),
                    ("review_requested", "In peer review"),
                    ("merged", "Merged"),
                    ("retro_recorded", "Retro recorded"),
                    ("delivered", "Delivered"),
                    ("review_delivered", "Review delivered"),
                    ("ignored", "Ignored"),
                ],
                default="not_started",
                max_length=32,
            ),
        ),
    ]
