# Generated by Django 6.1.1 on 2026-09-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0120_attempt_conversation_facts_and_cli_too_old"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingarticlesuggestion",
            name="kind",
            field=models.CharField(
                choices=[("news_article", "News article"), ("memory_reconciliation", "Memory reconciliation")],
                default="news_article",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="pendingarticlesuggestion",
            name="url",
            field=models.URLField(blank=True, default="", max_length=1024),
        ),
    ]
