# Generated by Django 6.1.1 on 2026-09-25 20:40

import django.utils.timezone
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0121_deferred_question_task_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerGeneration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sha", models.CharField(max_length=40, unique=True)),
                ("image", models.CharField(max_length=255)),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("starting", "Starting"),
                            ("active", "Active"),
                            ("draining", "Draining"),
                            ("retired", "Retired"),
                            ("failed", "Failed"),
                        ],
                        default="starting",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("drain_requested_at", models.DateTimeField(blank=True, null=True)),
                ("drain_deadline", models.DateTimeField(blank=True, null=True)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="claimed_generation",
            field=models.CharField(blank=True, db_default="", default="", max_length=40),
        ),
    ]
