"""Real-git integration tests for the git-hook installation probe."""

from pathlib import Path
from unittest.mock import patch

import pytest

from teatree.core import hook_quarantine
from teatree.core.gates.git_hooks_preflight import (
    GATES_BY_HOOK,
    PREK_CONFIG_NAME,
    REQUIRED_HOOK_NAMES,
    format_remediation,
    probe_checkouts,
    probe_git_hooks,
)
from teatree.utils import run as run_mod
from teatree.utils.git_worktree_query import git_common_dir
from tests._git_repo import make_git_repo, run_git

#: The prek marker is written out here rather than imported: a fixture that reads its
#: expectations off the module under test cannot catch that module being wrong.
_PREK_SHIM = (
    "#!/bin/sh\n"
    "# File generated by prek: https://github.com/j178/prek\n"
    'exec prek hook-impl --hook-type={name}{cd} -- "$@"\n'
)


def install_hooks(repo: Path, *names: str) -> Path:
    """Write sound prek shims for *names* (default: every required hook).

    A hook is installed only when it is prek's own and bound to the repo root, so an
    executable stand-in carrying no marker is a checkout with no working gate.
    """
    hooks_dir = repo / ".git" / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    for name in names or REQUIRED_HOOK_NAMES:
        hook = hooks_dir / name
        hook.write_text(_PREK_SHIM.format(name=name, cd=""), encoding="utf-8")
        hook.chmod(0o755)
    return hooks_dir


def install_prek_shims(repo: Path, *, config_dir: str | None = None) -> Path:
    """Write prek-generated shims for every required hook, optionally bound to *config_dir*."""
    hooks_dir = repo / ".git" / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    cd = f' --cd="{config_dir}"' if config_dir else ""
    for name in REQUIRED_HOOK_NAMES:
        hook = hooks_dir / name
        hook.write_text(_PREK_SHIM.format(name=name, cd=cd), encoding="utf-8")
        hook.chmod(0o755)
    return hooks_dir


def make_prek_checkout(path: Path) -> Path:
    repo = make_git_repo(path)
    (repo / PREK_CONFIG_NAME).write_text("repos: []\n", encoding="utf-8")
    return repo


class TestProbeGitHooks:
    def test_fresh_repo_reports_both_hooks_missing(self, tmp_path: Path) -> None:
        repo = make_git_repo(tmp_path / "repo")

        probe = probe_git_hooks(repo)

        assert probe.missing == REQUIRED_HOOK_NAMES
        assert not probe.ok
        assert probe.installable

    def test_sample_hooks_do_not_count_as_installed(self, tmp_path: Path) -> None:
        repo = make_git_repo(tmp_path / "repo")
        sample = repo / ".git" / "hooks" / "pre-push.sample"
        sample.parent.mkdir(parents=True, exist_ok=True)
        sample.write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
        sample.chmod(0o755)

        assert "pre-push" in probe_git_hooks(repo).missing

    def test_non_executable_hook_counts_as_missing(self, tmp_path: Path) -> None:
        repo = make_git_repo(tmp_path / "repo")
        install_hooks(repo)
        (repo / ".git" / "hooks" / "pre-commit").chmod(0o644)

        assert probe_git_hooks(repo).missing == ("pre-commit",)

    def test_a_hand_written_hook_prek_never_wrote_counts_as_missing(self, tmp_path: Path) -> None:
        """An operator's own executable gate is not this repo's prek gate, so the repair must reach it.

        Nothing else pins the acceptor's positive form: asking only whether a FOREIGN-config
        fault was detected reports "installed" for a hook prek never wrote at all, so the
        re-install that would preserve and replace it never runs.
        """
        repo = make_git_repo(tmp_path / "repo")
        install_hooks(repo)
        hand_written = repo / ".git" / "hooks" / "pre-push"
        hand_written.write_text("#!/bin/sh\n# the operator's own pre-push gate\nexit 0\n", encoding="utf-8")
        hand_written.chmod(0o755)

        assert probe_git_hooks(repo).missing == ("pre-push",)

    def test_installed_hooks_pass(self, tmp_path: Path) -> None:
        repo = make_git_repo(tmp_path / "repo")
        hooks_dir = install_hooks(repo)

        probe = probe_git_hooks(repo)

        assert probe.ok
        assert probe.missing == ()
        assert probe.hooks_dir == hooks_dir.resolve()

    def test_worktree_inherits_the_common_dir_verdict(self, tmp_path: Path) -> None:
        repo = make_git_repo(tmp_path / "repo")
        worktree = tmp_path / "wt"
        run_git(repo, "worktree", "add", "-q", "-b", "feature", str(worktree))

        assert probe_git_hooks(worktree).missing == REQUIRED_HOOK_NAMES

        install_hooks(repo)

        assert probe_git_hooks(worktree).ok

    def test_deliberate_hooks_path_is_reported_not_judged(self, tmp_path: Path) -> None:
        repo = make_git_repo(tmp_path / "repo")
        elsewhere = tmp_path / "operator-hooks"
        elsewhere.mkdir()
        run_git(repo, "config", "core.hooksPath", str(elsewhere))

        probe = probe_git_hooks(repo)

        assert probe.custom_hooks_path == str(elsewhere)
        assert probe.missing == ()
        assert not probe.installable

    def test_hooks_path_pointing_at_the_default_dir_is_not_custom(self, tmp_path: Path) -> None:
        repo = make_git_repo(tmp_path / "repo")
        install_hooks(repo)
        run_git(repo, "config", "core.hooksPath", str(repo / ".git" / "hooks"))

        probe = probe_git_hooks(repo)

        assert probe.custom_hooks_path is None
        assert probe.ok

    def test_non_repo_is_indeterminate_not_missing(self, tmp_path: Path) -> None:
        probe = probe_git_hooks(tmp_path)

        assert probe.indeterminate_reason is not None
        assert probe.missing == ()
        assert not probe.ok


class TestAShimBoundToAnotherConfig:
    """`prek install` run from a subdirectory bakes `--cd=<subdir>` into the shim.

    The repo's gate then becomes that subdirectory's config: in a checkout vendoring
    another project, every host hook stops running and the vendored project's
    development lane gates the host instead. The file is present and executable, so a
    presence-only probe reports it installed — and `t3 setup`, which keys off that
    verdict, never reaches the repair written for exactly this case.
    """

    def test_a_shim_bound_to_a_nested_config_counts_as_missing(self, tmp_path: Path) -> None:
        repo = make_git_repo(tmp_path / "repo")
        install_prek_shims(repo, config_dir="vendor/teatree")

        probe = probe_git_hooks(repo)

        assert probe.missing == REQUIRED_HOOK_NAMES
        assert not probe.ok

    def test_a_root_bound_shim_still_counts_as_installed(self, tmp_path: Path) -> None:
        repo = make_git_repo(tmp_path / "repo")
        install_prek_shims(repo)

        assert probe_git_hooks(repo).ok


#: A legacy hook nobody wrote as UTF-8 — the `.git/hooks` any long-lived clone may hold.
#: `UnicodeDecodeError` is a `ValueError`, so it escaped every handler catching `OSError`.
_LATIN1_HOOK = "#!/bin/sh\n# caf\xe9 legacy hook\nexit 0\n".encode("latin-1")


def write_undecodable_hook(repo: Path, name: str) -> Path:
    hooks_dir = repo / ".git" / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    hook = hooks_dir / name
    hook.write_bytes(_LATIN1_HOOK)
    hook.chmod(0o755)
    return hook


class TestAnUndecodableHookIsNotASoundGate:
    """A file nothing can read is not evidence that this repo's gate is installed.

    The probe asked whether a FAULT had been detected, and an unreadable file exhibits
    none — so an undecodable `pre-push` was counted installed, `t3 setup` printed
    `already installed`, and the leak gate and `dev/push-gate.sh` never fired again.
    """

    def test_a_latin1_pre_push_is_reported_missing(self, tmp_path: Path) -> None:
        repo = make_prek_checkout(tmp_path / "repo")
        install_hooks(repo, "pre-commit")
        write_undecodable_hook(repo, "pre-push")

        probe = probe_git_hooks(repo)

        assert probe.missing == ("pre-push",)
        assert probe.ok is False

    def test_a_sound_prek_pre_push_is_reported_installed(self, tmp_path: Path) -> None:
        """The control: a gate that fails closed on everything reports every repo ungated."""
        repo = make_prek_checkout(tmp_path / "repo")
        install_hooks(repo)

        probe = probe_git_hooks(repo)

        assert probe.ok
        assert probe.missing == ()

    def test_a_foreign_cd_shim_is_still_reported_missing(self, tmp_path: Path) -> None:
        """The control the other way: an acceptor checking only the marker re-opens #4193."""
        repo = make_prek_checkout(tmp_path / "repo")
        install_hooks(repo, "pre-commit")
        install_prek_shims(repo, config_dir="vendor/core")

        assert probe_git_hooks(repo).missing == REQUIRED_HOOK_NAMES


class TestProbeCheckouts:
    def test_a_protected_clone_never_vouches_for_an_unprotected_one(self, tmp_path: Path) -> None:
        """The whole bug: hooks installed in one clone, absent in another."""
        container = make_prek_checkout(tmp_path / "container-clone")
        install_hooks(container)
        host = make_prek_checkout(tmp_path / "host-checkout")

        probes = probe_checkouts([container, host])

        assert [probe.checkout for probe in probes] == [container, host]
        assert probes[0].ok
        assert not probes[1].ok
        assert probes[1].missing == REQUIRED_HOOK_NAMES

    def test_worktrees_collapse_onto_their_clone_verdict(self, tmp_path: Path) -> None:
        clone = make_prek_checkout(tmp_path / "clone")
        first = tmp_path / "wt-a"
        second = tmp_path / "wt-b"
        for path, branch in ((first, "a"), (second, "b")):
            run_git(clone, "worktree", "add", "-q", "-b", branch, str(path))

        probes = probe_checkouts([clone, first, second])

        assert [probe.checkout for probe in probes] == [clone]

    def test_checkout_without_a_prek_config_is_skipped(self, tmp_path: Path) -> None:
        plain = make_git_repo(tmp_path / "plain")

        assert probe_checkouts([plain]) == []


class TestFormatRemediation:
    def test_names_the_checkout_each_missing_hook_and_the_install_command(self, tmp_path: Path) -> None:
        repo = make_git_repo(tmp_path / "repo")

        text = "\n".join(format_remediation(probe_git_hooks(repo)))

        assert str(repo) in text
        assert "pre-commit" in text
        assert "pre-push" in text
        assert "t3 setup" in text

    def test_installed_repo_needs_no_remediation(self, tmp_path: Path) -> None:
        repo = make_git_repo(tmp_path / "repo")
        install_hooks(repo)

        assert format_remediation(probe_git_hooks(repo)) == []


@pytest.mark.parametrize("name", REQUIRED_HOOK_NAMES)
def test_each_required_hook_documents_the_gates_it_carries(name: str) -> None:
    assert GATES_BY_HOOK[name]


class TestTheProbeCarriesTheQuarantine:
    """The doctor and the installer line read ONE computation, so they cannot disagree."""

    @staticmethod
    def _park(repo: Path, name: str, blob: bytes) -> Path:
        parked = hook_quarantine.quarantine_dir(git_common_dir(repo))
        parked.mkdir(parents=True, exist_ok=True)
        (parked / name).write_bytes(blob)
        return parked / name

    def test_a_clean_checkout_reports_nothing_parked(self, tmp_path: Path) -> None:
        repo = make_git_repo(tmp_path / "repo")

        assert probe_git_hooks(repo).quarantined == ()

    def test_a_parked_hook_is_reported_and_fails_the_remediation(self, tmp_path: Path) -> None:
        repo = make_git_repo(tmp_path / "repo")
        parked = self._park(repo, "pre-push", b"#!/bin/sh\nexit 0\n")

        probe = probe_git_hooks(repo)

        assert probe.quarantined == (parked,)
        assert any(str(parked) in line for line in format_remediation(probe)), format_remediation(probe)

    def test_an_unreadable_quarantine_is_none_and_still_reported(self, tmp_path: Path) -> None:
        repo = make_git_repo(tmp_path / "repo")
        hook_quarantine.quarantine_dir(git_common_dir(repo)).mkdir(parents=True)

        def _refuse(self: Path) -> None:
            raise PermissionError(13, "Permission denied", str(self))

        with patch.object(Path, "iterdir", _refuse):
            probe = probe_git_hooks(repo)

        assert probe.quarantined is None
        assert any(hook_quarantine.QUARANTINE_DIRNAME in line for line in format_remediation(probe))

    def test_the_two_findings_are_independent_sections(self, tmp_path: Path) -> None:
        """A fully-installed clone can still be holding a gate that is no longer running."""
        repo = make_git_repo(tmp_path / "repo")
        parked = self._park(repo, "pre-push", b"#!/bin/sh\nexit 0\n")

        lines = format_remediation(probe_git_hooks(repo))

        assert any("is not running its git hooks" in line for line in lines), lines
        assert any(str(parked) in line for line in lines), lines


class TestAMissingGitBinaryNeverPropagates:
    """`GitHooksInstaller.install` does not wrap this probe, and `t3 setup` runs under `set -e`.

    The canonical `git_common_dir` lets an `OSError` out — an unreachable binary would
    traceback out of container init instead of reporting one unprobeable checkout.
    """

    def test_a_missing_git_binary_reads_as_indeterminate_not_a_raise(self, tmp_path: Path) -> None:
        repo = make_git_repo(tmp_path / "repo")

        with patch.object(run_mod, "subprocess") as mock_sp:
            mock_sp.run.side_effect = FileNotFoundError(2, "No such file or directory", "git")
            probe = probe_git_hooks(repo)

        assert probe.indeterminate_reason is not None
        assert probe.hooks_dir is None

    def test_a_reachable_git_binary_still_probes_the_checkout(self, tmp_path: Path) -> None:
        """The control: a guard returning `None` unconditionally passes the test above."""
        repo = make_git_repo(tmp_path / "repo")

        probe = probe_git_hooks(repo)

        assert probe.indeterminate_reason is None
        assert probe.hooks_dir == (repo / ".git" / "hooks").resolve()


class TestTheDoctorStaysSilentOnAnUnprobeableCheckout:
    """The other polarity of the installer's "must speak": a line here is a hard doctor FAIL.

    ``checks_bootstrap._check_git_hooks_installed`` reads any remediation line as a failure, so
    emitting one for a checkout nothing could inspect attributes a cause the probe never found.
    """

    def test_format_remediation_stays_silent_on_an_unprobeable_checkout(self, tmp_path: Path) -> None:
        not_a_checkout = tmp_path / "plain"
        not_a_checkout.mkdir()
        probe = probe_git_hooks(not_a_checkout)
        assert probe.indeterminate_reason is not None, "the fixture turned out to be a checkout"

        assert format_remediation(probe) == []

    def test_format_remediation_still_reports_a_probeable_gap(self, tmp_path: Path) -> None:
        """The control: returning `[]` unconditionally passes the test above."""
        repo = make_git_repo(tmp_path / "repo")

        assert format_remediation(probe_git_hooks(repo)) != []
